

-- PATTERN {DATA, OPERATORE_CHIAMATO, UTENTE_CHIAMATO}
CREATE VIEW SQL_OLAP AS
SELECT	DATA, OPERATORE_CHIAMATO, UTENTE_CHIAMATO, 
		DURATA_MEDIA = SUM(SOMMA_DURATA) / SUM(COUNT_DURATA),
		NUM_SIM_CHIAMANTI = COUNT(DISTINCT SIM_CHIAMANTE),
		NUM_SIM_CHIAMATE = SUM(NUM_SIM_CHIAMATE)
FROM STARSCHEMA
GROUP BY DATA, OPERATORE_CHIAMATO, UTENTE_CHIAMATO WITH CUBE

-- CONTROLLO CHE NUM_SIM_CHIAMATE SIA CALCOLABILE 

SELECT DATA, OPERATORE_CHIAMATO, UTENTE_CHIAMATO, NUM_SIM_CHIAMATE
FROM SQL_OLAP
ORDER BY NUM_SIM_CHIAMATE DESC

SELECT	DATA, OPERATORE_CHIAMATO, UTENTE_CHIAMATO, SIM_CHIAMANTE,
		NUM_SIM_CHIAMATE = COUNT(DISTINCT A_CHIAMATA)
FROM PER_FT
GROUP BY DATA, OPERATORE_CHIAMATO, UTENTE_CHIAMATO, SIM_CHIAMANTE
ORDER BY NUM_SIM_CHIAMATE DESC

-- ERRORE NON CALCOLABILE, NEL PATTERN MANCA SIM_CHIAMANTE


-- WINDOW FUNCTION
CREATE VIEW PATTERN_DATA_OPERATORE_CHIAMATO AS
SELECT	DATA, OPERATORE_CHIAMATO, 
		DURATA_MEDIA = SUM(SOMMA_DURATA) / SUM(COUNT_DURATA),
		NUM_SIM_CHIAMANTI = COUNT(DISTINCT SIM_CHIAMANTE)
FROM STARSCHEMA
GROUP BY DATA, OPERATORE_CHIAMATO


SELECT	*,
		SUM(NUM_SIM_CHIAMANTI) OVER (PARTITION BY OPERATORE_CHIAMATO) AS TOTALE_NUM_SIM_CHIAMANTE_PER_OPERATORE,
		SUM(NUM_SIM_CHIAMANTI) OVER (PARTITION BY OPERATORE_CHIAMATO ORDER BY DATA) AS TOTALE_NUM_SIM_CHIAMANTE_PER_OPERATORE_TO_DATE,
		(CAST(SUM(DURATA_MEDIA) OVER (PARTITION BY OPERATORE_CHIAMATO) AS REAL) / COUNT(DURATA_MEDIA) OVER (PARTITION BY OPERATORE_CHIAMATO)) AS DURATA_MEDIA_PER_OPERATORE
FROM PATTERN_DATA_OPERATORE_CHIAMATO

WITH OPERATORE_RANKED AS
(
SELECT	*,
		RANK() OVER (PARTITION BY OPERATORE_CHIAMATO ORDER BY DURATA_MEDIA DESC) AS [RANK]
FROM PATTERN_DATA_OPERATORE_CHIAMATO
)
SELECT * 
FROM OPERATORE_RANKED
WHERE [RANK] = 1


