


-- DIMENSION TABLE SIM_CHIAMANTE
CREATE VIEW DT_SIM_CHIAMANTE AS
SELECT SIM_CHIAMANTE.SIM AS SIM_CHIAMANTE, SIM_CHIAMANTE_PREFISSO.PREFISSO AS PREFISSO_CHIAMANTE, SIM_CHIAMANTE_PREFISSO.OPERATORE AS OPERATORE_CHIAMANTE, 
                  SIM_CHIAMANTE.TARIFFA AS TARIFFA_CHIAMANTE, dbo.UTENTE.UTENTE AS UTENTE_CHIAMANTE, dbo.UTENTE.CITTA AS UTENTE_CHIAMANTE_CITTA
FROM     dbo.PREFISSO AS SIM_CHIAMANTE_PREFISSO INNER JOIN
                  dbo.SIM AS SIM_CHIAMANTE ON SIM_CHIAMANTE_PREFISSO.PREFISSO = SIM_CHIAMANTE.PREFISSO INNER JOIN
                  dbo.UTENTE ON SIM_CHIAMANTE.UTENTE = dbo.UTENTE.UTENTE

SELECT COUNT(*) FROM SIM

-- DIMENSION TABLE UTENTE_CHIAMATO
CREATE VIEW DT_UTENTE_CHIAMATO AS
SELECT *
FROM UTENTE

-- DIMENSIONE TABLE OPERATORE_CHIAMATO
CREATE VIEW DT_OPERATORE_CHIAMATO AS
SELECT DISTINCT OPERATORE
FROM PREFISSO

-- VISTA APPOGGIO
ALTER VIEW PER_FT AS
SELECT dbo.TELEFONATA.DATA, dbo.TELEFONATA.DA_CHIAMANTE AS SIM_CHIAMANTE, SIM_1.UTENTE AS UTENTE_CHIAMATO, dbo.PREFISSO.OPERATORE AS OPERATORE_CHIAMATO, dbo.TELEFONATA.A_CHIAMATA, dbo.TELEFONATA.DURATA
FROM     dbo.TELEFONATA INNER JOIN
                  dbo.SIM AS SIM_1 INNER JOIN
                  dbo.PREFISSO ON SIM_1.PREFISSO = dbo.PREFISSO.PREFISSO ON dbo.TELEFONATA.A_CHIAMATA = SIM_1.SIM

SELECT COUNT(*) FROM TELEFONATA
SELECT COUNT(*) FROM PER_FT

-- FACT TABLE
CREATE VIEW FACT_TABLE AS
SELECT	DATA,SIM_CHIAMANTE, OPERATORE_CHIAMATO, UTENTE_CHIAMATO,
		SUM(DURATA) AS SOMMA_DURATA, COUNT(DURATA) AS COUNT_DURATA,
		COUNT(DISTINCT A_CHIAMATA) AS NUM_SIM_CHIAMATE 
FROM PER_FT
GROUP BY DATA,SIM_CHIAMANTE, OPERATORE_CHIAMATO, UTENTE_CHIAMATO



-- STAR SCHEMA VIRTUALE
CREATE VIEW STARSCHEMA AS
SELECT dbo.FACT_TABLE.OPERATORE_CHIAMATO, dbo.FACT_TABLE.UTENTE_CHIAMATO, dbo.DT_UTENTE_CHIAMATO.CITTA AS UTENTE_CHIAMATO_CITTA, dbo.DT_SIM_CHIAMANTE.*, dbo.FACT_TABLE.DATA, 
                  dbo.FACT_TABLE.SOMMA_DURATA, dbo.FACT_TABLE.COUNT_DURATA, dbo.FACT_TABLE.NUM_SIM_CHIAMATE
FROM     dbo.FACT_TABLE INNER JOIN
                  dbo.DT_SIM_CHIAMANTE ON dbo.FACT_TABLE.SIM_CHIAMANTE = dbo.DT_SIM_CHIAMANTE.SIM_CHIAMANTE INNER JOIN
                  dbo.DT_OPERATORE_CHIAMATO ON dbo.FACT_TABLE.OPERATORE_CHIAMATO = dbo.DT_OPERATORE_CHIAMATO.OPERATORE INNER JOIN
                  dbo.DT_UTENTE_CHIAMATO ON dbo.FACT_TABLE.UTENTE_CHIAMATO = dbo.DT_UTENTE_CHIAMATO.UTENTE

SELECT COUNT(*) FROM STARSCHEMA
SELECT COUNT(*) FROM FACT_TABLE