--- Esercitazione Martedì 4 Marzo  2025

-- 1. Creare un db in SQL ed eseguire passo passo le seguenti istruzioni

CREATE TABLE ISCRIZIONI (
	AA varchar(10),
	STUD varchar(10),
	CDL varchar(10),
	PRES_CDL varchar(10),
	CLASSE varchar(10),
	TIPO varchar(10),
	TASSE smallint
);


-- Inserimento dati nella tabella ISCRIZIONI
INSERT INTO ISCRIZIONI VALUES ('2017', 'A', 'LM_INFO', 'P1', 'LM32', 'LM', 110)
INSERT INTO ISCRIZIONI VALUES ('2017', 'D', 'LT_INF', 'P3', 'L08', 'LT', 100)
INSERT INTO ISCRIZIONI VALUES ('2018', 'A', 'LM_INFO', 'P1', 'LM32', 'LM', 120)
INSERT INTO ISCRIZIONI VALUES ('2018', 'B', 'LM_GEST', 'P2', 'LM31', 'LM', 150)
INSERT INTO ISCRIZIONI VALUES ('2018', 'C', 'LM_INFO', 'P1', 'LM32', 'LM', 100)
INSERT INTO ISCRIZIONI VALUES ('2018', 'D', 'LT_INF', 'P3', 'L08', 'LT', 140)
INSERT INTO ISCRIZIONI VALUES ('2018', 'E', 'LT_INF_MN', 'P4', 'L08', 'LT', 80)

SELECT * FROM ISCRIZIONI


-- SQL-OLAP: Pattern in SQL 
SELECT CLASSE, NISCR=count(*)  
FROM ISCRIZIONI  
GROUP BY CLASSE

SELECT CLASSE, AA, NISCR=count(*)  
FROM ISCRIZIONI  
GROUP BY CLASSE,AA

SELECT CDL, NISCR = count(*)
FROM ISCRIZIONI
GROUP BY CDL

SELECT AA, TASSE_TOT = sum(TASSE)
FROM ISCRIZIONI
GROUP BY AA

-- SQL-OLAP: Gli operatori CUBE e ROLLUP

-- SQL-OLAP: Operatore CUBE 
SELECT AA,CLASSE, NISCR=count(*)  
FROM ISCRIZIONI  
GROUP BY AA, CLASSE WITH CUBE

SELECT AA,CLASSE, NISCR=count(*)  
FROM ISCRIZIONI  
GROUP BY CUBE(AA, CLASSE)

-- Restituisce tutte le possibili combinazione tra gli elementi del group by
-- Ordine nel group by irrelevante
-- Introduce un elemento poliformo NULL


-- GROUPING è in grado di individuare il valore poliformo NULL e distinguerlo dal normale valore NULL dei DBMS (funzione booleana)
SELECT AA,CLASSE, NISCR=count(*), GROUPING(CLASSE) AS AGGREGO_CLASSE
FROM ISCRIZIONI  
GROUP BY AA, CLASSE WITH CUBE

SELECT AA,CLASSE, NISCR=count(*), GROUPING(AA) AS AGGREGO_AA
FROM ISCRIZIONI  
GROUP BY AA, CLASSE WITH CUBE

SELECT AA,CLASSE, NISCR=count(*), GROUPING(AA) AS AGGREGO_AA, GROUPING(CLASSE) AS AGGREGO_CLASSE
FROM ISCRIZIONI  
GROUP BY AA, CLASSE WITH CUBE

-- GROUPING_ID codifica binaria tra i parametri per identificare parametri
SELECT AA,CLASSE, NISCR=count(*), GROUPING(AA) AS AGGREGO_AA, GROUPING(CLASSE) AS AGGREGO_CLASSE, GROUPING_ID(AA,CLASSE) AS PATTERN
FROM ISCRIZIONI  
GROUP BY AA, CLASSE WITH CUBE
ORDER BY PATTERN

-- Diamo un valore a NULL/ALL utilizzando CASE WHEN
SELECT 
AA=CASE WHEN GROUPING(AA)=1 THEN 'TuttiGliAnni'
		 ELSE AA END,		  
CLASSE=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiLeClassi'
		 ELSE CLASSE END,		  
  NISCR=count(*),
  GROUPING(AA) AS AGGREGO_AA, 
  GROUPING(CLASSE) AS AGGREGO_CLASSE,
  GROUPING_ID(AA,CLASSE) AS PATTERN
FROM ISCRIZIONI  
GROUP BY AA, CLASSE WITH CUBE
ORDER BY PATTERN

SELECT 
AA=CASE WHEN GROUPING(AA)=1 THEN 'TuttiGliAnni'
		 ELSE AA END,		  
CLASSE=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiLeClassi'
		 ELSE CLASSE END,		  
  NISCR=count(*),
  GROUPING(AA) AS AGGREGO_AA, 
  GROUPING(CLASSE) AS AGGREGO_CLASSE
FROM ISCRIZIONI  
GROUP BY AA, CLASSE WITH CUBE

SELECT 
AA=CASE WHEN GROUPING(AA)=1 THEN 'TuttiGliAnni'
		 ELSE AA END,		  
CLASSE=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiLeClassi'
		 ELSE CLASSE END,
TIPO=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiITipi'
		 ELSE TIPO END,
  NISCR=count(*),
  GROUPING(AA) AS AGGREGO_AA, 
  GROUPING(CLASSE) AS AGGREGO_CLASSE,
  GROUPING_ID(AA,CLASSE,TIPO) AS PATTERN
FROM ISCRIZIONI  
GROUP BY AA, CLASSE,TIPO WITH CUBE
ORDER BY PATTERN


SELECT 
    CASE 
        WHEN GROUPING(AA) = 1 THEN 'TuttiGliAnni' 
        ELSE AA 
    END AS AA,  
    CASE 
        WHEN GROUPING(CLASSE) = 1 THEN 'TutteLeClassi' 
        ELSE CLASSE 
    END AS CLASSE,  
    COUNT(*) AS NISCR,
    GROUPING(AA) AS AGGREGO_AA, 
    GROUPING(CLASSE) AS AGGREGO_CLASSE,
    GROUPING_ID(AA, CLASSE) AS PATTERN,
    CASE GROUPING_ID(AA, CLASSE)
        WHEN 0 THEN 'NESSUNO - pattern AA, CLASSE'
        WHEN 1 THEN 'CLASSE - pattern AA'
        WHEN 2 THEN 'AA - pattern CLASSE'
        WHEN 3 THEN 'AA, CLASSE - pattern vuoto'
    END AS ATTRIBUTI_AGGREGAZIONE
FROM ISCRIZIONI  
GROUP BY CUBE(AA, CLASSE)
ORDER BY PATTERN DESC;

-- Il pattern CLASSE, TIPO non è valido per via della FD: CLASSE -> TIPO
SELECT		  
CLASSE=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiLeClassi'
		 ELSE CLASSE END,
TIPO=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiITipi'
		 ELSE TIPO END,
  NISCR=count(*),
  GROUPING(CLASSE) AS AGGREGO_CLASSE,
  GROUPING_ID(CLASSE,TIPO) AS PATTERN
FROM ISCRIZIONI  
GROUP BY CLASSE,TIPO WITH CUBE

-- Per pattern di questo tipo dobbiamo utilizzare il ROLLUP

-- SQL-OLAP: Operatore ROLLUP
SELECT AA,CLASSE, NISCR=count(*)  
FROM ISCRIZIONI  
GROUP BY AA, CLASSE WITH ROLLUP

-- L'ordine è rilevante (seguire il verso opposto della gerarchia)
-- Realizzazione del pattern {A1, A2, …, Ak} e dei seguenti k sottoinsiemi    {A1, A2, …, Ak-1 } , {A1, A2, …, Ak-2 }  …     {A1}     {}

SELECT		  
CLASSE=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiLeClassi'
		 ELSE CLASSE END,
TIPO=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiITipi'
		 ELSE TIPO END,
  NISCR=count(*),
  GROUPING(CLASSE) AS AGGREGO_CLASSE,
  GROUPING_ID(CLASSE,TIPO) AS PATTERN
FROM ISCRIZIONI  
GROUP BY TIPO,CLASSE WITH ROLLUP

-- ROLLUP(TIPO,CLASSE):  TIPO,CLASSE; TIPO; {} 
-- Visualizza {CLASSE} ma anche gli attributi determinati {TIPO}


-- Consideriamo CDL, CLASSE con CDL --> CLASSE
-- I pattern "teorici" significativi sono {CLD}, {CLASSE} e {}

SELECT 
CLASSE=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiLeClassi'
		 ELSE CLASSE END,		  
CDL=CASE WHEN GROUPING(CDL)=1 THEN 'TuttiiCDL'
		 ELSE CDL END,		  
  NISCR=count(*),
  GROUPING(CDL), 
  GROUPING(CLASSE) ,
  GROUPING_ID(CDL,CLASSE) AS PATTERN
FROM ISCRIZIONI  
GROUP BY CLASSE,CDL  WITH CUBE
ORDER BY PATTERN,CDL

-- IL PATTERN 0 E 1 RESTITUISCONO LO STESSO RISULTATO

SELECT 
CLASSE=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiLeClassi'
		 ELSE CLASSE END,		  
CDL=CASE WHEN GROUPING(CDL)=1 THEN 'TuttiiCDL'
		 ELSE CDL END,		  
  NISCR=count(*),
  GROUPING(CDL), 
  GROUPING(CLASSE) ,
  GROUPING_ID(CDL,CLASSE) AS PATTERN
FROM ISCRIZIONI  
GROUP BY CLASSE,CDL  WITH ROLLUP
ORDER BY PATTERN,CDL


-- Nel caso generico è poco significativo

SELECT 
AA=CASE WHEN GROUPING(AA)=1 THEN 'TuttiGliAnni'
		 ELSE AA END,		  
CLASSE=CASE WHEN GROUPING(CLASSE)=1 THEN 'TuttiLeClassi'
		 ELSE CLASSE END,		  
  NISCR=count(*),
  GROUPING(AA) AS AGGREGO_AA, 
  GROUPING(CLASSE) AS AGGREGO_CLASSE,
  GROUPING_ID(AA,CLASSE) AS PATTERN
FROM ISCRIZIONI  
GROUP BY AA, CLASSE WITH ROLLUP
ORDER BY PATTERN

-- Consideriamo ora tutta la gerarchia CDL --> CLASSE --> TIPO
-- Devo fare GROUP BY TIPO,CLASSE,CDL WITH ROLLUP

SELECT 
  TIPO,CLASSE,CDL,
  NISCR=count(*)
	,   GROUPING_ID(TIPO,CLASSE,CDL) AS PATTERN
  FROM ISCRIZIONI  
GROUP BY TIPO,CLASSE,CDL WITH ROLLUP

-- Non è corretto scrivere GROUP BY CDL,CLASSE,TIPO WITH ROLLUP

SELECT 
  TIPO,CLASSE,CDL,
  NISCR=count(*)
	,   GROUPING_ID(TIPO,CLASSE,CDL) AS PATTERN
  FROM ISCRIZIONI  
GROUP BY CDL,CLASSE,TIPO WITH ROLLUP



-- Memorizzo il tutto in una vista per futuri utilizzi

CREATE VIEW PATTERN_TIPO_CLASSE_CDL AS
SELECT 
  TIPO,CLASSE,CDL,
  NISCR=count(*)
	,   GROUPING_ID(TIPO,CLASSE,CDL) AS PATTERN
FROM ISCRIZIONI  
GROUP BY TIPO,CLASSE,CDL WITH ROLLUP

SELECT * 
FROM PATTERN_TIPO_CLASSE_CDL

-- Proviamo anche GROUPING SETS, nel quale dobbiamo esplicitare tutti i pattern validi
-- Non è possibile creare combinazioni di CUBE e ROLLUP
-- Non genera i pattern superflui
SELECT AA, CDL, TIPO, NISCR = COUNT(*)
FROM ISCRIZIONI 
GROUP BY
    GROUPING SETS (
        (AA, CDL),
        (AA, TIPO),
        (AA),
        (CDL),
        (TIPO),
        ()
    );

SELECT 
  AA, CDL, TIPO,
  NISCR=count(*)
	,   GROUPING_ID(AA,CDL,TIPO) AS PATTERN
  FROM ISCRIZIONI  
GROUP BY AA,CDL,TIPO WITH CUBE
HAVING NOT (GROUPING(CDL) = 0 AND GROUPING(TIPO) = 0)














