
--PATTERN

-- Un pattern particolare che si potrebbe analizzare è quello che considera tutte le città presenti nello schema di fatto
SELECT SOCIETA_DITTA_CITTA, IMMOBILE_CITTA, SOCIETA_IMMOBILE_CITTA, PROPRIETARIO_CITTA, NUMERO_RIPARAZIONI= COUNT(*), IMPORTOMEDIO = AVG(IMPORTO)
FROM STARSCHEMA
GROUP BY SOCIETA_DITTA_CITTA, IMMOBILE_CITTA, SOCIETA_IMMOBILE_CITTA, PROPRIETARIO_CITTA 


-- WINDOW FUNCTION

CREATE VIEW DATA_PROPRIETARIO AS
SELECT DATA, PROPRIETARIO, N_RIPARA = COUNT(*), IMPORTO = AVG(IMPORTO)
FROM STARSCHEMA
GROUP BY DATA, PROPRIETARIO

SELECT N_RIPARA = SUM(N_RIPARA), IMPORTO = AVG(IMPORTO)
FROM DATA_PROPRIETARIO

-- IMPORTO SBAGLIATO

ALTER VIEW DATA_PROPRIETARIO AS
SELECT	DATA, PROPRIETARIO,
		N_RIPARA = COUNT(*), IMPORTO_SUM = SUM(IMPORTO), IMPORTO_COUNT = COUNT(IMPORTO)
FROM STARSCHEMA
GROUP BY DATA, PROPRIETARIO

SELECT N_RIPARA = SUM(N_RIPARA), IMPORTO = SUM(IMPORTO_SUM) / SUM(IMPORTO_COUNT)
FROM DATA_PROPRIETARIO


SELECT	DATA, PROPRIETARIO, N_RIPARA,
		SUM(N_RIPARA) OVER (PARTITION BY PROPRIETARIO) AS TOTALE_RIPARAZIONI_PER_PROPRIETARIO,
		SUM(N_RIPARA) OVER (PARTITION BY PROPRIETARIO ORDER BY DATA, PROPRIETARIO) AS PROPRIETARIO_TO_DATE,
		SUM(N_RIPARA) OVER (ORDER BY PROPRIETARIO, DATA ) AS CUMULATIVE
FROM DATA_PROPRIETARIO


SELECT	PROPRIETARIO, DATA, IMPORTO = IMPORTO_SUM / IMPORTO_COUNT,
		SUM(IMPORTO_SUM) OVER ( PARTITION BY PROPRIETARIO ORDER BY DATA ROWS 2 PRECEDING ) / SUM(IMPORTO_COUNT) OVER ( PARTITION BY PROPRIETARIO ORDER BY DATA ROWS 2 PRECEDING ) AS MediaMobile,
		SUM(IMPORTO_SUM) OVER ( PARTITION BY PROPRIETARIO ORDER BY DATA ROWS UNBOUNDED PRECEDING) / SUM(IMPORTO_COUNT) OVER ( PARTITION BY PROPRIETARIO ORDER BY DATA ROWS UNBOUNDED PRECEDING) AS MediaMobile2,
		SUM(IMPORTO_SUM) OVER ( PARTITION BY PROPRIETARIO) / SUM(IMPORTO_COUNT) OVER ( PARTITION BY PROPRIETARIO) AS MediaMobile3
FROM DATA_PROPRIETARIO;