
-- STAR SCHEMA

-- DIMENSION TABLE APPARTAMENTO
ALTER VIEW S_DT_APPARTAMENTO AS
SELECT 
    APPARTAMENTO.APPARTAMENTO AS APPARTAMENTO,
    IMMOBILE.IMMOBILE AS IMMOBILE,
    IMMOBILE_CITTA.CITTA AS IMMOBILE_CITTA,
    IMMOBILE_CITTA.REGIONE AS IMMOBILE_CITTA_REGIONE,
    SOCIETA.SOCIETA AS SOCIETA_IMMOBILE,
    SOCIETA_CITTA.CITTA AS SOCIETA_IMMOBILE_CITTA,
    SOCIETA_CITTA.REGIONE AS SOCIETA_IMMOBILE_CITTA_REGIONE,
    PROPRIETARIO.PROPRIETARIO AS PROPRIETARIO,
    PROPRIETARIO.FASCIA_REDDITO AS PROPRIETARIO_FASCIA_REDDITO,
    PROPRIETARIO.ALIQUOTA_IRPEF AS PROPRIETARIO_ALIQUOTA_IRPEF,
    PROPRIETARIO_CITTA.CITTA AS PROPRIETARIO_CITTA,
    PROPRIETARIO_CITTA.REGIONE AS PROPRIETARIO_CITTA_REGIONE




FROM 
    dbo.APPARTAMENTO
INNER JOIN dbo.IMMOBILE 
    ON APPARTAMENTO.IMMOBILE = IMMOBILE.IMMOBILE
INNER JOIN dbo.PROPRIETARIO 
    ON APPARTAMENTO.PROPRIETARIO = PROPRIETARIO.PROPRIETARIO
INNER JOIN dbo.SOCIETA 
    ON IMMOBILE.SOCIETA = SOCIETA.SOCIETA
INNER JOIN dbo.CITTA AS SOCIETA_CITTA 
    ON SOCIETA.CITTA = SOCIETA_CITTA.CITTA
INNER JOIN dbo.CITTA AS IMMOBILE_CITTA 
    ON IMMOBILE.CITTA = IMMOBILE_CITTA.CITTA
INNER JOIN dbo.CITTA AS PROPRIETARIO_CITTA 
    ON PROPRIETARIO.CITTA = PROPRIETARIO_CITTA.CITTA;

SELECT COUNT(*) FROM S_DT_APPARTAMENTO
SELECT COUNT(*) FROM APPARTAMENTO

-- DIMENSION TABLE DITTA
ALTER VIEW S_DT_DITTA AS
SELECT 
    DITTA.DITTA AS DITTA,
    SOCIETA.SOCIETA AS SOCIETA_DITTA,
    SOCIETA_DITTA_CITTA.CITTA AS SOCIETA_DITTA_CITTA,
    SOCIETA_DITTA_CITTA.REGIONE AS SOCIETA_DITTA_CITTA_REGIONE
FROM 
    dbo.CITTA AS SOCIETA_DITTA_CITTA
INNER JOIN dbo.SOCIETA 
    ON SOCIETA_DITTA_CITTA.CITTA = SOCIETA.CITTA
INNER JOIN dbo.DITTA 
    ON SOCIETA.SOCIETA = DITTA.SOCIETA
UNION 
SELECT 9999,9999,'NO','NO'


SELECT COUNT(*) FROM S_DT_DITTA
SELECT COUNT(*) FROM DITTA

-- FACT TABLE RIPARAZIONE
-- NO VISTA APPOGGIO PERCHè SCHEMA TRANSAZIONALE
-- NO MISURE PERCHè DERIVATE
ALTER VIEW FACT_TABLE AS
SELECT dbo.RIPARAZIONE.DATA, dbo.RIPARAZIONE.[%DETRAIBILE], dbo.RIPARAZIONE.IMPORTO, dbo.RIPARAZIONE.APPARTAMENTO, COALESCE(dbo.CON_DITTA.DITTA, 9999) AS DITTA
FROM     dbo.CON_DITTA RIGHT JOIN
                  dbo.RIPARAZIONE ON dbo.CON_DITTA.DATA = dbo.RIPARAZIONE.DATA AND dbo.CON_DITTA.APPARTAMENTO = dbo.RIPARAZIONE.APPARTAMENTO

SELECT COUNT(*) FROM FACT_TABLE
SELECT COUNT(*) FROM RIPARAZIONE


ALTER VIEW STARSCHEMA AS
SELECT dbo.FACT_TABLE.DATA, dbo.FACT_TABLE.[%DETRAIBILE],IMPORTO, dbo.S_DT_APPARTAMENTO.*, dbo.S_DT_DITTA.*
FROM     dbo.FACT_TABLE INNER JOIN
                  dbo.S_DT_APPARTAMENTO ON dbo.FACT_TABLE.APPARTAMENTO = dbo.S_DT_APPARTAMENTO.APPARTAMENTO INNER JOIN
                  dbo.S_DT_DITTA ON dbo.FACT_TABLE.DITTA = dbo.S_DT_DITTA.DITTA


-- SNOWFLAKE SCHEMA

-- DIMENSION TABLE DITTA
CREATE VIEW SF_DT_DITTA AS 
SELECT DITTA.*
FROM DITTA
UNION 
SELECT 9999,9999

-- DIMENSION TABLE SOCIETA
CREATE VIEW SF_DT_SOCIETA AS
SELECT *
FROM SOCIETA


-- DIMENSION TABLE CITTA
CREATE VIEW SF_DT_CITTA AS
SELECT *
FROM CITTA


-- DIMENSION TABLE APPARTAMENTO
CREATE VIEW SF_DT_APPARTAMENTO AS
SELECT *
FROM APPARTAMENTO


-- DIMENSION TABLE IMMOBILE
CREATE VIEW SF_DT_IMMOBILE AS
SELECT *
FROM IMMOBILE


-- DIMENSION TABLE PROPRIETARIO
CREATE VIEW SF_DT_PROPRIETARIO AS
SELECT PROPRIETARIO, CITTA, FASCIA_REDDITO
FROM PROPRIETARIO

-- DIMENSION TABLE FASCIA_REDDITO
CREATE VIEW SF_DT_FASCIAREDDITO AS
SELECT DISTINCT FASCIA_REDDITO, ALIQUOTA_IRPEF
FROM PROPRIETARIO


CREATE SCHEMA SNOWFLAKE

SELECT * INTO SNOWFLAKE.DT_SOCIETA FROM SF_DT_SOCIETA
SELECT * INTO SNOWFLAKE.DT_CITTA FROM SF_DT_CITTA
SELECT * INTO SNOWFLAKE.DT_APPARTAMENTO FROM SF_DT_APPARTAMENTO
SELECT * INTO SNOWFLAKE.DT_IMMOBILE FROM SF_DT_IMMOBILE
SELECT * INTO SNOWFLAKE.FACT_TABLE FROM FACT_TABLE
SELECT * INTO SNOWFLAKE.DT_DITTA FROM SF_DT_DITTA
SELECT * INTO SNOWFLAKE.DT_PROPRIETARIO FROM SF_DT_PROPRIETARIO
SELECT * INTO SNOWFLAKE.DT_FASCIA_REDDITO FROM SF_DT_FASCIAREDDITO


SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'STARSCHEMA';