
-- DIMENSION TABLE PARTENZA
CREATE VIEW DT_PARTENZA AS
SELECT PARTENZA.CITTA AS PARTENZA_CITTA, PARTENZA.DISTRETTO AS PARTENZA_DISTRETTO, dbo.REGIONE.REGIONE AS PARTENZA_REGIONE, dbo.REGIONE.STATO AS PARTENZA_REGIONE_STATO
FROM     dbo.CITTA AS PARTENZA INNER JOIN
                  dbo.REGIONE ON PARTENZA.REGIONE = dbo.REGIONE.REGIONE

SELECT COUNT(*) FROM DT_PARTENZA
SELECT COUNT(*) FROM CITTA


-- DIMENSION TABLE RESIDENZA
CREATE VIEW DT_RESIDENZA AS
SELECT RESIDENZA.CITTA AS RESIDENZA_CITTA, RESIDENZA.DISTRETTO AS RESIDENZA_DISTRETTO, dbo.REGIONE.REGIONE AS RESIDENZA_REGIONE, dbo.REGIONE.STATO AS RESIDENZA_REGIONE_STATO
FROM     dbo.CITTA AS RESIDENZA INNER JOIN
                  dbo.REGIONE ON RESIDENZA.REGIONE = dbo.REGIONE.REGIONE

SELECT COUNT(*) FROM DT_RESIDENZA
SELECT COUNT(*) FROM CITTA

-- VISTA APPOGGIO PER_FT
CREATE VIEW PER_FT AS
SELECT DISTINCT dbo.VIAGGIO.PERSONA, dbo.VIAGGIO.ITINERARIO, dbo.VIAGGIO.ANNO, dbo.ITINERARIO.PARTENZA, dbo.ITINERARIO.AGENZIA, dbo.PERSONA.RESIDENZA, dbo.REGIONE.STATO AS DESTINAZIONE_STATO
FROM     dbo.CITTA INNER JOIN
                  dbo.ITINERARIO ON dbo.CITTA.CITTA = dbo.ITINERARIO.DESTINAZIONE INNER JOIN
                  dbo.REGIONE ON dbo.CITTA.REGIONE = dbo.REGIONE.REGIONE INNER JOIN
                  dbo.VIAGGIO ON dbo.ITINERARIO.ITINERARIO = dbo.VIAGGIO.ITINERARIO INNER JOIN
                  dbo.PERSONA ON dbo.VIAGGIO.PERSONA = dbo.PERSONA.PERSONA

SELECT COUNT(*) FROM PER_FT
SELECT COUNT(*) FROM VIAGGIO


-- FACT TABLE VIAGGIO

CREATE VIEW FACT_TABLE AS 
SELECT	RESIDENZA, PARTENZA, DESTINAZIONE_STATO, ANNO, AGENZIA,
		NumVIAGGI = COUNT(*), NumITINERARI = COUNT(DISTINCT ITINERARIO),
		NumPERSONE = COUNT(DISTINCT PERSONA)
FROM PER_FT
GROUP BY RESIDENZA, PARTENZA, DESTINAZIONE_STATO, ANNO, AGENZIA


-- ARCO MULTIPLO
-- AGENZIA HA CON + SEDI
SELECT DISTINCT AGENZIA, 'X' AS SEDE, 1.0 AS PESO INTO PESO FROM ITINERARIO
UPDATE PESO SET PESO=0.5 WHERE AGENZIA = 'AGAT'
INSERT PESO SELECT 'AGAT','Y',0.5
SELECT * FROM PESO

-- FACT TABLE CON PUSHDOWN
CREATE VIEW FT_PUSHDOWN AS
SELECT	RESIDENZA, PARTENZA, DESTINAZIONE_STATO, ANNO, FACT_TABLE.AGENZIA,
-- ARCO MULTIPLO
PESO.SEDE,
-- MISURE 
--- IMPATTO (DUE VERSIONI)
		NumVIAGGI, -- NON PESATA
		NumVIAGGI_PES = NumVIAGGI * PESO.PESO, -- PESATA
--- PESATA 
		NumITINERARI_PES = NumITINERARI * PESO,
		NumPERSONE_PES = NumPERSONE * PESO
FROM FACT_TABLE JOIN PESO ON FACT_TABLE.AGENZIA = PESO.AGENZIA

-- NELLE INTERROGAZIONI USERO SEMPRE FT_PUSHDOWN

--STAR SCHEMA
CREATE VIEW STARSCHEMA AS
SELECT dbo.DT_RESIDENZA.RESIDENZA_DISTRETTO, dbo.DT_RESIDENZA.RESIDENZA_REGIONE, dbo.DT_RESIDENZA.RESIDENZA_REGIONE_STATO, dbo.DT_PARTENZA.PARTENZA_DISTRETTO, dbo.DT_PARTENZA.PARTENZA_REGIONE, 
                  dbo.DT_PARTENZA.PARTENZA_REGIONE_STATO, dbo.FT_PUSHDOWN.RESIDENZA, dbo.FT_PUSHDOWN.PARTENZA, dbo.FT_PUSHDOWN.DESTINAZIONE_STATO, dbo.FT_PUSHDOWN.ANNO, dbo.FT_PUSHDOWN.AGENZIA, 
                  dbo.FT_PUSHDOWN.SEDE, dbo.FT_PUSHDOWN.NumVIAGGI_PES, dbo.FT_PUSHDOWN.NumVIAGGI, dbo.FT_PUSHDOWN.NumITINERARI_PES, dbo.FT_PUSHDOWN.NumPERSONE_PES
FROM     dbo.FT_PUSHDOWN INNER JOIN
                  dbo.DT_RESIDENZA ON dbo.FT_PUSHDOWN.RESIDENZA = dbo.DT_RESIDENZA.RESIDENZA_CITTA INNER JOIN
                  dbo.DT_PARTENZA ON dbo.FT_PUSHDOWN.PARTENZA = dbo.DT_PARTENZA.PARTENZA_CITTA


SELECT * FROM STARSCHEMA



-- SNOWFLAKE SCHEMA

-- DIMENSION TABLE CITTA
CREATE VIEW SF_DT_CITTA AS
SELECT * FROM CITTA

-- DIMENSION TABLE REGIONE
CREATE VIEW SF_DT_REGIONE AS
SELECT * FROM REGIONE

-- SNOWFLAKE (DA SISTEMARE I NOMI)
CREATE VIEW SNOWFLAKE AS
SELECT dbo.FT_PUSHDOWN.ANNO, CITTA_PARTENZA.*, REGIONE_PARTENZA.STATO, CITTA_RESIDENZA.*, REGIONE_RESIDENZA.STATO AS Expr1, dbo.FT_PUSHDOWN.AGENZIA, dbo.FT_PUSHDOWN.DESTINAZIONE_STATO, 
                  dbo.FT_PUSHDOWN.SEDE, dbo.FT_PUSHDOWN.NumVIAGGI, dbo.FT_PUSHDOWN.NumVIAGGI_PES, dbo.FT_PUSHDOWN.NumITINERARI_PES, dbo.FT_PUSHDOWN.NumPERSONE_PES
FROM     dbo.SF_DT_REGIONE AS REGIONE_RESIDENZA INNER JOIN
                  dbo.SF_DT_CITTA AS CITTA_RESIDENZA ON REGIONE_RESIDENZA.REGIONE = CITTA_RESIDENZA.REGIONE INNER JOIN
                  dbo.FT_PUSHDOWN INNER JOIN
                  dbo.SF_DT_CITTA AS CITTA_PARTENZA ON dbo.FT_PUSHDOWN.PARTENZA = CITTA_PARTENZA.CITTA INNER JOIN
                  dbo.SF_DT_REGIONE AS REGIONE_PARTENZA ON CITTA_PARTENZA.REGIONE = REGIONE_PARTENZA.REGIONE ON CITTA_RESIDENZA.CITTA = dbo.FT_PUSHDOWN.RESIDENZA
