
-- SQL-OLAP 
-- NA
-- MISURE DI IMPATTO
-- MISURE PESATE



-- NumITINERARI  NA = {RESIDENZA,ANNO}
-- NumViaggi DI IMPATTO
CREATE VIEW SQL_OLAP AS
SELECT	RESIDENZA, ANNO, SEDE,
		NumITINERARI = CASE 
							WHEN GROUPING(RESIDENZA) = 0 AND GROUPING(ANNO) = 0 THEN SUM(NumITINERARI_PES)
							ELSE -SUM(NumITINERARI_PES)
						END, 
		NumVIAGGI = CASE
						-- SE SEDE VERSIONE NON PESATA
						WHEN GROUPING(SEDE) = 0 THEN SUM(NumVIAGGI)
						ELSE SUM(NumVIAGGI_PES)
					END
FROM STARSCHEMA
GROUP BY RESIDENZA, ANNO, SEDE WITH CUBE


-- PATTERN VUOTO
SELECT * FROM SQL_OLAP
WHERE RESIDENZA IS NULL AND ANNO IS NULL AND SEDE IS NULL
-- NumVIAGGI GIUSTO MENTRE NumITINERARI NO PERCHE NON AGGREGABILE SU QUESTE DIMENSIONI


SELECT * FROM SQL_OLAP
WHERE RESIDENZA IS NOT NULL AND ANNO IS NULL AND SEDE IS NULL
ORDER BY 4 DESC

-- CONTROLLO 
SELECT RESIDENZA, COUNT(DISTINCT ITINERARIO)
FROM PER_FT
GROUP BY RESIDENZA
ORDER BY 2 DESC

-- WINDOW FUNCTION
-- Per ogni cliente, il prodotto con il maggior importo di vendita e la relativa percentuale”
-- Dove per ogni cliente si intendeva anche il cliente “All”;
-- Questa analisi nel contesto in esame possiamo riscriverla
--Per ogni AGENZIA, la città di partenza con il maggior numero di viaggi e la relativa percentuale”
-- vedo attributi/istanze

SELECT * FROM STARSCHEMA
-- si considerano le variabili (attributi dimensionali) in gioco, AGENZIA e PARTENZA_CITTA
-- con anche i totali parziali (WITH CUBE)

CREATE VIEW AGENZIA_PARTENZA AS
SELECT	AGENZIA, PARTENZA, 
		SUM(NumVIAGGI) AS NumVIAGGI
FROM STARSCHEMA
GROUP BY AGENZIA, PARTENZA WITH CUBE;


SELECT * FROM AGENZIA_PARTENZA

-- si effettua il ranking delle città (di partenza) rispetto alle agenzie sulla base di NumVIAGGI

-- è possibile usare ROW_NUMBER() o RANK(); usiamo quest'ultima per considerare anche i parimerito

ALTER VIEW TOP_P AS
SELECT	AGENZIA, PARTENZA, NumVIAGGI,
		RANK() OVER (PARTITION BY AGENZIA ORDER BY NumVIAGGI DESC) AS [RANK],
		( SUM (NumVIAGGI) OVER (PARTITION BY AGENZIA) ) / 2 AS TOTALEAGENZIA,
		100.0 * NumVIAGGI / (max (NumVIAGGI) OVER (PARTITION BY AGENZIA)) as RAPPORTO
FROM AGENZIA_PARTENZA

SELECT * 
FROM TOP_P 
WHERE RANK <=2


--Per ogni AGENZIA, IL PERCORSO la città di partenza & DESTINAZIONE STATO con il maggior numero di viaggi e la relativa percentuale”

SELECT * FROM STARSCHEMA

CREATE VIEW AGENZIA_PARTENZA_DESTINAZIONE AS
SELECT	AGENZIA, PARTENZA, DESTINAZIONE_STATO, 
		SUM(NumVIAGGI) AS NumVIAGGI
FROM STARSCHEMA
GROUP BY AGENZIA, PARTENZA, DESTINAZIONE_STATO WITH CUBE;


SELECT * FROM AGENZIA_PARTENZA_DESTINAZIONE

CREATE VIEW TOP_P2 AS
SELECT	AGENZIA, PARTENZA, DESTINAZIONE_STATO, NumVIAGGI,
		RANK() OVER (PARTITION BY AGENZIA ORDER BY NumVIAGGI DESC) AS [RANK]
FROM AGENZIA_PARTENZA_DESTINAZIONE

ALTER VIEW TOP_P2B AS
SELECT *,
		RANK() OVER (PARTITION BY AGENZIA ORDER BY RANK) as RANK2
FROM TOP_P2
WHERE (DESTINAZIONE_STATO IS NOT NULL AND PARTENZA IS NOT NULL OR (DESTINAZIONE_STATO IS NULL AND PARTENZA IS NULL AND AGENZIA IS NOT NULL))

SELECT * FROM TOP_P2B WHERE RANK <= 2



