/****** Object:  Table [dbo].[CITTA]    Script Date: 07/04/2025 23:01:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CITTA](
	[CITTA] [varchar](18) NOT NULL,
	[REGIONE] [varchar](18) NULL,
	[DISTRETTO] [varchar](18) NULL,
PRIMARY KEY CLUSTERED 
(
	[CITTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITINERARIO]    Script Date: 07/04/2025 23:01:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITINERARIO](
	[ITINERARIO] [varchar](18) NOT NULL,
	[PARTENZA] [varchar](18) NULL,
	[DESTINAZIONE] [varchar](18) NULL,
	[AGENZIA] [varchar](18) NULL,
	[TIPO] [varchar](18) NULL,
PRIMARY KEY CLUSTERED 
(
	[ITINERARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERSONA]    Script Date: 07/04/2025 23:01:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONA](
	[PERSONA] [varchar](18) NOT NULL,
	[RESIDENZA] [varchar](18) NULL,
PRIMARY KEY CLUSTERED 
(
	[PERSONA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REGIONE]    Script Date: 07/04/2025 23:01:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REGIONE](
	[REGIONE] [varchar](18) NOT NULL,
	[STATO] [varchar](18) NULL,
PRIMARY KEY CLUSTERED 
(
	[REGIONE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VIAGGIO]    Script Date: 07/04/2025 23:01:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VIAGGIO](
	[PERSONA] [varchar](18) NOT NULL,
	[DATA] [date] NOT NULL,
	[ITINERARIO] [varchar](18) NULL,
	[ANNO]  AS (datepart(year,[DATA])),
 CONSTRAINT [PK__VIAGGIO__CB6ADD120CC26EAB] PRIMARY KEY CLUSTERED 
(
	[PERSONA] ASC,
	[DATA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[CITTA] ([CITTA], [REGIONE], [DISTRETTO]) VALUES (N'BO', N'EMILIA', N'A')
GO
INSERT [dbo].[CITTA] ([CITTA], [REGIONE], [DISTRETTO]) VALUES (N'MO', N'EMILIA', N'B')
GO
INSERT [dbo].[CITTA] ([CITTA], [REGIONE], [DISTRETTO]) VALUES (N'PZ', N'LUCANIA', N'C')
GO
INSERT [dbo].[CITTA] ([CITTA], [REGIONE], [DISTRETTO]) VALUES (N'RE', N'EMILIA', N'B')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'?]ke', N'MO', N'BO', N'AGVC', N'VIAGGIO')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'+)x"', N'RE', N'MO', N'AGAT', N'LAVORO')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'-=rp', N'PZ', N'RE', N'AGXB', N'SCUOLA')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'0@mk', N'MO', N'RE', N'AGXB', N'VACANZE')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'Be2p', N'PZ', N'MO', N'AGXB', N'VIAGGIO')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'bQwn', N'MO', N'BO', N'AGXB', N'VIAGGIO')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'bu5\', N'BO', N'MO', N'AGAT', N'VACANZE')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'BY"M', N'MO', N'RE', N'AGVC', N'VIAGGIO')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'c.Ph', N'PZ', N'RE', N'AGXB', N'LAVORO')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'ebIU', N'PZ', N'BO', N'AGAT', N'VIAGGIO')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'f*!x', N'RE', N'MO', N'AGXB', N'SCUOLA')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'hC<R', N'RE', N'PZ', N'AGUB', N'SCUOLA')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'Kz9>', N'MO', N'RE', N'AGXB', N'VACANZE')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'P,up', N'MO', N'RE', N'AGVC', N'VIAGGIO')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'QFv,', N'PZ', N'MO', N'AGUB', N'SCUOLA')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'TkWQ', N'RE', N'BO', N'AGVC', N'LAVORO')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'UE_T', N'RE', N'BO', N'AGUB', N'LAVORO')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'XlcV', N'PZ', N'RE', N'AGVC', N'VACANZE')
GO
INSERT [dbo].[ITINERARIO] ([ITINERARIO], [PARTENZA], [DESTINAZIONE], [AGENZIA], [TIPO]) VALUES (N'yZ>G', N'RE', N'MO', N'AGXB', N'SCUOLA')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Africa Teel', N'BO')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Aleisha Sattler', N'PZ')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Amos Larrinzar', N'RE')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Bronwyn Carranceja', N'RE')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Cathryn Hamlet', N'RE')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Estevan Luengas', N'PZ')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Garry Knoll', N'BO')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Georgia Mori', N'MO')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Gerri Kibler', N'BO')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Jenni Viñuela', N'PZ')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Maresca Iribarren', N'MO')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Monika Witcher', N'RE')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Rudi Dodd', N'RE')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Sammie Sas', N'MO')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Sarai Prego', N'BO')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Shaniqua Nijhuis', N'BO')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Shelley Hipp', N'PZ')
GO
INSERT [dbo].[PERSONA] ([PERSONA], [RESIDENZA]) VALUES (N'Veronique Lara', N'PZ')
GO
INSERT [dbo].[REGIONE] ([REGIONE], [STATO]) VALUES (N'EMILIA', N'ITALIA')
GO
INSERT [dbo].[REGIONE] ([REGIONE], [STATO]) VALUES (N'LUCANIA', N'ITALIA')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Africa Teel', CAST(N'2010-09-30' AS Date), N'hC<R')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Africa Teel', CAST(N'2011-08-04' AS Date), N'0@mk')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Aleisha Sattler', CAST(N'2010-08-02' AS Date), N'bQwn')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Aleisha Sattler', CAST(N'2012-05-05' AS Date), N'c.Ph')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Aleisha Sattler', CAST(N'2013-07-11' AS Date), N'f*!x')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Bronwyn Carranceja', CAST(N'2011-01-30' AS Date), N'XlcV')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Bronwyn Carranceja', CAST(N'2011-05-31' AS Date), N'ebIU')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Cathryn Hamlet', CAST(N'2010-09-23' AS Date), N'f*!x')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Cathryn Hamlet', CAST(N'2013-07-02' AS Date), N'yZ>G')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Estevan Luengas', CAST(N'2012-03-21' AS Date), N'-=rp')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Estevan Luengas', CAST(N'2012-11-17' AS Date), N'c.Ph')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Garry Knoll', CAST(N'2012-04-28' AS Date), N'ebIU')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Garry Knoll', CAST(N'2013-05-30' AS Date), N'bu5\')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Garry Knoll', CAST(N'2014-05-08' AS Date), N'UE_T')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Gerri Kibler', CAST(N'2010-01-02' AS Date), N'UE_T')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Gerri Kibler', CAST(N'2010-02-26' AS Date), N'ebIU')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Jenni Viñuela', CAST(N'2010-09-29' AS Date), N'QFv,')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Jenni Viñuela', CAST(N'2010-11-20' AS Date), N'Be2p')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Maresca Iribarren', CAST(N'2010-09-25' AS Date), N'XlcV')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Maresca Iribarren', CAST(N'2012-04-19' AS Date), N'BY"M')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Monika Witcher', CAST(N'2012-01-21' AS Date), N'QFv,')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Monika Witcher', CAST(N'2012-03-10' AS Date), N'+)x"')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Rudi Dodd', CAST(N'2013-11-25' AS Date), N'+)x"')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Sammie Sas', CAST(N'2012-07-27' AS Date), N'-=rp')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Sarai Prego', CAST(N'2012-05-18' AS Date), N'XlcV')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Sarai Prego', CAST(N'2012-11-10' AS Date), N'QFv,')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Shaniqua Nijhuis', CAST(N'2010-01-06' AS Date), N'yZ>G')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Shaniqua Nijhuis', CAST(N'2010-01-27' AS Date), N'+)x"')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Shaniqua Nijhuis', CAST(N'2011-12-21' AS Date), N'UE_T')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Shaniqua Nijhuis', CAST(N'2012-03-27' AS Date), N'+)x"')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Shaniqua Nijhuis', CAST(N'2013-09-07' AS Date), N'+)x"')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Shelley Hipp', CAST(N'2013-07-24' AS Date), N'hC<R')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Veronique Lara', CAST(N'2011-04-09' AS Date), N'UE_T')
GO
INSERT [dbo].[VIAGGIO] ([PERSONA], [DATA], [ITINERARIO]) VALUES (N'Veronique Lara', CAST(N'2012-04-05' AS Date), N'?]ke')
GO
ALTER TABLE [dbo].[CITTA]  WITH CHECK ADD FOREIGN KEY([REGIONE])
REFERENCES [dbo].[REGIONE] ([REGIONE])
GO
ALTER TABLE [dbo].[ITINERARIO]  WITH CHECK ADD FOREIGN KEY([DESTINAZIONE])
REFERENCES [dbo].[CITTA] ([CITTA])
GO
ALTER TABLE [dbo].[ITINERARIO]  WITH CHECK ADD FOREIGN KEY([PARTENZA])
REFERENCES [dbo].[CITTA] ([CITTA])
GO
ALTER TABLE [dbo].[PERSONA]  WITH CHECK ADD FOREIGN KEY([RESIDENZA])
REFERENCES [dbo].[CITTA] ([CITTA])
GO
ALTER TABLE [dbo].[VIAGGIO]  WITH CHECK ADD  CONSTRAINT [FK__VIAGGIO__ITINERA__2C3393D0] FOREIGN KEY([ITINERARIO])
REFERENCES [dbo].[ITINERARIO] ([ITINERARIO])
GO
ALTER TABLE [dbo].[VIAGGIO] CHECK CONSTRAINT [FK__VIAGGIO__ITINERA__2C3393D0]
GO
ALTER TABLE [dbo].[VIAGGIO]  WITH CHECK ADD  CONSTRAINT [FK__VIAGGIO__PERSONA__2B3F6F97] FOREIGN KEY([PERSONA])
REFERENCES [dbo].[PERSONA] ([PERSONA])
GO
ALTER TABLE [dbo].[VIAGGIO] CHECK CONSTRAINT [FK__VIAGGIO__PERSONA__2B3F6F97]
GO
