
-- DIMENSION TABLE PARTENZA
CREATE VIEW DT_PARTENZA AS
SELECT dbo.AEROPORTO.AEROPORTO AS PARTENZA, dbo.AEROPORTO.CATEGORIA AS AEROPORTO_PARTENZA_CATEGORIA, dbo.CITTÀ.CITTÀ AS PARTENZA_AEROPORTO_CITTA, 
                  dbo.CITTÀ.STATO AS PARTENZA_AEROPORTO_STATO
FROM     dbo.AEROPORTO INNER JOIN
                  dbo.CITTÀ ON dbo.AEROPORTO.CITTÀ = dbo.CITTÀ.CITTÀ

SELECT COUNT(*) FROM AEROPORTO
SELECT COUNT(*) FROM DT_PARTENZA

-- DIMENSION TABLE RESIDENZA
CREATE VIEW DT_RESIDENZA AS
SELECT CITTÀ AS CITTA_RESIDENZA, STATO AS STATO_RESIDENZA
FROM CITTÀ

SELECT COUNT(*) FROM CITTÀ
SELECT COUNT(*) FROM DT_RESIDENZA

-- VISTA APPOGGIO
CREATE VIEW PER_FT AS
SELECT dbo.BOARDING_PASS.PARTENZA, dbo.BOARDING_PASS.DURATA, dbo.PERSONA.RESIDENZA, CITTÀ_1.STATO AS DESTINAZIONE_STATO, dbo.BIGLIETTO.AGENZIA, dbo.BIGLIETTO.PERSONA
FROM     dbo.PERSONA INNER JOIN
                  dbo.CITTÀ ON dbo.PERSONA.RESIDENZA = dbo.CITTÀ.CITTÀ INNER JOIN
                  dbo.BIGLIETTO ON dbo.PERSONA.PERSONA = dbo.BIGLIETTO.PERSONA INNER JOIN
                  dbo.BOARDING_PASS ON dbo.BIGLIETTO.BIGLIETTO = dbo.BOARDING_PASS.BIGLIETTO INNER JOIN
                  dbo.AEROPORTO ON dbo.BOARDING_PASS.DESTINAZIONE = dbo.AEROPORTO.AEROPORTO INNER JOIN
                  dbo.CITTÀ AS CITTÀ_1 ON dbo.AEROPORTO.CITTÀ = CITTÀ_1.CITTÀ

SELECT COUNT(*) FROM BOARDING_PASS
SELECT COUNT(*) FROM PER_FT


-- FACT TABLE
CREATE VIEW FACT_TABLE AS
SELECT	PARTENZA,RESIDENZA, DESTINAZIONE_STATO, AGENZIA,
		NUM_VIAGGIO = COUNT(*), SOMMA_DURATA = SUM(DURATA),
		COUNT_DURATA = COUNT(DURATA), NUM_PERSONE = COUNT(DISTINCT PERSONA)
FROM PER_FT
GROUP BY PARTENZA,RESIDENZA, DESTINAZIONE_STATO, AGENZIA


-- STAR SCHEMA VIRTUALE
CREATE VIEW STARSCHEMA AS
SELECT dbo.DT_RESIDENZA.*, dbo.DT_PARTENZA.*, dbo.FACT_TABLE.AGENZIA, dbo.FACT_TABLE.NUM_VIAGGIO, dbo.FACT_TABLE.SOMMA_DURATA, dbo.FACT_TABLE.COUNT_DURATA, dbo.FACT_TABLE.NUM_PERSONE, 
                  dbo.FACT_TABLE.DESTINAZIONE_STATO
FROM     dbo.FACT_TABLE INNER JOIN
                  dbo.DT_RESIDENZA ON dbo.FACT_TABLE.RESIDENZA = dbo.DT_RESIDENZA.CITTA_RESIDENZA INNER JOIN
                  dbo.DT_PARTENZA ON dbo.FACT_TABLE.PARTENZA = dbo.DT_PARTENZA.PARTENZA
