
-- PATTERN {RESIDENZA,DESTINAZIONE_STATO}

CREATE VIEW PATTERN_RESIDENZA_DESTINAZIONE_STATO AS
SELECT	CITTA_RESIDENZA, DESTINAZIONE_STATO, NUM_VIAGGI = SUM(NUM_VIAGGIO),
		DURATA = SUM(SOMMA_DURATA) / SUM(COUNT_DURATA),
		NUM_PERSONE = SUM(NUM_PERSONE) -- NON CALCOLABILE
FROM STARSCHEMA
GROUP BY CITTA_RESIDENZA, DESTINAZIONE_STATO WITH CUBE

-- NUM_PERSONE NON CALCOLABILE 
-- NEL PATTERN MANCA PARTENZA E AGENZIA
-- CONTROLLO 
SELECT *
FROM PATTERN_RESIDENZA_DESTINAZIONE_STATO
ORDER BY NUM_PERSONE DESC

SELECT	PARTENZA, DESTINAZIONE_STATO, AGENZIA,
		NUM_PERSONE = COUNT(DISTINCT PERSONA)
FROM PER_FT
GROUP BY PARTENZA, DESTINAZIONE_STATO, AGENZIA WITH CUBE
ORDER BY NUM_PERSONE DESC


-- WINDOW FUNCTION 
SELECT	CITTA_RESIDENZA, DESTINAZIONE_STATO, NUM_VIAGGI, DURATA,
		SUM(NUM_VIAGGI) OVER (PARTITION BY DESTINAZIONE_STATO) AS TOTALE_NUM_VIAGGI_PER_DESTINAZIONE,
		(SUM(DURATA) OVER (PARTITION BY DESTINAZIONE_STATO) / COUNT(DURATA) OVER (PARTITION BY DESTINAZIONE_STATO)) AS DURATA_MEDIA_PER_DESTINAZIONE
FROM PATTERN_RESIDENZA_DESTINAZIONE_STATO

WITH STATI_RANKED AS
(
SELECT	CITTA_RESIDENZA, DESTINAZIONE_STATO, NUM_VIAGGI, DURATA,
		RANK() OVER (PARTITION BY DESTINAZIONE_STATO ORDER BY DURATA DESC) AS [RANK]
FROM PATTERN_RESIDENZA_DESTINAZIONE_STATO
)
SELECT * 
FROM STATI_RANKED
WHERE [RANK] = 1