CREATE TABLE VENDITE (
	DATA DATE,
	CLIENTE_CITTA VARCHAR(50),
	CLIENTE_REGIONE VARCHAR(50),
	NEGOZIO VARCHAR(50),
	NEGOZIO_CITTA VARCHAR(50),
	NEGOZIO_REGIONE VARCHAR(50),
	QUANTITA INT,
	CONSTRAINT PK_VENDITA PRIMARY KEY (DATA, CLIENTE_CITTA, NEGOZIO)
);


INSERT INTO VENDITE (DATA, CLIENTE_CITTA, CLIENTE_REGIONE, NEGOZIO, NEGOZIO_CITTA, NEGOZIO_REGIONE, QUANTITA) VALUES
('2019-02-21', 'RE', 'EMILIA', 'MO1', 'MO', 'EMILIA', 100),
('2019-02-20', 'MT', 'LUCANIA', 'MO1', 'MO', 'EMILIA', 200),
('2019-02-21', 'PZ', 'LUCANIA', 'MO2', 'MO', 'EMILIA', 50),
('2019-02-20', 'RE', 'EMILIA', 'PZ1', 'PZ', 'LUCANIA', 70)