
SELECT * FROM VENDITE

-- FACT TABLE, DIMENSIONI = {DATA, CLIENTE_CITTA, NEGOZIO}, MISURE = {SUM(QUANTITA)}
-- SCHEMA TRANSAZIONE -> NO GROUP BY
CREATE VIEW FACT_TABLE AS 
SELECT DATA,CLIENTE_CITTA, NEGOZIO, QUANTITA
FROM VENDITE

-- DIMENSION TABLE CITTA
DROP VIEW IF EXISTS DT_CITTA

CREATE VIEW DT_CITTA AS
SELECT DISTINCT NEGOZIO_CITTA, NEGOZIO_REGIONE
FROM VENDITE
UNION 
SELECT DISTINCT CLIENTE_CITTA, CLIENTE_REGIONE
FROM VENDITE

-- DIMENSION TABLE NEGOZIO
DROP VIEW IF EXISTS DT_NEGOZIO

CREATE VIEW DT_NEGOZIO AS
SELECT DISTINCT NEGOZIO, NEGOZIO_CITTA
FROM VENDITE


-- SNOWFLAKE 

CREATE SCHEMA SNOWFLAKE

SELECT * INTO SNOWFLAKE.FACT_TABLE FROM FACT_TABLE;
SELECT * INTO SNOWFLAKE.DT_CITTA FROM DT_CITTA;
SELECT * INTO SNOWFLAKE.DT_NEGOZIO FROM DT_NEGOZIO;

