

-- DIMENSION TABLE CITTA_RISTORANTE
CREATE VIEW DT_CITTA_RISTORANTE AS
SELECT CITTA AS CITTA_RISTORANTE, REGIONE AS REGIONE_RISTORANTE, STATO AS STATO_RISTORANTE
FROM     dbo.RISTORANTE

SELECT COUNT(*) FROM RISTORANTE
SELECT COUNT(*) FROM DT_CITTA_RISTORANTE

-- DIMENSION TABLE SCUOLACULINARIA_CUOCO
CREATE VIEW DT_SCUOLACULINARIA_CUOCO AS
SELECT *
FROM SCUOLACULINARIA

SELECT COUNT(*) FROM SCUOLACULINARIA
SELECT COUNT(*) FROM DT_SCUOLACULINARIA_CUOCO

-- DIMENSION TABLE PASTICCIERE
CREATE VIEW DT_PASTICCIERE AS
SELECT dbo.CHEF.ETA AS PASTICCIERE_ETA, dbo.CHEF.DIPLOMA AS PASTICCIERE_DIPLOMA, dbo.CHEF.CHEF AS PASTICCIERE, dbo.SCUOLACULINARIA.SCUOLACULINARIA AS PASTICCIERE_SCUOLACULINARIA, 
                  dbo.SCUOLACULINARIA.TIPO AS PASTICCIERE_SCUOLACULINARIA_TIPO
FROM     dbo.CHEF INNER JOIN
                  dbo.SCUOLACULINARIA ON dbo.CHEF.SCUOLACULINARIA = dbo.SCUOLACULINARIA.SCUOLACULINARIA
UNION 
SELECT 9999,'NO_PASTICCIERE','NO_PASTICCIERE','NO_PASTICCIERE','NO_PASTICCIERE'

SELECT COUNT(*) FROM CHEF
SELECT COUNT(*) FROM DT_PASTICCIERE

-- VISTA APPOGGIO
CREATE VIEW PER_FT AS
SELECT COALESCE(dbo.PRANZO_NATALE.PASTICCIERE,'NO_PASTICCIERE') AS PASTICCIERE, dbo.PRANZO.SETTIMANA, dbo.RISTORANTE.CITTA AS CITTA_RISTORANTE, dbo.CHEF.SCUOLACULINARIA AS SCUOLACULINARIA_CUOCO, dbo.PRANZO.PREZZO, dbo.PRANZO.RISTORANTE, 
                  dbo.PRANZO.CUOCO
FROM     dbo.PRANZO INNER JOIN
                  dbo.RISTORANTE ON dbo.PRANZO.RISTORANTE = dbo.RISTORANTE.RISTORANTE INNER JOIN
                  dbo.CHEF ON dbo.PRANZO.CUOCO = dbo.CHEF.CHEF LEFT OUTER JOIN
                  dbo.PRANZO_NATALE ON dbo.PRANZO.CP = dbo.PRANZO_NATALE.CP

SELECT COUNT(*) FROM PER_FT
SELECT COUNT(*) FROM PRANZO

-- FACT TABLE
CREATE VIEW FACT_TABLE AS 
SELECT	CITTA_RISTORANTE,SCUOLACULINARIA_CUOCO,SETTIMANA,PASTICCIERE,
		SOMMA_PREZZO = SUM(PREZZO), COUNT_PREZZO = COUNT(PREZZO),
		NUM_RISTORANTI = COUNT(DISTINCT RISTORANTE),
		NUM_CUOCO = COUNT(DISTINCT CUOCO)
FROM PER_FT
GROUP BY CITTA_RISTORANTE,SCUOLACULINARIA_CUOCO,SETTIMANA,PASTICCIERE


-- STAR SCHEMA VIRTUALE

