

-- PATTERN  {SETTIMANA, CITTA_RISTORANTE, PASTICCIERE}

-- TUTTE LE MISURE CALCOLABILI
CREATE VIEW PATTERN_SETTIMANA_CITTARISTORANTE_PASTICCIERE AS
SELECT	SETTIMANA, CITTA_RISTORANTE, PASTICCIERE,
		PREZZO_MEDIO = SUM(SOMMA_PREZZO) / SUM(COUNT_PREZZO),
		NUM_RISTORANTI = CASE WHEN GROUPING(SETTIMANA) = 0 THEN SUM(NUM_RISTORANTI) ELSE -SUM(NUM_RISTORANTI) END,
		NUM_CUOCO = CASE WHEN GROUPING(SETTIMANA) = 0 OR GROUPING(CITTA_RISTORANTE) = 0 OR GROUPING(PASTICCIERE) = 0 THEN SUM(NUM_CUOCO) ELSE -SUM(NUM_CUOCO) END
FROM STARSCHEMA
GROUP BY SETTIMANA, CITTA_RISTORANTE, PASTICCIERE WITH CUBE

--CONTROLLO 
SELECT SETTIMANA, CITTA_RISTORANTE, PASTICCIERE, NUM_RISTORANTI
FROM PATTERN_SETTIMANA_CITTARISTORANTE_PASTICCIERE
WHERE CITTA_RISTORANTE IS NOT NULL AND PASTICCIERE IS NOT NULL AND SETTIMANA IS NOT NULL
ORDER BY SETTIMANA ASC

SELECT	SETTIMANA, CITTA_RISTORANTE, PASTICCIERE,
		NUM_RISTORANTI = COUNT(DISTINCT RISTORANTE)
FROM PER_FT
GROUP BY SETTIMANA, CITTA_RISTORANTE, PASTICCIERE
ORDER BY SETTIMANA ASC


--CONTROLLO 
SELECT SETTIMANA, CITTA_RISTORANTE, PASTICCIERE, NUM_CUOCO
FROM PATTERN_SETTIMANA_CITTARISTORANTE_PASTICCIERE
WHERE CITTA_RISTORANTE IS NOT NULL AND PASTICCIERE IS NOT NULL AND SETTIMANA IS NOT NULL
ORDER BY SETTIMANA ASC

SELECT	SETTIMANA, CITTA_RISTORANTE, PASTICCIERE,
		NUM_CUOCO = COUNT(DISTINCT CUOCO)
FROM PER_FT
GROUP BY SETTIMANA, CITTA_RISTORANTE, PASTICCIERE
ORDER BY SETTIMANA ASC


-- WINDOW FUNCTION
SELECT	*, 
		SUM(NUM_RISTORANTI) OVER (PARTITION BY CITTA_RISTORANTE) AS TOT_RISTORANTE_PER_CITTA,
		ROUND(SUM(PREZZO_MEDIO) OVER (PARTITION BY CITTA_RISTORANTE) / COUNT(PREZZO_MEDIO) OVER (PARTITION BY CITTA_RISTORANTE),2) AS PREZZO_MEDIO_PER_CITTA,
FROM PATTERN_SETTIMANA_CITTARISTORANTE_PASTICCIERE
WHERE CITTA_RISTORANTE IS NOT NULL AND PASTICCIERE IS NOT NULL AND SETTIMANA IS NOT NULL

SELECT	*,
		RANK() OVER (PARTITION BY CITTA_RISTORANTE ORDER BY PREZZO_MEDIO) AS [RANK]
FROM PATTERN_SETTIMANA_CITTARISTORANTE_PASTICCIERE
WHERE CITTA_RISTORANTE IS NOT NULL AND PASTICCIERE IS NOT NULL AND SETTIMANA IS NOT NULL