/****** Object:  Table [dbo].[AZIENDA]    Script Date: 18/12/2023 13:16:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AZIENDA](
	[AZIENDA] [varchar](22) NOT NULL,
	[CITTA] [varchar](22) NULL,
 CONSTRAINT [PK_CORSO] PRIMARY KEY CLUSTERED 
(
	[AZIENDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CITTA]    Script Date: 18/12/2023 13:16:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CITTA](
	[CITTA] [varchar](22) NOT NULL,
	[REGIONE] [varchar](22) NULL,
 CONSTRAINT [PK_DIPARTIMENTO] PRIMARY KEY CLUSTERED 
(
	[CITTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIPARTIMENTO]    Script Date: 18/12/2023 13:16:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIPARTIMENTO](
	[DIPARTIMENTO] [varchar](22) NOT NULL,
	[CITTA] [varchar](22) NULL,
	[DIRETTORE] [varchar](22) NULL,
 CONSTRAINT [PK_CDL] PRIMARY KEY CLUSTERED 
(
	[DIPARTIMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIRETTORE]    Script Date: 18/12/2023 13:16:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIRETTORE](
	[DIRETTORE] [varchar](22) NOT NULL,
	[REGIONE] [varchar](22) NULL,
 CONSTRAINT [PK_FACOLTA] PRIMARY KEY CLUSTERED 
(
	[DIRETTORE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MACCHINA_PULITRICE]    Script Date: 18/12/2023 13:16:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MACCHINA_PULITRICE](
	[DATA] [smalldatetime] NOT NULL,
	[UFFICIO] [varchar](22) NOT NULL,
	[AZIENDA] [varchar](22) NULL,
 CONSTRAINT [PK_MACCHINA_PULITRICE] PRIMARY KEY CLUSTERED 
(
	[DATA] ASC,
	[UFFICIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERSONALE]    Script Date: 18/12/2023 13:16:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONALE](
	[PERSONALE] [varchar](22) NOT NULL,
	[AZIENDA] [varchar](22) NULL,
	[GENERE] [varchar](22) NULL,
 CONSTRAINT [PK_APPELLO] PRIMARY KEY CLUSTERED 
(
	[PERSONALE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PULIZIA]    Script Date: 18/12/2023 13:16:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PULIZIA](
	[DATA] [smalldatetime] NOT NULL,
	[UFFICIO] [varchar](22) NOT NULL,
	[TURNO] [varchar](10) NOT NULL,
	[PERSONALE] [varchar](22) NOT NULL,
	[NUM_ORE] [int] NULL,
 CONSTRAINT [PK_QUASICISIAMO] PRIMARY KEY CLUSTERED 
(
	[DATA] ASC,
	[UFFICIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UFFICIO]    Script Date: 18/12/2023 13:16:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UFFICIO](
	[UFFICIO] [varchar](22) NOT NULL,
	[DIPARTIMENTO] [varchar](22) NULL,
 CONSTRAINT [PK_STUDENTE] PRIMARY KEY CLUSTERED 
(
	[UFFICIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[AZIENDA] ([AZIENDA], [CITTA]) VALUES (N'110', N'MODENA')
GO
INSERT [dbo].[AZIENDA] ([AZIENDA], [CITTA]) VALUES (N'210', N'POTENZA')
GO
INSERT [dbo].[AZIENDA] ([AZIENDA], [CITTA]) VALUES (N'NO', N'NO')
GO
INSERT [dbo].[CITTA] ([CITTA], [REGIONE]) VALUES (N'MODENA', N'ER')
GO
INSERT [dbo].[CITTA] ([CITTA], [REGIONE]) VALUES (N'NO', N'NO')
GO
INSERT [dbo].[CITTA] ([CITTA], [REGIONE]) VALUES (N'POTENZA', N'LUCANIA')
GO
INSERT [dbo].[DIPARTIMENTO] ([DIPARTIMENTO], [CITTA], [DIRETTORE]) VALUES (N'D_10', N'MODENA', N'UGO')
GO
INSERT [dbo].[DIPARTIMENTO] ([DIPARTIMENTO], [CITTA], [DIRETTORE]) VALUES (N'D_20', N'POTENZA', N'ADA')
GO
INSERT [dbo].[DIPARTIMENTO] ([DIPARTIMENTO], [CITTA], [DIRETTORE]) VALUES (N'D_30', N'POTENZA', N'PIO')
GO
INSERT [dbo].[DIPARTIMENTO] ([DIPARTIMENTO], [CITTA], [DIRETTORE]) VALUES (N'D_NO', N'NO', N'NO')
GO
INSERT [dbo].[DIRETTORE] ([DIRETTORE], [REGIONE]) VALUES (N'ADA', N'PZ')
GO
INSERT [dbo].[DIRETTORE] ([DIRETTORE], [REGIONE]) VALUES (N'NO', N'NO')
GO
INSERT [dbo].[DIRETTORE] ([DIRETTORE], [REGIONE]) VALUES (N'PIO', N'MO')
GO
INSERT [dbo].[DIRETTORE] ([DIRETTORE], [REGIONE]) VALUES (N'UGO', N'MO')
GO
INSERT [dbo].[MACCHINA_PULITRICE] ([DATA], [UFFICIO], [AZIENDA]) VALUES (CAST(N'2023-10-15T00:00:00' AS SmallDateTime), N'U_10', N'110')
GO
INSERT [dbo].[MACCHINA_PULITRICE] ([DATA], [UFFICIO], [AZIENDA]) VALUES (CAST(N'2023-12-08T00:00:00' AS SmallDateTime), N'U_10', N'110')
GO
INSERT [dbo].[MACCHINA_PULITRICE] ([DATA], [UFFICIO], [AZIENDA]) VALUES (CAST(N'2023-12-12T00:00:00' AS SmallDateTime), N'U_10', N'110')
GO
INSERT [dbo].[MACCHINA_PULITRICE] ([DATA], [UFFICIO], [AZIENDA]) VALUES (CAST(N'2023-12-12T00:00:00' AS SmallDateTime), N'U_40', N'210')
GO
INSERT [dbo].[MACCHINA_PULITRICE] ([DATA], [UFFICIO], [AZIENDA]) VALUES (CAST(N'2023-12-13T00:00:00' AS SmallDateTime), N'U_20', N'110')
GO
INSERT [dbo].[PERSONALE] ([PERSONALE], [AZIENDA], [GENERE]) VALUES (N'NO', N'NO', N'NO')
GO
INSERT [dbo].[PERSONALE] ([PERSONALE], [AZIENDA], [GENERE]) VALUES (N'P_1', N'110', N'A')
GO
INSERT [dbo].[PERSONALE] ([PERSONALE], [AZIENDA], [GENERE]) VALUES (N'P_10', N'110', N'B')
GO
INSERT [dbo].[PERSONALE] ([PERSONALE], [AZIENDA], [GENERE]) VALUES (N'P_11', N'210', N'A')
GO
INSERT [dbo].[PERSONALE] ([PERSONALE], [AZIENDA], [GENERE]) VALUES (N'P_2', N'210', N'A')
GO
INSERT [dbo].[PERSONALE] ([PERSONALE], [AZIENDA], [GENERE]) VALUES (N'P_3', N'210', N'B')
GO
INSERT [dbo].[PERSONALE] ([PERSONALE], [AZIENDA], [GENERE]) VALUES (N'P_30', N'110', N'B')
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-08-08T00:00:00' AS SmallDateTime), N'U_10', N'Pomeriggio', N'P_2', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-08-08T00:00:00' AS SmallDateTime), N'U_20', N'Mattina', N'P_3', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-08-08T00:00:00' AS SmallDateTime), N'U_30', N'Pomeriggio', N'P_3', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-08-08T00:00:00' AS SmallDateTime), N'U_40', N'Pomeriggio', N'P_1', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-01T00:00:00' AS SmallDateTime), N'U_10', N'Pomeriggio', N'P_3', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-01T00:00:00' AS SmallDateTime), N'U_20', N'Mattina', N'P_3', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-01T00:00:00' AS SmallDateTime), N'U_30', N'Mattina', N'P_2', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-01T00:00:00' AS SmallDateTime), N'U_40', N'Mattina', N'P_11', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-05T00:00:00' AS SmallDateTime), N'U_10', N'Pomeriggio', N'P_3', 3)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-05T00:00:00' AS SmallDateTime), N'U_20', N'Pomeriggio', N'P_3', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-05T00:00:00' AS SmallDateTime), N'U_30', N'Mattina', N'P_2', 3)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-05T00:00:00' AS SmallDateTime), N'U_40', N'Pomeriggio', N'P_2', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-06T00:00:00' AS SmallDateTime), N'U_10', N'Mattina', N'P_3', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-06T00:00:00' AS SmallDateTime), N'U_20', N'Pomeriggio', N'P_11', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-06T00:00:00' AS SmallDateTime), N'U_30', N'Pomeriggio', N'P_2', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-06T00:00:00' AS SmallDateTime), N'U_40', N'Mattina', N'P_2', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-15T00:00:00' AS SmallDateTime), N'U_10', N'Mattina', N'P_10', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-15T00:00:00' AS SmallDateTime), N'U_20', N'Mattina', N'P_2', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-15T00:00:00' AS SmallDateTime), N'U_30', N'Pomeriggio', N'P_1', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-10-15T00:00:00' AS SmallDateTime), N'U_40', N'Pomeriggio', N'P_11', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-08T00:00:00' AS SmallDateTime), N'U_10', N'Mattina', N'P_3', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-08T00:00:00' AS SmallDateTime), N'U_20', N'Pomeriggio', N'P_1', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-08T00:00:00' AS SmallDateTime), N'U_30', N'Pomeriggio', N'P_2', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-08T00:00:00' AS SmallDateTime), N'U_40', N'Pomeriggio', N'P_3', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-12T00:00:00' AS SmallDateTime), N'U_10', N'Pomeriggio', N'P_11', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-12T00:00:00' AS SmallDateTime), N'U_20', N'Mattina', N'P_30', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-12T00:00:00' AS SmallDateTime), N'U_30', N'Mattina', N'P_2', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-12T00:00:00' AS SmallDateTime), N'U_40', N'Mattina', N'P_3', 1)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-13T00:00:00' AS SmallDateTime), N'U_10', N'Pomeriggio', N'P_1', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-13T00:00:00' AS SmallDateTime), N'U_20', N'Mattina', N'P_1', 3)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-13T00:00:00' AS SmallDateTime), N'U_30', N'Pomeriggio', N'p_1', 2)
GO
INSERT [dbo].[PULIZIA] ([DATA], [UFFICIO], [TURNO], [PERSONALE], [NUM_ORE]) VALUES (CAST(N'2023-12-13T00:00:00' AS SmallDateTime), N'U_40', N'Mattina', N'P_2', 2)
GO
INSERT [dbo].[UFFICIO] ([UFFICIO], [DIPARTIMENTO]) VALUES (N'U_10', N'D_10')
GO
INSERT [dbo].[UFFICIO] ([UFFICIO], [DIPARTIMENTO]) VALUES (N'U_20', N'D_30')
GO
INSERT [dbo].[UFFICIO] ([UFFICIO], [DIPARTIMENTO]) VALUES (N'U_30', N'D_30')
GO
INSERT [dbo].[UFFICIO] ([UFFICIO], [DIPARTIMENTO]) VALUES (N'U_40', N'D_30')
GO
INSERT [dbo].[UFFICIO] ([UFFICIO], [DIPARTIMENTO]) VALUES (N'U_NO', N'D_NO')
GO
ALTER TABLE [dbo].[AZIENDA]  WITH CHECK ADD  CONSTRAINT [FK_CONTOCORRENTE_BANCA] FOREIGN KEY([CITTA])
REFERENCES [dbo].[CITTA] ([CITTA])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[AZIENDA] CHECK CONSTRAINT [FK_CONTOCORRENTE_BANCA]
GO
ALTER TABLE [dbo].[DIPARTIMENTO]  WITH CHECK ADD  CONSTRAINT [FK_DIPARTIMENTO_CITTA] FOREIGN KEY([CITTA])
REFERENCES [dbo].[CITTA] ([CITTA])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DIPARTIMENTO] CHECK CONSTRAINT [FK_DIPARTIMENTO_CITTA]
GO
ALTER TABLE [dbo].[DIPARTIMENTO]  WITH CHECK ADD  CONSTRAINT [FK_DIPARTIMENTO_DIRETTORE] FOREIGN KEY([DIRETTORE])
REFERENCES [dbo].[DIRETTORE] ([DIRETTORE])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[DIPARTIMENTO] CHECK CONSTRAINT [FK_DIPARTIMENTO_DIRETTORE]
GO
ALTER TABLE [dbo].[MACCHINA_PULITRICE]  WITH CHECK ADD  CONSTRAINT [FK_MACCHINA_PULITRICE_AZIENDA] FOREIGN KEY([AZIENDA])
REFERENCES [dbo].[AZIENDA] ([AZIENDA])
GO
ALTER TABLE [dbo].[MACCHINA_PULITRICE] CHECK CONSTRAINT [FK_MACCHINA_PULITRICE_AZIENDA]
GO
ALTER TABLE [dbo].[MACCHINA_PULITRICE]  WITH CHECK ADD  CONSTRAINT [FK_MACCHINA_PULITRICE_QUASICISIAMO] FOREIGN KEY([DATA], [UFFICIO])
REFERENCES [dbo].[PULIZIA] ([DATA], [UFFICIO])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[MACCHINA_PULITRICE] CHECK CONSTRAINT [FK_MACCHINA_PULITRICE_QUASICISIAMO]
GO
ALTER TABLE [dbo].[PERSONALE]  WITH CHECK ADD  CONSTRAINT [FK_APPELLO_CORSO] FOREIGN KEY([AZIENDA])
REFERENCES [dbo].[AZIENDA] ([AZIENDA])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PERSONALE] CHECK CONSTRAINT [FK_APPELLO_CORSO]
GO
ALTER TABLE [dbo].[PULIZIA]  WITH CHECK ADD  CONSTRAINT [FK_QUASICISIAMO_PERSONALE] FOREIGN KEY([PERSONALE])
REFERENCES [dbo].[PERSONALE] ([PERSONALE])
GO
ALTER TABLE [dbo].[PULIZIA] CHECK CONSTRAINT [FK_QUASICISIAMO_PERSONALE]
GO
ALTER TABLE [dbo].[PULIZIA]  WITH CHECK ADD  CONSTRAINT [FK_QUASICISIAMO_UFFICIO] FOREIGN KEY([UFFICIO])
REFERENCES [dbo].[UFFICIO] ([UFFICIO])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[PULIZIA] CHECK CONSTRAINT [FK_QUASICISIAMO_UFFICIO]
GO
ALTER TABLE [dbo].[UFFICIO]  WITH CHECK ADD  CONSTRAINT [FK_UFFICIO_DIPARTIMENTO] FOREIGN KEY([DIPARTIMENTO])
REFERENCES [dbo].[DIPARTIMENTO] ([DIPARTIMENTO])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[UFFICIO] CHECK CONSTRAINT [FK_UFFICIO_DIPARTIMENTO]
GO
