
-- LE ANALISI NON SONO FATTE PER TROVARE UN VALORE SPECIFICO
-- SONO ANALISI FATTE E RIFATTE MA APPLICATE AD UN DETERMINATO CONTESTO
-- MOSTRARE NON AGGREGABILITA CON WITH CUBE
-- APPLICARE DELLE WINDOW FUNCTIONS (ANCHE SENZA WITH CUBE)


-- PATTERN DA ANALIZZARE
-- {DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO}
-- CONVIENE UTILIZZARE I PATTERN PRESENTI NELLE NA DELLE MISURE

SELECT * FROM VIEWSTARSCHEMA

-- SQL-OLAP
DROP VIEW IF EXISTS SQL_OLAP

ALTER VIEW SQL_OLAP AS
SELECT	DATA, AZIENDA_PERSONALE, DIPARTIMENTO,
		SUM(NUMPULIZIE) AS 'NUMPULIZIE',
		SUM(NUMORE) AS 'NUMORE',
		IIF(GROUPING(DATA) = 1, -SUM(NUMUFFICI),SUM(NUMUFFICI)) AS NUMUFFICI, --NA = {DATA}
		IIF(GROUPING(DATA) = 1 OR GROUPING(DIPARTIMENTO) = 1, -SUM(NUMPERSONALE),SUM(NUMPERSONALE)) AS NUMPERSONALE_NONCALCOLABILE --NA = {DATA,DIPARTIMENTO,TURNO,AZIENDA_MP}
FROM VIEWSTARSCHEMA
GROUP BY DATA, AZIENDA_PERSONALE, DIPARTIMENTO WITH CUBE

-- NUMPERSONALE NON CALCOLABILE NEL PATTERN MANCA TURNO, AZIENDA_MP
-- CONTROLLO
SELECT DATA, AZIENDA_PERSONALE, DIPARTIMENTO,NUMPERSONALE_NONCALCOLABILE
FROM SQL_OLAP
ORDER BY DATA DESC

SELECT DATA, AZIENDA_PERSONALE, DIPARTIMENTO,NUMPERSONALE = COUNT(DISTINCT PERSONALE)
FROM PER_FT
GROUP BY DATA, AZIENDA_PERSONALE, DIPARTIMENTO
ORDER BY DATA DESC


-- WINDOW FUNCTION

-- Per ogni azienda, il dipartimento con il maggior numero ore e la relativa percentuale
WITH AZIENDA_DIP_ORE AS
(
SELECT AZIENDA_PERSONALE, DIPARTIMENTO, NUMORE = SUM(NUMORE)
FROM VIEWSTARSCHEMA
GROUP BY AZIENDA_PERSONALE, DIPARTIMENTO
), AZIENDA_DIP_RANKED AS
(
SELECT	*, RANK() OVER (PARTITION BY AZIENDA_PERSONALE ORDER BY NUMORE DESC) AS [RANK],
		TOTORE = SUM(NUMORE) OVER (PARTITION BY AZIENDA_PERSONALE) 
FROM AZIENDA_DIP_ORE
)
SELECT *, RAPPORTO = 100.0 * CAST(NUMORE AS REAL) / TOTORE
FROM AZIENDA_DIP_RANKED
WHERE [RANK] = 1



-- WITH CUBE
WITH AZIENDA_DIP_ORE AS
(
SELECT AZIENDA_PERSONALE, DIPARTIMENTO, NUMORE = SUM(NUMORE)
FROM VIEWSTARSCHEMA
GROUP BY AZIENDA_PERSONALE, DIPARTIMENTO WITH CUBE
), AZIENDA_DIP_RANKED AS
(
SELECT *, RANK() OVER (PARTITION BY AZIENDA_PERSONALE ORDER BY NUMORE DESC) AS [RANK]
FROM AZIENDA_DIP_ORE
)
SELECT *
FROM AZIENDA_DIP_RANKED
WHERE [RANK] <= 2 AND AZIENDA_PERSONALE IS NOT NULL AND DIPARTIMENTO IS NOT NULL




-- ARCO MULTIPLO
CREATE VIEW SQL_OLAP_PD AS
SELECT	DATA, AZIENDA_PERSONALE, SEDE,
	-- Misure pesate
	SUM(NumORE_PES) AS NumORE,
	-- Misure di impatto
CASE
	WHEN GROUPING(SEDE) = 1 THEN -- non c’è SEDE (arco multiplo): USA VERSIONE PESATA
		CASE WHEN GROUPING(DATA) = 1 THEN -SUM(NumUFFICI_PES) ELSE SUM(NumUFFICI_PES) END
	ELSE -- USA VERSIONE NON PESATA
		CASE WHEN GROUPING(DATA) = 1 THEN -SUM(NumUFFICI) ELSE SUM(NumUFFICI) END
END AS NumUFFICI

FROM FACT_TABLE_PD
GROUP BY DATA, AZIENDA_PERSONALE, SEDE WITH CUBE;

-- UNA PRIMA VERIFICA SUL PATTERN VUOTO
SELECT DATA, AZIENDA_PERSONALE, SEDE, NumUFFICI, NumORE FROM SQL_OLAP_PD
WHERE DATA IS NULL AND AZIENDA_PERSONALE IS NULL AND SEDE IS NULL

SELECT NumUFFICI=COUNT(DISTINCT UFFICIO) , NumORE=SUM([NUM_ORE]) FROM PER_FT

-- UNA SECONDA VERIFICA SUL PATTERN {DATA}

SELECT DATA, AZIENDA_PERSONALE, SEDE, NumUFFICI, NumORE FROM SQL_OLAP_PD
WHERE DATA IS NOT NULL AND AZIENDA_PERSONALE IS NULL AND SEDE IS NULL
ORDER BY DATA -- PER FACILITARE CONFRONTO

SELECT DATA, NumUFFICI=COUNT(DISTINCT UFFICIO) , NumORE=SUM([NUM_ORE]) FROM PER_FT
GROUP BY DATA
ORDER BY DATA -- PER FACILITARE CONFRONTO

-- UNA TERZA VERIFICA SUL PATTERN {DATA,SEDE}
SELECT DATA, AZIENDA_PERSONALE, SEDE, NumUFFICI, NumORE FROM SQL_OLAP_PD
WHERE DATA IS NOT NULL AND AZIENDA_PERSONALE IS NULL AND SEDE = 'Y'
ORDER BY DATA -- PER FACILITARE CONFRONTO


SELECT DATA, NumUFFICI=COUNT(DISTINCT UFFICIO) ,
NumORE=SUM([NUM_ORE] * P.PESO)
FROM PER_FT F INNER JOIN PESO P ON F.DIPARTIMENTO = P.DIPARTIMENTO
WHERE sede='Y'
GROUP BY DATA, SEDE
ORDER BY DATA -- PER FACILITARE CONFRONTO