
-- DIMENSION TABLE DIPARTIMENTO
DROP VIEW IF EXISTS DT_DIPARTIMENTO

CREATE VIEW DT_DIPARTIMENTO AS
SELECT dbo.DIPARTIMENTO.DIPARTIMENTO, dbo.CITTA.CITTA AS DIPARTIMENTO_CITTA, dbo.CITTA.REGIONE AS DIPARTIMENTO_REGIONE, dbo.DIRETTORE.DIRETTORE, dbo.DIRETTORE.REGIONE AS DIRETTORE_REGIONE
FROM     dbo.CITTA INNER JOIN
                  dbo.DIPARTIMENTO ON dbo.CITTA.CITTA = dbo.DIPARTIMENTO.CITTA INNER JOIN
                  dbo.DIRETTORE ON dbo.DIPARTIMENTO.DIRETTORE = dbo.DIRETTORE.DIRETTORE

SELECT COUNT(*) FROM DIPARTIMENTO
SELECT COUNT(*) FROM DT_DIPARTIMENTO


-- DIMENSION TABLE AZIENDA_PERSONALE
DROP VIEW IF EXISTS DT_AZIENDA_PERSONALE

CREATE VIEW DT_AZIENDA_PERSONALE AS
SELECT dbo.AZIENDA.AZIENDA AS AZIENDA_PERSONALE, dbo.CITTA.CITTA AS AZIENDA_PERSONALE_CITTA, dbo.CITTA.REGIONE AS AZIENDA_PERSONALE_REGIONE
FROM     dbo.AZIENDA INNER JOIN
                  dbo.CITTA ON dbo.AZIENDA.CITTA = dbo.CITTA.CITTA

SELECT COUNT(*) FROM DT_AZIENDA_PERSONALE
SELECT COUNT(*) FROM AZIENDA

-- DIMENSION TABLE AZIENDA_MACCHINA_PULITRICE
DROP VIEW IF EXISTS DT_AZIENDA_MACCHINA_PULITRICE

CREATE VIEW DT_AZIENDA_MACCHINA_PULITRICE AS
SELECT dbo.AZIENDA.AZIENDA AS AZIENDA_MACCHINA_PULITRICE, dbo.CITTA.CITTA AS AZIENDA_MACCHINA_PULITRICE_CITTA, dbo.CITTA.REGIONE AS AZIENDA_MACCHINA_PULITRICE_REGIONE
FROM     dbo.AZIENDA INNER JOIN
                  dbo.CITTA ON dbo.AZIENDA.CITTA = dbo.CITTA.CITTA

SELECT COUNT(*) FROM DT_AZIENDA_MACCHINA_PULITRICE
SELECT COUNT(*) FROM AZIENDA

-- FACT TABLE PULIZIA

--- VISTA APPOGGIO
DROP VIEW IF EXISTS PER_FT 

CREATE VIEW PER_FT AS
SELECT dbo.PULIZIA.DATA, dbo.PULIZIA.UFFICIO, dbo.PULIZIA.TURNO, dbo.PULIZIA.NUM_ORE, dbo.PERSONALE.PERSONALE, dbo.PERSONALE.AZIENDA AS AZIENDA_PERSONALE, dbo.UFFICIO.DIPARTIMENTO, 
                  CASE WHEN dbo.MACCHINA_PULITRICE.AZIENDA IS NULL THEN 'NO' ELSE dbo.MACCHINA_PULITRICE.AZIENDA END AS AZIENDA_MACCHINA_PULITRICE
FROM     dbo.MACCHINA_PULITRICE RIGHT JOIN
                  dbo.PULIZIA ON dbo.MACCHINA_PULITRICE.DATA = dbo.PULIZIA.DATA AND dbo.MACCHINA_PULITRICE.UFFICIO = dbo.PULIZIA.UFFICIO INNER JOIN
                  dbo.PERSONALE ON dbo.PULIZIA.PERSONALE = dbo.PERSONALE.PERSONALE INNER JOIN
                  dbo.UFFICIO ON dbo.PULIZIA.UFFICIO = dbo.UFFICIO.UFFICIO


--- FACT TABLE
DROP VIEW IF EXISTS FACT_TABLE

CREATE VIEW FACT_TABLE AS
SELECT	DATA,DIPARTIMENTO, TURNO, AZIENDA_PERSONALE, AZIENDA_MACCHINA_PULITRICE,
		NUMPULIZIE=COUNT(*), NUMORE=SUM(NUM_ORE), 
		NUMUFFICI=COUNT(DISTINCT UFFICIO), NUMPERSONALE=COUNT(DISTINCT PERSONALE)
FROM PER_FT
GROUP BY DATA,DIPARTIMENTO, TURNO, AZIENDA_PERSONALE, AZIENDA_MACCHINA_PULITRICE



-- STAR SCHEMA
DROP TABLE STARSCHEMA.DT_AZIENDA_MACCHINA_PULITRICE
DROP TABLE STARSCHEMA.DT_DIPARTIMENTO
DROP TABLE STARSCHEMA.DT_AZIENDA_PERSONALE
DROP TABLE STARSCHEMA.FACT_TABLE

DROP SCHEMA IF EXISTS STARSCHEMA

CREATE SCHEMA STARSCHEMA

SELECT * INTO STARSCHEMA.FACT_TABLE FROM FACT_TABLE
SELECT * INTO STARSCHEMA.DT_DIPARTIMENTO FROM DT_DIPARTIMENTO
SELECT * INTO STARSCHEMA.DT_AZIENDA_PERSONALE FROM DT_AZIENDA_PERSONALE
SELECT * INTO STARSCHEMA.DT_AZIENDA_MACCHINA_PULITRICE FROM DT_AZIENDA_MACCHINA_PULITRICE

DROP VIEW IF EXISTS VIEWSTARSCHEMA

CREATE VIEW VIEWSTARSCHEMA AS
SELECT dbo.FACT_TABLE.DATA, dbo.FACT_TABLE.TURNO, dbo.DT_AZIENDA_PERSONALE.AZIENDA_PERSONALE, dbo.DT_AZIENDA_PERSONALE.AZIENDA_PERSONALE_CITTA, 
                  dbo.DT_AZIENDA_PERSONALE.AZIENDA_PERSONALE_REGIONE, dbo.DT_DIPARTIMENTO.DIPARTIMENTO, dbo.DT_DIPARTIMENTO.DIPARTIMENTO_CITTA, dbo.DT_DIPARTIMENTO.DIPARTIMENTO_REGIONE, 
                  dbo.DT_DIPARTIMENTO.DIRETTORE, dbo.DT_DIPARTIMENTO.DIRETTORE_REGIONE, dbo.DT_AZIENDA_MACCHINA_PULITRICE.AZIENDA_MACCHINA_PULITRICE, 
                  dbo.DT_AZIENDA_MACCHINA_PULITRICE.AZIENDA_MACCHINA_PULITRICE_CITTA, dbo.DT_AZIENDA_MACCHINA_PULITRICE.AZIENDA_MACCHINA_PULITRICE_REGIONE, dbo.FACT_TABLE.NUMPULIZIE, dbo.FACT_TABLE.NUMORE, 
                  dbo.FACT_TABLE.NUMUFFICI, dbo.FACT_TABLE.NUMPERSONALE
FROM     dbo.FACT_TABLE INNER JOIN
                  dbo.DT_AZIENDA_PERSONALE ON dbo.FACT_TABLE.AZIENDA_PERSONALE = dbo.DT_AZIENDA_PERSONALE.AZIENDA_PERSONALE INNER JOIN
                  dbo.DT_AZIENDA_MACCHINA_PULITRICE ON dbo.FACT_TABLE.AZIENDA_MACCHINA_PULITRICE = dbo.DT_AZIENDA_MACCHINA_PULITRICE.AZIENDA_MACCHINA_PULITRICE INNER JOIN
                  dbo.DT_DIPARTIMENTO ON dbo.FACT_TABLE.DIPARTIMENTO = dbo.DT_DIPARTIMENTO.DIPARTIMENTO

SELECT COUNT(*) FROM VIEWSTARSCHEMA
SELECT COUNT(*) FROM FACT_TABLE



-- ARCO MULTIPLO 
SELECT DIPARTIMENTO, 'X' AS SEDE, 1.0 AS PESO INTO PESO FROM DIPARTIMENTO
UPDATE PESO SET PESO=0.5 WHERE DIPARTIMENTO = 'D_10'
INSERT PESO SELECT 'D_10','Y',0.5 select * from PESO


CREATE VIEW FACT_TABLE_PD AS
SELECT DATA, TURNO, AZIENDA_PERSONALE, F.DIPARTIMENTO, AZIENDA_MACCHINA_PULITRICE,P.SEDE,
		-- Impatto
		NumUFFICI, -- VERSIONE NON PESATA
		NumUFFICI_PES = NumUFFICI * P.PESO, -- VERSIONE PESATA
		-- Pesata
		NumORE_PES = NumORE * P.PESO
FROM FACT_TABLE F INNER JOIN PESO P ON F.DIPARTIMENTO = P.DIPARTIMENTO

