
-- Dimension Table Studente

DROP VIEW IF EXISTS DT_STUD

CREATE VIEW DT_STUD AS
SELECT  
    CONCAT(STUDENTE.MATR,'_',STUDENTE.CDL)  AS 'STUDENTE.STUD',    
    STUDENTE.SESSO AS 'STUDENTE.SESSO',  
    PERSONA.CF AS 'PERSONA.CF',  
    PERSONA.ETA AS 'PERSONA.ETA',  
    STUDENTE_CITTA.CITTA AS 'STUDENTE_CITTA.CITTA',  
    STUDENTE_CITTA.ALTIT AS 'STUDENTE_CITTA.ALTIT',  
    STUDENTE_REGIONE.REG AS 'STUDENTE_REGIONE.REG',  
    STUDENTE_REGIONE.STATO AS 'STUDENTE_REGIONE.STATO',  
    STUDENTE_REGIONE.CONT AS 'STUDENTE_REGIONE.CONT',  
    STUDENTE_REGIONE.CAPOL AS 'STUDENTE_REGIONE.CAPOL'  
FROM dbo.CITTA AS STUDENTE_CITTA  
INNER JOIN dbo.PER AS PERSONA  
    ON STUDENTE_CITTA.CITTA = PERSONA.CITTA  
INNER JOIN dbo.REG AS STUDENTE_REGIONE  
    ON STUDENTE_CITTA.REG = STUDENTE_REGIONE.REG  
INNER JOIN dbo.STUD AS STUDENTE  
    ON PERSONA.CF = STUDENTE.CF;  


-- Controllare sempre che il numero di tuple sia quello del DBO

SELECT COUNT(*) FROM DT_STUD;
SELECT COUNT(*) FROM STUD



-- Dimension Table Docente

CREATE VIEW DT_DOC AS
SELECT  
	CASE WHEN DOC_TECN.CF IS NOT NULL THEN 'S' ELSE 'N' END AS 'DOC_TECN_Y_N',
    COALESCE(DOC_TECN.SPEC,'NO_SPEC') AS 'DOC_TECN.SPEC',  
    DOC.CF AS 'DOC.CF',  
    DIP_CITTA.CITTA AS 'DIP_CITTA.CITTA',  
    DOC.DIP AS 'DOC.DIP',  
    DIP_CITTA.ALTIT AS 'DIP_CITTA.ALTIT',  
    DIP_REGIONE.REG AS 'DIP_REGIONE.REG',  
    DIP_REGIONE.STATO AS 'DIP_REGIONE.STATO',  
    DIP_REGIONE.CONT AS 'DIP_REGIONE.CONT',  
    DIP_REGIONE.CAPOL AS 'DIP_REGIONE.CAPOL',  
    DOCENTE_REGIONE.REG AS 'DOCENTE_REGIONE.REG',  
    DOCENTE_REGIONE.CONT AS 'DOCENTE_REGIONE.CONT',  
    DOCENTE_REGIONE.STATO AS 'DOCENTE_REGIONE.STATO',  
    DOCENTE_REGIONE.CAPOL AS 'DOCENTE_REGIONE.CAPOL',  
    DOCENTE_CITTA.CITTA AS 'DOCENTE_CITTA.CITTA',  
    DOCENTE_CITTA.ALTIT AS 'DOCENTE_CITTA.ALTIT',  
    PER.ETA AS 'PER.ETA',  
    PER.CF AS 'PER.CF'  
FROM dbo.REG AS DOCENTE_REGIONE  
INNER JOIN dbo.PER  
    INNER JOIN dbo.CITTA AS DOCENTE_CITTA  
        ON PER.CITTA = DOCENTE_CITTA.CITTA  
    INNER JOIN dbo.DOC  
        ON PER.CF = DOC.CF  
    ON DOCENTE_REGIONE.REG = DOCENTE_CITTA.REG  
INNER JOIN dbo.CITTA AS DIP_CITTA  
    ON DOC.DIP_CITTA = DIP_CITTA.CITTA  
INNER JOIN dbo.REG AS DIP_REGIONE  
    ON DIP_CITTA.REG = DIP_REGIONE.REG  
LEFT JOIN dbo.DOC_TECN  
    ON DOC.CF = DOC_TECN.CF;  


SELECT COUNT(*) FROM DT_DOC
SELECT COUNT(*) FROM DOC

-- Fact Table

CREATE VIEW FACT_TABLE AS
SELECT MATR + '_' + CDL AS STUD, DOC, ANNO, COUNT(*) AS NUMESAMI, MAX(VOTO) AS MAXVOTO
FROM ESAME
GROUP BY MATR,CDL,DOC,ANNO


-- Star schema 

CREATE SCHEMA STARSCHEMA;

SELECT * INTO STARSCHEMA.FACT_TABLE FROM FACT_TABLE;
SELECT * INTO STARSCHEMA.DT_STUD FROM DT_STUD;
SELECT * INTO STARSCHEMA.DT_DOC FROM DT_DOC;


-- Snowflake schema

CREATE VIEW DT_CITTA AS SELECT * FROM CITTA
CREATE VIEW DT_REG AS SELECT REG, CAPOL, STATO FROM REG
CREATE VIEW DT_STATO AS SELECT DISTINCT STATO, CONT FROM REG

CREATE VIEW DT_DIP AS SELECT DISTINCT DIP FROM DOC


CREATE SCHEMA SNOWFLAKE

SELECT * INTO SNOWFLAKE.DT_STUD FROM DT_STUD
SELECT * INTO SNOWFLAKE.DT_CITTA FROM DT_CITTA
SELECT * INTO SNOWFLAKE.DT_DOC FROM DT_DOC
SELECT * INTO SNOWFLAKE.DT_STATO FROM DT_STATO
SELECT * INTO SNOWFLAKE.DT_REG FROM DT_REG
SELECT * INTO SNOWFLAKE.FACT_TABLE FROM FACT_TABLE



