SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CITTA](
	[CITTA] [varchar](20) NOT NULL,
	[REGIONE] [varchar](20) NULL,
 CONSTRAINT [PK_CITTA] PRIMARY KEY CLUSTERED 
(
	[CITTA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DIPARTIMENTO](
	[DIP] [varchar](20) NOT NULL,
	[SEDE] [varchar](20) NULL,
	[GENERE] [varchar](20) NULL,
 CONSTRAINT [PK_DIPARTIMENTO] PRIMARY KEY CLUSTERED 
(
	[DIP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DIPENDENTE](
	[CF] [varchar](20) NOT NULL,
	[AFFERISCE_A] [varchar](20) NULL,
	[RESIDENZA] [varchar](20) NULL,
	[ETA] [int] NULL,
 CONSTRAINT [PK_DIPENDENTE] PRIMARY KEY CLUSTERED 
(
	[CF] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [PROGETTO](
	[COD_PROG] [varchar](20) NOT NULL,
	[NOME] [varchar](20) NULL,
	[PROPOSTO_DA] [varchar](20) NULL,
	[CATEGORIA] [varchar](20) NULL,
 CONSTRAINT [PK_PROGETTO] PRIMARY KEY CLUSTERED 
(
	[COD_PROG] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CAPOREPARTO](
	[CF] [varchar](20) NOT NULL,
	[CLASSE] [varchar](20) NULL,
 CONSTRAINT [PK_CAPOREPARTO] PRIMARY KEY CLUSTERED 
(
	[CF] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ATTIVITASVOLTA](
	[MESE] [varchar](20) NOT NULL,
	[COD_PROG] [varchar](20) NOT NULL,
	[NOMEATTIVITA] [varchar](20) NOT NULL,
	[SVOLTA_DA] [varchar](20) NULL,
	[NORE] [int] NULL,
 CONSTRAINT [PK_ATTIVITASVOLTA] PRIMARY KEY CLUSTERED 
(
	[MESE] ASC,
	[COD_PROG] ASC,
	[NOMEATTIVITA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [REPARTO](
	[REPARTO] [varchar](20) NOT NULL,
	[RESPONSABILE] [varchar](20) NULL,
	[DIPARTIMENTO] [varchar](20) NULL,
 CONSTRAINT [PK_REPARTO] PRIMARY KEY CLUSTERED 
(
	[REPARTO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [EXTRA](
	[MESE] [varchar](20) NOT NULL,
	[COD_PROG] [varchar](20) NOT NULL,
	[NOMEATTIVITA] [varchar](20) NOT NULL,
	[SVOLTA_IN] [varchar](20) NOT NULL,
	[TIPO] [varchar](20) NULL,
 CONSTRAINT [PK_EXTRA] PRIMARY KEY CLUSTERED 
(
	[MESE] ASC,
	[COD_PROG] ASC,
	[NOMEATTIVITA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [ATTIVITASVOLTA]  WITH CHECK ADD  CONSTRAINT [FK_ATTIVITASVOLTA_DIPENDENTE] FOREIGN KEY([SVOLTA_DA])
REFERENCES [DIPENDENTE] ([CF])
GO
ALTER TABLE [ATTIVITASVOLTA] CHECK CONSTRAINT [FK_ATTIVITASVOLTA_DIPENDENTE]
GO
ALTER TABLE [ATTIVITASVOLTA]  WITH CHECK ADD  CONSTRAINT [FK_ATTIVITASVOLTA_PROGETTO] FOREIGN KEY([COD_PROG])
REFERENCES [PROGETTO] ([COD_PROG])
GO
ALTER TABLE [ATTIVITASVOLTA] CHECK CONSTRAINT [FK_ATTIVITASVOLTA_PROGETTO]
GO
ALTER TABLE [CAPOREPARTO]  WITH CHECK ADD  CONSTRAINT [FK_CAPOREPARTO_DIPENDENTE] FOREIGN KEY([CF])
REFERENCES [DIPENDENTE] ([CF])
GO
ALTER TABLE [CAPOREPARTO] CHECK CONSTRAINT [FK_CAPOREPARTO_DIPENDENTE]
GO
ALTER TABLE [DIPARTIMENTO]  WITH CHECK ADD  CONSTRAINT [FK_DIPARTIMENTO_CITTA] FOREIGN KEY([SEDE])
REFERENCES [CITTA] ([CITTA])
GO
ALTER TABLE [DIPARTIMENTO] CHECK CONSTRAINT [FK_DIPARTIMENTO_CITTA]
GO
ALTER TABLE [DIPENDENTE]  WITH CHECK ADD  CONSTRAINT [FK_DIPENDENTE_CITTA] FOREIGN KEY([RESIDENZA])
REFERENCES [CITTA] ([CITTA])
GO
ALTER TABLE [DIPENDENTE] CHECK CONSTRAINT [FK_DIPENDENTE_CITTA]
GO
ALTER TABLE [DIPENDENTE]  WITH CHECK ADD  CONSTRAINT [FK_DIPENDENTE_DIPARTIMENTO] FOREIGN KEY([AFFERISCE_A])
REFERENCES [DIPARTIMENTO] ([DIP])
GO
ALTER TABLE [DIPENDENTE] CHECK CONSTRAINT [FK_DIPENDENTE_DIPARTIMENTO]
GO
ALTER TABLE [EXTRA]  WITH CHECK ADD  CONSTRAINT [FK_EXTRA_ATTIVITASVOLTA] FOREIGN KEY([MESE], [COD_PROG], [NOMEATTIVITA])
REFERENCES [ATTIVITASVOLTA] ([MESE], [COD_PROG], [NOMEATTIVITA])
GO
ALTER TABLE [EXTRA] CHECK CONSTRAINT [FK_EXTRA_ATTIVITASVOLTA]
GO
ALTER TABLE [EXTRA]  WITH CHECK ADD  CONSTRAINT [FK_EXTRA_REPARTO] FOREIGN KEY([SVOLTA_IN])
REFERENCES [REPARTO] ([REPARTO])
GO
ALTER TABLE [EXTRA] CHECK CONSTRAINT [FK_EXTRA_REPARTO]
GO
ALTER TABLE [PROGETTO]  WITH CHECK ADD  CONSTRAINT [FK_PROGETTO_DIPARTIMENTO] FOREIGN KEY([PROPOSTO_DA])
REFERENCES [DIPARTIMENTO] ([DIP])
GO
ALTER TABLE [PROGETTO] CHECK CONSTRAINT [FK_PROGETTO_DIPARTIMENTO]
GO
ALTER TABLE [REPARTO]  WITH CHECK ADD  CONSTRAINT [FK_REPARTO_CAPOREPARTO] FOREIGN KEY([RESPONSABILE])
REFERENCES [CAPOREPARTO] ([CF])
GO
ALTER TABLE [REPARTO] CHECK CONSTRAINT [FK_REPARTO_CAPOREPARTO]
GO
ALTER TABLE [REPARTO]  WITH CHECK ADD  CONSTRAINT [FK_REPARTO_DIPARTIMENTO] FOREIGN KEY([DIPARTIMENTO])
REFERENCES [DIPARTIMENTO] ([DIP])
GO
ALTER TABLE [REPARTO] CHECK CONSTRAINT [FK_REPARTO_DIPARTIMENTO]
GO



-- 🔹 CITTA
INSERT INTO CITTA (CITTA, REGIONE) VALUES
('Milano', 'Lombardia'),
('Roma', 'Lazio'),
('Torino', 'Piemonte');

-- 🔹 DIPARTIMENTO
INSERT INTO DIPARTIMENTO (DIP, SEDE, GENERE) VALUES
('INF01', 'Milano', 'Informatica'),
('BIO01', 'Roma', 'Biologia'),
('ENG01', 'Torino', 'Ingegneria');

-- 🔹 DIPENDENTE
INSERT INTO DIPENDENTE (CF, AFFERISCE_A, RESIDENZA, ETA) VALUES
('RSSMRA80A01F205X', 'INF01', 'Milano', 45),
('VRDLGI85B12H501Z', 'BIO01', 'Roma', 38),
('BNCLRA90C03L219X', 'ENG01', 'Torino', 29);

-- 🔹 PROGETTO
INSERT INTO PROGETTO (COD_PROG, NOME, PROPOSTO_DA, CATEGORIA) VALUES
('P001', 'AI Research', 'INF01', 'Tecnologia'),
('P002', 'Genetics', 'BIO01', 'Scienza'),
('P003', 'Robotica', 'ENG01', 'Automazione');

-- 🔹 CAPOREPARTO
INSERT INTO CAPOREPARTO (CF, CLASSE) VALUES
('RSSMRA80A01F205X', 'A1'),
('VRDLGI85B12H501Z', 'B2'),
('BNCLRA90C03L219X', 'C3');

-- 🔹 REPARTO
INSERT INTO REPARTO (REPARTO, RESPONSABILE, DIPARTIMENTO) VALUES
('REP01', 'RSSMRA80A01F205X', 'INF01'),
('REP02', 'VRDLGI85B12H501Z', 'BIO01'),
('REP03', 'BNCLRA90C03L219X', 'ENG01');

-- 🔹 ATTIVITASVOLTA
INSERT INTO ATTIVITASVOLTA (MESE, COD_PROG, NOMEATTIVITA, SVOLTA_DA, NORE) VALUES
('Aprile', 'P001', 'Test su dataset', 'RSSMRA80A01F205X', 20),
('Maggio', 'P002', 'Campionamento', 'VRDLGI85B12H501Z', 15),
('Giugno', 'P003', 'Manutenzione Robot', 'BNCLRA90C03L219X', 22),
('Luglio', 'P001', 'Documentazione', 'RSSMRA80A01F205X', 10),
('Agosto', 'P002', 'Pubb.risultati', 'VRDLGI85B12H501Z', 18),
('Settembre', 'P003', 'Test Ambientali', 'BNCLRA90C03L219X', 30);


-- 🔹 EXTRA
INSERT INTO EXTRA (MESE, COD_PROG, NOMEATTIVITA, SVOLTA_IN, TIPO) VALUES
('Aprile', 'P001', 'Test su dataset', 'REP01', 'Formazione'),
('Luglio', 'P001', 'Documentazione', 'REP02', 'Workshop'),
('Giugno', 'P003', 'Manutenzione Robot', 'REP03', 'Ricerca');
