

-- DIMENSION TABLE DIPENDENTE
CREATE VIEW DT_DIPENDENTE AS
SELECT 
    DIPENDENTE_DIPARTIMENTO_CITTA.CITTA AS DIPENDENTE_DIPARTIMENTO_CITTA,
    DIPENDENTE_DIPARTIMENTO_CITTA.REGIONE AS DIPENDENTE_DIPARTIMENTO_REGIONE,
    DIPENDENTE_DIPARTIMENTO.DIP AS DIPENDENTE_DIPARTIMENTO,
    DIPENDENTE_DIPARTIMENTO.GENERE AS DIPENDENTE_DIPARTIMENTO_GENERE,
    DIPENDENTE.CF AS DIPENDENTE_CF,
    DIPENDENTE.ETA AS DIPENDENTE_ETA,
    DIPENDENTE_CITTA.CITTA AS DIPENDENTE_CITTA,
    DIPENDENTE_CITTA.REGIONE AS DIPENDENTE_CITTA_REGIONE
FROM 
    dbo.CITTA AS DIPENDENTE_DIPARTIMENTO_CITTA
    INNER JOIN dbo.DIPARTIMENTO AS DIPENDENTE_DIPARTIMENTO 
        ON DIPENDENTE_DIPARTIMENTO_CITTA.CITTA = DIPENDENTE_DIPARTIMENTO.SEDE 
    INNER JOIN dbo.DIPENDENTE 
        ON DIPENDENTE_DIPARTIMENTO.DIP = DIPENDENTE.AFFERISCE_A 
    INNER JOIN dbo.CITTA AS DIPENDENTE_CITTA 
        ON DIPENDENTE.RESIDENZA = DIPENDENTE_CITTA.CITTA;

SELECT COUNT(*) FROM DT_DIPENDENTE
SELECT COUNT(*) FROM DIPENDENTE


-- DIMENSION TABLE DIPARTIMENTO_PROGETTO
CREATE VIEW DT_DIPARTIMENTO_PROGETTO AS
SELECT 
    DIPARTIMENTO.DIP AS DIPARTIMENTO,
    DIPARTIMENTO.GENERE AS DIPARTIMENTO_GENERE,
    DIPARTIMENTO_CITTA.CITTA AS DIPARTIMENTO_CITTA,
    DIPARTIMENTO_CITTA.REGIONE AS DIPARTIMENTO_CITTA_REGIONE
FROM 
    dbo.CITTA AS DIPARTIMENTO_CITTA
    INNER JOIN dbo.DIPARTIMENTO 
        ON DIPARTIMENTO_CITTA.CITTA = DIPARTIMENTO.SEDE;

SELECT COUNT(*) FROM DT_DIPARTIMENTO_PROGETTO
SELECT COUNT(*) FROM DIPARTIMENTO

-- DIMENSION TABLE EXTRA_REPARTO
ALTER VIEW DT_EXTRA_REPARTO AS
SELECT 
    REPARTO.REPARTO AS REPARTO,
    CAPOREPARTO.CLASSE AS RESPONSABILE_CLASSE,
    RESPONSABILE.CF AS RESPONSABILE_CF,
    RESPONSABILE.ETA AS RESPONSABILE_ETA,
    REPARTO_DIPARTIMENTO_CITTA.CITTA AS REPARTO_DIPARTIMENTO_CITTA,
    REPARTO_DIPARTIMENTO_CITTA.REGIONE AS REPARTO_DIPARTIMENTO_REGIONE,
    REPARTO_DIPARTIMENTO.GENERE AS REPARTO_DIPARTIMENTO_GENERE,
    REPARTO_DIPARTIMENTO.DIP AS REPARTO_DIPARTIMENTO_DIP,
    RESPONSABILE_DIPARTIMENTO.GENERE AS RESPONSABILE_DIPARTIMENTO_GENERE,
    RESPONSABILE_DIPARTIMENTO.DIP AS RESPONSABILE_DIPARTIMENTO_DIP,
    RESPONSABILE_DIPARTIMENTO_CITTA.CITTA AS RESPONSABILE_DIPARTIMENTO_CITTA,
    RESPONSABILE_DIPARTIMENTO_CITTA.REGIONE AS RESPONSABILE_DIPARTIMENTO_REGIONE,
    RESPONSABILE_CITTA.CITTA AS RESPONSABILE_CITTA,
    RESPONSABILE_CITTA.REGIONE AS RESPONSABILE_CITTA_REGIONE
FROM 
    dbo.DIPARTIMENTO AS REPARTO_DIPARTIMENTO
    INNER JOIN dbo.CITTA AS REPARTO_DIPARTIMENTO_CITTA 
        ON REPARTO_DIPARTIMENTO.SEDE = REPARTO_DIPARTIMENTO_CITTA.CITTA 
    INNER JOIN dbo.DIPARTIMENTO AS RESPONSABILE_DIPARTIMENTO 
        INNER JOIN dbo.DIPENDENTE AS RESPONSABILE 
            ON RESPONSABILE_DIPARTIMENTO.DIP = RESPONSABILE.AFFERISCE_A 
        INNER JOIN dbo.CAPOREPARTO 
            ON RESPONSABILE.CF = CAPOREPARTO.CF 
        INNER JOIN dbo.REPARTO 
            ON CAPOREPARTO.CF = REPARTO.RESPONSABILE 
        INNER JOIN dbo.CITTA AS RESPONSABILE_CITTA 
            ON RESPONSABILE.RESIDENZA = RESPONSABILE_CITTA.CITTA 
        ON REPARTO_DIPARTIMENTO.DIP = REPARTO.DIPARTIMENTO 
    INNER JOIN dbo.CITTA AS RESPONSABILE_DIPARTIMENTO_CITTA 
        ON RESPONSABILE_DIPARTIMENTO.SEDE = RESPONSABILE_DIPARTIMENTO_CITTA.CITTA
UNION 
SELECT 'NO_EXTRA','NO_EXTRA','NO_EXTRA',9999,'NO_EXTRA','NO_EXTRA','NO_EXTRA','NO_EXTRA','NO_EXTRA','NO_EXTRA', 'NO_EXTRA','NO_EXTRA','NO_EXTRA','NO_EXTRA'

SELECT COUNT(*) FROM EXTRA
SELECT COUNT(*) FROM DT_EXTRA_REPARTO




-- VISTA APPOGGIO
CREATE VIEW PER_FT AS
SELECT dbo.ATTIVITASVOLTA.MESE, dbo.ATTIVITASVOLTA.SVOLTA_DA AS DIPENDENTE, dbo.ATTIVITASVOLTA.NORE, dbo.ATTIVITASVOLTA.COD_PROG AS PROGETTO, dbo.PROGETTO.PROPOSTO_DA AS DIPARTIMENTO_PROGETTO, 
                  COALESCE(dbo.EXTRA.TIPO,'NO_EXTRA') AS EXTRA_TIPO, COALESCE(dbo.REPARTO.REPARTO,'NO_EXTRA') AS EXTRA_REPARTO
FROM     dbo.PROGETTO INNER JOIN
                  dbo.ATTIVITASVOLTA ON dbo.PROGETTO.COD_PROG = dbo.ATTIVITASVOLTA.COD_PROG LEFT OUTER JOIN
                  dbo.REPARTO INNER JOIN
                  dbo.EXTRA ON dbo.REPARTO.REPARTO = dbo.EXTRA.SVOLTA_IN ON dbo.ATTIVITASVOLTA.MESE = dbo.EXTRA.MESE AND dbo.ATTIVITASVOLTA.COD_PROG = dbo.EXTRA.COD_PROG AND 
                  dbo.ATTIVITASVOLTA.NOMEATTIVITA = dbo.EXTRA.NOMEATTIVITA

SELECT COUNT(*) FROM ATTIVITASVOLTA
SELECT COUNT(*) FROM PER_FT

-- FACT TABLE
CREATE VIEW FACT_TABLE AS 
SELECT	MESE, DIPENDENTE, DIPARTIMENTO_PROGETTO, EXTRA_TIPO, EXTRA_REPARTO,
		SOMMA_NORE = SUM(NORE), COUNT_NORE = COUNT(NORE),
		NUM_PROGETTI = COUNT(DISTINCT PROGETTO)
FROM PER_FT
GROUP BY MESE, DIPENDENTE, DIPARTIMENTO_PROGETTO, EXTRA_TIPO, EXTRA_REPARTO

-- STAR SCHEMA VIRTUALE
ALTER VIEW STARSCHEMA AS
SELECT dbo.FACT_TABLE.DIPENDENTE,dbo.FACT_TABLE.MESE, dbo.FACT_TABLE.DIPARTIMENTO_PROGETTO, dbo.FACT_TABLE.EXTRA_TIPO, dbo.FACT_TABLE.SOMMA_NORE, dbo.FACT_TABLE.COUNT_NORE, dbo.FACT_TABLE.EXTRA_REPARTO, 
                  dbo.FACT_TABLE.NUM_PROGETTI, dbo.DT_DIPARTIMENTO_PROGETTO.DIPARTIMENTO_GENERE, dbo.DT_DIPARTIMENTO_PROGETTO.DIPARTIMENTO_CITTA, dbo.DT_DIPARTIMENTO_PROGETTO.DIPARTIMENTO_CITTA_REGIONE, 
                  dbo.DT_EXTRA_REPARTO.RESPONSABILE_CLASSE, dbo.DT_EXTRA_REPARTO.RESPONSABILE_ETA, dbo.DT_EXTRA_REPARTO.RESPONSABILE_CF, dbo.DT_EXTRA_REPARTO.REPARTO_DIPARTIMENTO_CITTA, 
                  dbo.DT_EXTRA_REPARTO.REPARTO_DIPARTIMENTO_REGIONE, dbo.DT_EXTRA_REPARTO.REPARTO_DIPARTIMENTO_GENERE, dbo.DT_EXTRA_REPARTO.REPARTO_DIPARTIMENTO_DIP, 
                  dbo.DT_EXTRA_REPARTO.RESPONSABILE_DIPARTIMENTO_GENERE, dbo.DT_EXTRA_REPARTO.RESPONSABILE_DIPARTIMENTO_DIP, dbo.DT_EXTRA_REPARTO.RESPONSABILE_DIPARTIMENTO_CITTA, 
                  dbo.DT_EXTRA_REPARTO.RESPONSABILE_DIPARTIMENTO_REGIONE, dbo.DT_EXTRA_REPARTO.RESPONSABILE_CITTA, dbo.DT_EXTRA_REPARTO.RESPONSABILE_CITTA_REGIONE, dbo.DT_DIPENDENTE.DIPENDENTE_ETA, 
                  dbo.DT_DIPENDENTE.DIPENDENTE_CITTA, dbo.DT_DIPENDENTE.DIPENDENTE_CITTA_REGIONE, dbo.DT_DIPENDENTE.DIPENDENTE_DIPARTIMENTO_GENERE, dbo.DT_DIPENDENTE.DIPENDENTE_DIPARTIMENTO, 
                  dbo.DT_DIPENDENTE.DIPENDENTE_DIPARTIMENTO_REGIONE, dbo.DT_DIPENDENTE.DIPENDENTE_DIPARTIMENTO_CITTA
FROM     dbo.DT_DIPARTIMENTO_PROGETTO INNER JOIN
                  dbo.FACT_TABLE ON dbo.DT_DIPARTIMENTO_PROGETTO.DIPARTIMENTO = dbo.FACT_TABLE.DIPARTIMENTO_PROGETTO INNER JOIN
                  dbo.DT_DIPENDENTE ON dbo.FACT_TABLE.DIPENDENTE = dbo.DT_DIPENDENTE.DIPENDENTE_CF INNER JOIN
                  dbo.DT_EXTRA_REPARTO ON dbo.FACT_TABLE.EXTRA_REPARTO = dbo.DT_EXTRA_REPARTO.REPARTO

SELECT * FROM STARSCHEMA