

-- NA = {MESE_DIPENDENTE}

-- NON POSSO CALCOLARE NUM_PROGETTI, IL PATTERNO NON é COMPLETO
CREATE VIEW PATTERN_MESE_DIPENDENTE AS
SELECT MESE, DIPENDENTE, NORE_MEDIO = SUM(SOMMA_NORE) / SUM(COUNT_NORE), NUM_PROGETTI = SUM(NUM_PROGETTI)
FROM STARSCHEMA
GROUP BY MESE, DIPENDENTE WITH CUBE

-- CONTROLLO
SELECT *
FROM PATTERN_MESE_DIPENDENTE
ORDER BY MESE 

SELECT MESE, DIPENDENTE, EXTRA_TIPO, EXTRA_REPARTO,NUM_PROGETTI = COUNT(DISTINCT PROGETTO)
FROM PER_FT
GROUP BY MESE, DIPENDENTE, EXTRA_TIPO, EXTRA_REPARTO
ORDER BY MESE 

--  Realizzare il pattern {DIPENDENTE,MESE,EXTRATIPO} con WITH CUBE
ALTER VIEW ESERCIZIOC AS 
SELECT	MESE, DIPENDENTE,EXTRA_TIPO,
		NORE_MEDIO = SUM(SOMMA_NORE)/SUM(COUNT_NORE), 
		NUM_EXTRA_TIPO= COUNT(DISTINCT EXTRA_TIPO) 
FROM STARSCHEMA 
GROUP BY MESE, DIPENDENTE, EXTRA_TIPO WITH CUBE