

-- WINDOW FUNCTION
DROP VIEW IF EXISTS FACT_TABLE

CREATE TABLE FACT_TABLE (
	DATA DATE,
	AZIENDA_PERSONALE VARCHAR(50),
	DIPARTIMENTO_UFFICIO VARCHAR(50),
	NumORE INT
);


INSERT INTO FACT_TABLE (DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO, NumORE) VALUES
('2024-01-01', 'Alfa', 'HR', 3),
('2024-01-01', 'Alfa', 'HR', 2),
('2024-01-01', 'Alfa', 'IT', 3),
('2024-01-02', 'Alfa', 'HR', 4),
('2024-01-02', 'Beta', 'HR', 6);

SELECT * FROM FACT_TABLE

SELECT  DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO,NumORE,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE) AS TotalePerAzienda,
		SUM(NumORE) OVER() AS GranTotal
FROM FACT_TABLE

SELECT  DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO,NumORE,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE) AS TotalePerAzienda,
		SUM(NumORE) OVER() AS GranTotal,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE ORDER BY DATA) AS TotaleAziendaPerData,
		SUM(NumORE) OVER(ORDER BY DATA) AS GranTotalPerData
FROM FACT_TABLE

-- ROWS UNBOUNDED PRECEDING: considera illimitatamente le righe precedenti nella finestra
SELECT  DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO,NumORE,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE) AS TotalePerAzienda,
		SUM(NumORE) OVER() AS GranTotal,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE ORDER BY DATA) AS TotaleAziendaPerData,
		SUM(NumORE) OVER(ORDER BY DATA) AS GranTotalPerData,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE ORDER BY DATA ROWS UNBOUNDED PRECEDING) AS TotaleAziendaPerDataU,
		SUM(NumORE) OVER(ORDER BY DATA ROWS UNBOUNDED PRECEDING) AS GranTotalPerDataU
FROM FACT_TABLE


SELECT  DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO,NumORE,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE) AS TotalePerAzienda,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO) AS TotaleAziendaDipartimento
FROM FACT_TABLE

SELECT  DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO,NumORE,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE) AS TotalePerAzienda,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO) AS TotaleAziendaDipartimento,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO ORDER BY DATA) AS TotaleAziendaDipartimentoPerData
FROM FACT_TABLE

SELECT  DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO,SUM(NumORE) AS NumORE
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE) AS TotalePerAzienda,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO) AS TotaleAziendaDipartimento,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO ORDER BY DATA) AS TotaleAziendaDipartimentoPerData
FROM FACT_TABLE
GROUP BY DATA,AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO

-- Messaggio 8120, livello 16, stato 1, riga 959
-- La colonna 'FACT_TABLE.NumORE' non è valida nell'elenco di selezione perché non è inclusa 
-- né in una funzione di aggregazione né nella clausola GROUP BY.

CREATE VIEW DATA_AZIENDA_DIPARTIMENTO AS
SELECT DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO, NumORE= SUM(NumORE)
FROM FACT_TABLE
GROUP BY DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO


SELECT  DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE) AS TotalePerAzienda,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO) AS TotaleAziendaDipartimento,
		SUM(NumORE) OVER(PARTITION BY AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO ORDER BY DATA) AS TotaleAziendaDipartimentoPerData
FROM DATA_AZIENDA_DIPARTIMENTO


-- WITH CUBE + WF

ALTER VIEW DATA_AZIENDA_DIPARTIMENTO as
SELECT DATA,AZIENDA_PERSONALE,DIPARTIMENTO_UFFICIO,NumORE= SUM(NumORE)
FROM FACT_TABLE
GROUP BY DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO WITH CUBE

SELECT * FROM DATA_AZIENDA_DIPARTIMENTO

-- DOBBIAMO AGGIUNGERE UN CONTROLLO ALTRIMENTI SBALLA I RISULTATI
-- SUM(CASE WHEN <aggreghi rispetto a DIPARTIMENTO_UFFICIO oppure rispetto a DATA> THEN 0 ELSE NumORE END)


SELECT	DATA, AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO, NumOre as TotOrePerAziendaDipartimento,
		SUM(CASE
				WHEN DIPARTIMENTO_UFFICIO IS NULL OR DATA IS NULL THEN 0
				ELSE NumORE
			END) OVER (PARTITION BY AZIENDA_PERSONALE ORDER BY DATA, DIPARTIMENTO_UFFICIO ROWS UNBOUNDED PRECEDING) AS OrePerAziendaCumulativo ,
		SUM(CASE
				WHEN DIPARTIMENTO_UFFICIO IS NULL OR DATA IS NULL THEN 0
				ELSE NumORE
			END) OVER (PARTITION BY AZIENDA_PERSONALE ) AS TotOrePerAzienda
FROM DATA_AZIENDA_DIPARTIMENTO
WHERE AZIENDA_PERSONALE='Alfa' AND DATA IS NOT NULL AND DIPARTIMENTO_UFFICIO IS NOT NULL


-- RANKING
CREATE VIEW AZIENDA_DIPARTIMENTO AS
SELECT AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO, NUMORE = SUM(NumORE)
FROM FACT_TABLE
GROUP BY AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO

CREATE VIEW V1 AS 
SELECT	AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO,NUMORE,
		SUM(NumORE) OVER (PARTITION BY DIPARTIMENTO_UFFICIO) AS TotaleOrePerDipartimento,
		ROW_NUMBER() OVER (PARTITION BY DIPARTIMENTO_UFFICIO ORDER BY NUMORE DESC) AS [RANK], 
FROM AZIENDA_DIPARTIMENTO

SELECT *, CAST(NUMORE AS REAL) / TotaleOrePerDipartimento AS Rapporto
FROM V1 
WHERE [RANK] = 1

ALTER VIEW V1 AS 
SELECT	AZIENDA_PERSONALE, DIPARTIMENTO_UFFICIO,NUMORE,
		SUM(NumORE) OVER (PARTITION BY AZIENDA_PERSONALE) AS TotaleOrePerAzienda,
		SUM(NumORE) OVER (PARTITION BY DIPARTIMENTO_UFFICIO) AS TotaleOrePerDipartimento,
		ROW_NUMBER() OVER (PARTITION BY DIPARTIMENTO_UFFICIO ORDER BY NUMORE DESC) AS [RANK],
		CAST(NUMORE AS REAL) / SUM(NumORE) OVER (PARTITION BY DIPARTIMENTO_UFFICIO)  AS Rapporto
FROM AZIENDA_DIPARTIMENTO