/****** Object:  Table [dbo].[AZIENDA]    Script Date: 25/03/2025 08:19:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AZIENDA](
	[AZIENDA] [nchar](10) NOT NULL,
	[CITTA] [nchar](10) NOT NULL,
 CONSTRAINT [PK_AZIENDA] PRIMARY KEY CLUSTERED 
(
	[AZIENDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PESO]    Script Date: 25/03/2025 08:19:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PESO](
	[TIPO] [nchar](10) NOT NULL,
	[AZIENDA] [nchar](10) NOT NULL,
	[PESO] [float] NULL,
 CONSTRAINT [PK_PESO] PRIMARY KEY CLUSTERED 
(
	[TIPO] ASC,
	[AZIENDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODOTTO]    Script Date: 25/03/2025 08:19:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODOTTO](
	[PRODOTTO] [nchar](10) NOT NULL,
	[TIPO] [nchar](10) NULL,
 CONSTRAINT [PK_PRODOTTO] PRIMARY KEY CLUSTERED 
(
	[PRODOTTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SCONTRINO]    Script Date: 25/03/2025 08:19:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCONTRINO](
	[SCONTRINO] [int] NOT NULL,
	[DATA] [nchar](10) NULL,
 CONSTRAINT [PK_SCONTRINO] PRIMARY KEY CLUSTERED 
(
	[SCONTRINO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO]    Script Date: 25/03/2025 08:19:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO](
	[TIPO] [nchar](10) NOT NULL,
	[AZIENDA_SINGOLA] [nchar](10) NOT NULL,
 CONSTRAINT [PK_TIPO] PRIMARY KEY CLUSTERED 
(
	[TIPO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VENDITE]    Script Date: 25/03/2025 08:19:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENDITE](
	[SCONTRINO] [int] NOT NULL,
	[PRODOTTO] [nchar](10) NOT NULL,
	[QTY] [int] NULL,
	[PREZZO] [float] NULL,
 CONSTRAINT [PK_VENDITE] PRIMARY KEY CLUSTERED 
(
	[SCONTRINO] ASC,
	[PRODOTTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[AZIENDA] ([AZIENDA], [CITTA]) VALUES (N'AZ_A      ', N'MO        ')
GO
INSERT [dbo].[AZIENDA] ([AZIENDA], [CITTA]) VALUES (N'AZ_B      ', N'MO        ')
GO
INSERT [dbo].[PESO] ([TIPO], [AZIENDA], [PESO]) VALUES (N'ALIM      ', N'AZ_A      ', 1)
GO
INSERT [dbo].[PESO] ([TIPO], [AZIENDA], [PESO]) VALUES (N'SPOR      ', N'AZ_A      ', 0.5)
GO
INSERT [dbo].[PESO] ([TIPO], [AZIENDA], [PESO]) VALUES (N'SPOR      ', N'AZ_B      ', 0.5)
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [TIPO]) VALUES (N'ALIM_2    ', N'ALIM      ')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [TIPO]) VALUES (N'ALIM_3    ', N'ALIM      ')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [TIPO]) VALUES (N'SPOR_2    ', N'SPOR      ')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [TIPO]) VALUES (N'SPOR_3    ', N'SPOR      ')
GO
INSERT [dbo].[SCONTRINO] ([SCONTRINO], [DATA]) VALUES (1, N'FEB_16    ')
GO
INSERT [dbo].[SCONTRINO] ([SCONTRINO], [DATA]) VALUES (2, N'MAR_18    ')
GO
INSERT [dbo].[SCONTRINO] ([SCONTRINO], [DATA]) VALUES (3, N'MAR_19    ')
GO
INSERT [dbo].[TIPO] ([TIPO], [AZIENDA_SINGOLA]) VALUES (N'ALIM      ', N'AZ_A      ')
GO
INSERT [dbo].[TIPO] ([TIPO], [AZIENDA_SINGOLA]) VALUES (N'SPOR      ', N'AZ_B      ')
GO
INSERT [dbo].[VENDITE] ([SCONTRINO], [PRODOTTO], [QTY], [PREZZO]) VALUES (1, N'ALIM_2    ', 2, 5)
GO
INSERT [dbo].[VENDITE] ([SCONTRINO], [PRODOTTO], [QTY], [PREZZO]) VALUES (1, N'ALIM_3    ', 8, 15)
GO
INSERT [dbo].[VENDITE] ([SCONTRINO], [PRODOTTO], [QTY], [PREZZO]) VALUES (1, N'SPOR_2    ', 2, 25)
GO
INSERT [dbo].[VENDITE] ([SCONTRINO], [PRODOTTO], [QTY], [PREZZO]) VALUES (2, N'SPOR_3    ', 4, 5)
GO
INSERT [dbo].[VENDITE] ([SCONTRINO], [PRODOTTO], [QTY], [PREZZO]) VALUES (3, N'SPOR_2    ', 1, 30)
GO
ALTER TABLE [dbo].[PESO]  WITH CHECK ADD  CONSTRAINT [FK_PESO_AZIENDA] FOREIGN KEY([AZIENDA])
REFERENCES [dbo].[AZIENDA] ([AZIENDA])
GO
ALTER TABLE [dbo].[PESO] CHECK CONSTRAINT [FK_PESO_AZIENDA]
GO
ALTER TABLE [dbo].[PESO]  WITH CHECK ADD  CONSTRAINT [FK_PESO_TIPO] FOREIGN KEY([TIPO])
REFERENCES [dbo].[TIPO] ([TIPO])
GO
ALTER TABLE [dbo].[PESO] CHECK CONSTRAINT [FK_PESO_TIPO]
GO
ALTER TABLE [dbo].[PRODOTTO]  WITH CHECK ADD  CONSTRAINT [FK_PRODOTTO_TIPO] FOREIGN KEY([TIPO])
REFERENCES [dbo].[TIPO] ([TIPO])
GO
ALTER TABLE [dbo].[PRODOTTO] CHECK CONSTRAINT [FK_PRODOTTO_TIPO]
GO
ALTER TABLE [dbo].[VENDITE]  WITH CHECK ADD  CONSTRAINT [FK_VENDITE_PRODOTTO] FOREIGN KEY([PRODOTTO])
REFERENCES [dbo].[PRODOTTO] ([PRODOTTO])
GO
ALTER TABLE [dbo].[VENDITE] CHECK CONSTRAINT [FK_VENDITE_PRODOTTO]
GO
ALTER TABLE [dbo].[VENDITE]  WITH CHECK ADD  CONSTRAINT [FK_VENDITE_SCONTRINO] FOREIGN KEY([SCONTRINO])
REFERENCES [dbo].[SCONTRINO] ([SCONTRINO])
GO
ALTER TABLE [dbo].[VENDITE] CHECK CONSTRAINT [FK_VENDITE_SCONTRINO]
GO
