

CREATE VIEW RELUNI_SINGOLA AS
SELECT dbo.VENDITE.SCONTRINO, dbo.VENDITE.PRODOTTO, dbo.VENDITE.QTY, dbo.VENDITE.PREZZO, dbo.SCONTRINO.DATA, dbo.PRODOTTO.PRODOTTO AS Expr1, dbo.PRODOTTO.TIPO, dbo.TIPO.AZIENDA_SINGOLA
FROM     dbo.VENDITE INNER JOIN
                  dbo.SCONTRINO ON dbo.VENDITE.SCONTRINO = dbo.SCONTRINO.SCONTRINO INNER JOIN
                  dbo.PRODOTTO ON dbo.VENDITE.PRODOTTO = dbo.PRODOTTO.PRODOTTO INNER JOIN
                  dbo.TIPO ON dbo.PRODOTTO.TIPO = dbo.TIPO.TIPO

SELECT * FROM RELUNI_SINGOLA


-- Misure: Numero Vendite = COUNT(*), Numero prodotti = COUNT(DISTINCT PRODOTTO), Incasso = SUM(QTY,PREZZO)

SELECT AZIENDA_SINGOLA, COUNT(*) as NumeroVendite, COUNT(DISTINCT PRODOTTO) as NumeroProdotti, SUM(QTY*PREZZO) as Incasso
FROM RELUNI_SINGOLA R
GROUP BY CUBE(AZIENDA_SINGOLA)



CREATE VIEW RELUNI AS
SELECT dbo.VENDITE.SCONTRINO, dbo.VENDITE.PRODOTTO, dbo.SCONTRINO.DATA, dbo.VENDITE.QTY, dbo.VENDITE.PREZZO, dbo.PESO.AZIENDA, dbo.PESO.PESO, dbo.TIPO.TIPO AS Expr1, dbo.AZIENDA.CITTA
FROM     dbo.AZIENDA INNER JOIN
                  dbo.PESO ON dbo.AZIENDA.AZIENDA = dbo.PESO.AZIENDA INNER JOIN
                  dbo.TIPO ON dbo.PESO.TIPO = dbo.TIPO.TIPO INNER JOIN
                  dbo.PRODOTTO ON dbo.TIPO.TIPO = dbo.PRODOTTO.TIPO INNER JOIN
                  dbo.VENDITE ON dbo.PRODOTTO.PRODOTTO = dbo.VENDITE.PRODOTTO INNER JOIN
                  dbo.SCONTRINO ON dbo.VENDITE.SCONTRINO = dbo.SCONTRINO.SCONTRINO


SELECT * FROM RELUNI

-- Misure: 
-- Numero Vendite = COUNT(*) -> IMPATTO
-- Numero prodotti = COUNT(DISTINCT PRODOTTO) -> IMPATTO
-- Incasso = SUM(QTY,PREZZO) -> PESATA


-- MISURE PESATE

SELECT AZIENDA,SUBSTRING(DATA,1,3) as Mese, SUM(QTY*PREZZO*PESO) as Incasso
FROM RELUNI R
GROUP BY CUBE(AZIENDA,SUBSTRING(DATA,1,3))
ORDER BY SUBSTRING(DATA,1,3) DESC, AZIENDA DESC


SELECT CITTA,SUBSTRING(DATA,1,3) as Mese, SUM(QTY*PREZZO*PESO) as Incasso
FROM RELUNI R
GROUP BY CUBE(CITTA,SUBSTRING(DATA,1,3))
ORDER BY SUBSTRING(DATA,1,3) DESC, CITTA DESC

-- MISURE DI IMPATTO

SELECT SUBSTRING(DATA,1,3) as MESE, AZIENDA, COUNT(*) as NumeroVendite, COUNT(DISTINCT PRODOTTO) as NumeroProdotti
FROM RELUNI R
GROUP BY SUBSTRING(DATA,1,3), AZIENDA WITH CUBE
ORDER BY SUBSTRING(DATA,1,3) DESC, AZIENDA DESC
 -- RISULTATI SBALLATI


 DROP VIEW IF EXISTS FACT_TABLE

 -- CREIAMO FACT TABLE
 CREATE VIEW FACT_TABLE AS
 SELECT TIPO, SUBSTRING(DATA,1,3) AS MESE, COUNT(*) as NumeroVendite, COUNT(DISTINCT PRODOTTO) as NumeroProdotti, SUM(QTY*PREZZO) as Incasso
 FROM RELUNI_SINGOLA R
 GROUP BY TIPO, SUBSTRING(DATA,1,3)

 DROP VIEW IF EXISTS FACT_TABLE_PUSHDOWN

 -- PUSHDOWN AZIENDA IN BASE A PESO(TIPO,AZIENDA,PESO)
 CREATE VIEW FACT_TABLE_PUSHDOWN AS
 SELECT PESO.TIPO, MESE, AZIENDA, NumeroVendite, NumeroProdotti, Incasso, NumeroVendite * PESO AS NumeroVenditePesato, 
		NumeroProdotti * PESO AS NumeroProdottiPesato, Incasso * PESO AS IncassoPesato
 FROM FACT_TABLE JOIN PESO ON FACT_TABLE.TIPO = PESO.TIPO

 -- PATTER SQL-OLAP
 -- DIMENSION TABLE
 CREATE VIEW DT_AZIENDA AS 
 SELECT *
 FROM AZIENDA

 -- PER LE MISURE DI IMPATTO SE GROUPING(AZIENDA) = 0 -> valore non pesato

 SELECT MESE,AZIENDA, INCASSO = SUM(IncassoPesato),
		N_VENDITE = CASE 
						WHEN GROUPING(AZIENDA) = 0 THEN SUM(NumeroVendite)
						ELSE SUM(NumeroVenditePesato)
					END,
		N_PRODOTTI = CASE WHEN GROUPING(MESE) = 0 THEN
						CASE
							WHEN GROUPING(AZIENDA) = 0 THEN SUM(NumeroProdotti)
							ELSE SUM(NumeroProdottiPesato)
						END
					ELSE
						- CASE
							WHEN GROUPING(AZIENDA) = 0 THEN SUM(NumeroProdotti)
							ELSE SUM(NumeroProdottiPesato)
						END
						
					END
 FROM FACT_TABLE_PUSHDOWN
 GROUP BY MESE,AZIENDA WITH CUBE



