

-- DIMENSION TABLE ARBITRO
CREATE VIEW DT_ARBITRO AS
SELECT *
FROM ARBITRO

SELECT COUNT(*) FROM ARBITRO
SELECT COUNT(*) FROM DT_ARBITRO

-- DIMENSION TABLE SQUADRA_FUORI
CREATE VIEW DT_SQUADRA_FUORI AS
SELECT 
    SQUADRA_FUORI.SQUADRA AS SQUADRA_FUORI, 
    SQUADRA_FUORI.CITTA AS SQUADRA_FUORI_CITTA, 
    COALESCE(SQUADRA_FUORI_PRESIDENTE.PRESIDENTE,'NO_PRESIDENTE') AS SQUADRA_FUORI_PRESIDENTE, 
    COALESCE(SQUADRA_FUORI_PRESIDENTE.CITTA,'NO_PRESIDENTE') AS SQUADRA_FUORI_PRESIDENTE_CITTA
FROM dbo.PRESIDENTE AS SQUADRA_FUORI_PRESIDENTE
RIGHT JOIN dbo.SQUADRA AS SQUADRA_FUORI 
    ON SQUADRA_FUORI_PRESIDENTE.PRESIDENTE = SQUADRA_FUORI.PRESIDENTE;

SELECT COUNT(*) FROM SQUADRA
SELECT COUNT(*) FROM DT_SQUADRA_FUORI

-- DIMENSION TABLE TOP_PLAYER
ALTER VIEW DT_TOP_PLAYER AS
SELECT 
    TOP_PLAYER.GIOCATORE AS TOP_PLAYER_GIOCATORE, 
    TOP_PLAYER.RUOLO AS TOP_PLAYER_RUOLO, 
    TOP_PLAYER_SQUADRA.SQUADRA AS TOP_PLAYER_SQUADRA, 
    TOP_PLAYER_SQUADRA.CITTA AS TOP_PLAYER_SQUADRA_CITTA,
	COALESCE(TOP_PLAYER_SQUADRA_PRESIDENTE.PRESIDENTE,'NO_PRESIDENTE') AS TOP_PLAYER_SQUADRA_PRESIDENTE, 
    COALESCE(TOP_PLAYER_SQUADRA_PRESIDENTE.CITTA,'NO_PRESIDENTE') AS TOP_PLAYER_SQUADRA_PRESIDENTE_CITTA
FROM dbo.GIOCATORE AS TOP_PLAYER
INNER JOIN dbo.SQUADRA AS TOP_PLAYER_SQUADRA 
    ON TOP_PLAYER.SQUADRA = TOP_PLAYER_SQUADRA.SQUADRA
LEFT JOIN dbo.PRESIDENTE AS TOP_PLAYER_SQUADRA_PRESIDENTE 
    ON TOP_PLAYER_SQUADRA.PRESIDENTE = TOP_PLAYER_SQUADRA_PRESIDENTE.PRESIDENTE
UNION
SELECT 'NO_TOP_PLAYER','NO_TOP_PLAYER','NO_TOP_PLAYER','NO_TOP_PLAYER','NO_TOP_PLAYER','NO_TOP_PLAYER'


SELECT COUNT(*) FROM DT_TOP_PLAYER
SELECT COUNT(*) FROM GIOCATORE

-- FACT TABLE
ALTER VIEW FACT_TABLE AS
SELECT	COALESCE(dbo.GIOCATA_IN_CAMPO_NEUTRO.CITTA,'NO_CAMPO_NEUTRO') AS CITTA_CAMPO_NEUTRO,
		dbo.PARTITA.SQUADRA_FUORI, 
		dbo.PARTITA.MESE, 
		dbo.PARTITA.ARBITRO, 
        COALESCE(dbo.TOP_PLAYER.TOP_PLAYER,'NO_TOP_PLAYER') AS TOP_PLAYER,
		SOMMA_PREZZO_BIGLIETTO = dbo.PARTITA.PREZ_BIGLIETTO,
FROM     dbo.PARTITA_GIOCATA INNER JOIN
                  dbo.PARTITA ON dbo.PARTITA_GIOCATA.GIORNATA = dbo.PARTITA.GIORNATA AND dbo.PARTITA_GIOCATA.SQUADRA_CASA = dbo.PARTITA.SQUADRA_CASA LEFT OUTER JOIN
                  dbo.TOP_PLAYER ON dbo.PARTITA_GIOCATA.GIORNATA = dbo.TOP_PLAYER.GIORNATA AND dbo.PARTITA_GIOCATA.SQUADRA_CASA = dbo.TOP_PLAYER.SQUADRA_CASA LEFT OUTER JOIN
                  dbo.GIOCATA_IN_CAMPO_NEUTRO ON dbo.PARTITA_GIOCATA.GIORNATA = dbo.GIOCATA_IN_CAMPO_NEUTRO.GIORNATA AND dbo.PARTITA_GIOCATA.SQUADRA_CASA = dbo.GIOCATA_IN_CAMPO_NEUTRO.SQUADRA_CASA

SELECT COUNT(*) FROM PARTITA_GIOCATA
SELECT COUNT(*) FROM FACT_TABLE


CREATE VIEW STARSCHEMA AS
SELECT dbo.FACT_TABLE.CITTA_CAMPO_NEUTRO, dbo.DT_SQUADRA_FUORI.*, dbo.FACT_TABLE.MESE, dbo.FACT_TABLE.SOMMA_PREZZO_BIGLIETTO, dbo.DT_ARBITRO.ARBITRO, dbo.DT_ARBITRO.CITTA AS ARBITRO_CITTA, 
                  dbo.DT_ARBITRO.SESSO AS ARBITRO_SESSO, dbo.DT_TOP_PLAYER.*
FROM     dbo.FACT_TABLE INNER JOIN
                  dbo.DT_SQUADRA_FUORI ON dbo.FACT_TABLE.SQUADRA_FUORI = dbo.DT_SQUADRA_FUORI.SQUADRA_FUORI INNER JOIN
                  dbo.DT_ARBITRO ON dbo.FACT_TABLE.ARBITRO = dbo.DT_ARBITRO.ARBITRO INNER JOIN
                  dbo.DT_TOP_PLAYER ON dbo.FACT_TABLE.TOP_PLAYER = dbo.DT_TOP_PLAYER.TOP_PLAYER_GIOCATORE