

-- PATTERN {MESE, ARBITRO} 
-- IN VERITA DEVO AGGIUNGERE ANCHE SESSO E CITTA AVENDO FD CON ARBITRO
ALTER VIEW PATTERN_MESE_ARBITRO AS
SELECT	MESE,ARBITRO,ARBITRO_SESSO,ARBITRO_CITTA,
		AVG(SOMMA_PREZZO_BIGLIETTO) AS PREZZO_MEDIO_BIGLIETTO,
		NUM_SQUADRA_CASA = CASE WHEN GROUPING(MESE) = 1 OR GROUPING(MESE) = 1 THEN -COUNT(*) ELSE COUNT(*) END,
		-- NUM_CITTA_ARBITRO = CASE  WHEN GROUPING(MESE) = 1 OR GROUPING(MESE) = 1 THEN -COUNT(DISTINCT ARBITRO) ELSE COUNT(DISTINCT ARBITRO)  END, 
		-- NUM_CITTA_ARBITRO MEGLIO DERIVATA
		NUM_CITTA_ARBITRO = COUNT(DISTINCT ARBITRO),
		LIVELLO_DI_RAGGRUPPAMENTO=GROUPING_ID(MESE,ARBITRO,ARBITRO_CITTA,ARBITRO_SESSO)
FROM STARSCHEMA
GROUP BY MESE,ARBITRO,ARBITRO_SESSO,ARBITRO_CITTA WITH CUBE
HAVING NOT (GROUPING(ARBITRO) = 0 AND GROUPING(ARBITRO_CITTA)=1 OR GROUPING(ARBITRO)=0 AND GROUPING(ARBITRO_SESSO)=1)

SELECT COUNT(DISTINCT LIVELLO_DI_RAGGRUPPAMENTO) FROM PATTERN_MESE_ARBITRO

SELECT * FROM PATTERN_MESE_ARBITRO


-- WINDOW FUNCTION
-- PER OGNI MESE ARBITRO CON PREZZO MEDIO PIU ALTO

SELECT MESE, ARBITRO,PREZZO_MEDIO_BIGLIETTO,
		RANK() OVER (PARTITION BY MESE ORDER BY PREZZO_MEDIO_BIGLIETTO DESC) AS [RANK] 
FROM PATTERN_MESE_ARBITRO
WHERE MESE IS NOT NULL AND ARBITRO IS NOT NULL


