/****** Object:  Table [dbo].[AZIENDA]    Script Date: 14/12/2023 16:30:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AZIENDA](
	[AZIENDA] [varchar](12) NOT NULL,
	[CITTA] [varchar](12) NULL,
 CONSTRAINT [PK_AZIENDA] PRIMARY KEY CLUSTERED 
(
	[AZIENDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CITTA]    Script Date: 14/12/2023 16:30:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CITTA](
	[CITTA] [varchar](12) NOT NULL,
	[REGIONE] [varchar](12) NULL,
 CONSTRAINT [PK_CITTA] PRIMARY KEY CLUSTERED 
(
	[CITTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 14/12/2023 16:30:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[CLIENTE] [varchar](12) NOT NULL,
	[CITTA] [varchar](12) NULL,
	[PREFER] [varchar](12) NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DETTAGLIO]    Script Date: 14/12/2023 16:30:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DETTAGLIO](
	[NRIGA] [varchar](12) NOT NULL,
	[ORDINE] [varchar](12) NOT NULL,
	[PRODOTTO] [varchar](12) NULL,
	[COSTO] [float] NULL,
	[DATA_SPED] [varchar](10) NULL,
 CONSTRAINT [PK_DETTAGLIO] PRIMARY KEY CLUSTERED 
(
	[NRIGA] ASC,
	[ORDINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDINE]    Script Date: 14/12/2023 16:30:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDINE](
	[ORDINE] [varchar](12) NOT NULL,
	[CLIENTE] [varchar](12) NULL,
	[DATA_ORDINE] [varchar](10) NULL,
 CONSTRAINT [PK_ORDINE] PRIMARY KEY CLUSTERED 
(
	[ORDINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODOTTO]    Script Date: 14/12/2023 16:30:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODOTTO](
	[PRODOTTO] [varchar](12) NOT NULL,
	[AZIENDA] [varchar](12) NULL,
 CONSTRAINT [PK_PRODOTTO] PRIMARY KEY CLUSTERED 
(
	[PRODOTTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[AZIENDA] ([AZIENDA], [CITTA]) VALUES (N'A10', N'C102')
GO
INSERT [dbo].[AZIENDA] ([AZIENDA], [CITTA]) VALUES (N'A20', N'C30')
GO
INSERT [dbo].[CITTA] ([CITTA], [REGIONE]) VALUES (N'C102', N'R10')
GO
INSERT [dbo].[CITTA] ([CITTA], [REGIONE]) VALUES (N'C20', N'R20')
GO
INSERT [dbo].[CITTA] ([CITTA], [REGIONE]) VALUES (N'C30', N'R20')
GO
INSERT [dbo].[CLIENTE] ([CLIENTE], [CITTA], [PREFER]) VALUES (N'C10', N'C20', N'P10')
GO
INSERT [dbo].[CLIENTE] ([CLIENTE], [CITTA], [PREFER]) VALUES (N'C20', N'C20', N'P30')
GO
INSERT [dbo].[CLIENTE] ([CLIENTE], [CITTA], [PREFER]) VALUES (N'C30', N'C102', N'P30')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'1', N'O1', N'P10', 16, N'2022-12-12')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'1', N'O1_', N'P10_', 28, N'2022-12-12')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'1', N'O2', N'P10', 13, N'2022-12-13')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'1', N'O2_', N'P10_', 25, N'2022-12-13')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'1', N'O3', N'P10', 11, N'2022-10-16')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'1', N'O3_', N'P10_', 23, N'2022-10-15')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'1', N'O4', N'P30', 22, N'2022-12-12')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'1', N'O4_', N'P30_', 34, N'2022-12-13')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'2', N'O1', N'P30', 15, N'2022-12-13')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'2', N'O1_', N'P30_', 27, N'2022-12-13')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'2', N'O2', N'P30', 13, N'2022-10-15')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'2', N'O2_', N'P30_', 25, N'2022-10-15')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'2', N'O3', N'P20', 22, N'2022-10-15')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'2', N'O3_', N'P20_', 34, N'2022-10-15')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'2', N'O4', N'P20', 22, N'2023-02-28')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'23', N'O3', N'P20_', 34, N'2023-02-28')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'3', N'O1', N'P20', 13, N'2022-12-12')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'3', N'O1_', N'P20_', 25, N'2022-12-12')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'3', N'O2', N'P40', 12, N'2022-12-13')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'3', N'O2_', N'P40_', 24, N'2022-12-13')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'3', N'O4', N'P40', 22, N'2022-12-12')
GO
INSERT [dbo].[DETTAGLIO] ([NRIGA], [ORDINE], [PRODOTTO], [COSTO], [DATA_SPED]) VALUES (N'3', N'O4_', N'P40_', 34, N'2022-12-12')
GO
INSERT [dbo].[ORDINE] ([ORDINE], [CLIENTE], [DATA_ORDINE]) VALUES (N'O1', N'C20', N'2022-08-16')
GO
INSERT [dbo].[ORDINE] ([ORDINE], [CLIENTE], [DATA_ORDINE]) VALUES (N'O1_', N'C20', N'2022-08-17')
GO
INSERT [dbo].[ORDINE] ([ORDINE], [CLIENTE], [DATA_ORDINE]) VALUES (N'O2', N'C20', N'2022-08-16')
GO
INSERT [dbo].[ORDINE] ([ORDINE], [CLIENTE], [DATA_ORDINE]) VALUES (N'O2_', N'C20', N'2022-08-17')
GO
INSERT [dbo].[ORDINE] ([ORDINE], [CLIENTE], [DATA_ORDINE]) VALUES (N'O3', N'C20', N'2022-08-16')
GO
INSERT [dbo].[ORDINE] ([ORDINE], [CLIENTE], [DATA_ORDINE]) VALUES (N'O3_', N'C20', N'2022-08-17')
GO
INSERT [dbo].[ORDINE] ([ORDINE], [CLIENTE], [DATA_ORDINE]) VALUES (N'O4', N'C30', N'2022-09-14')
GO
INSERT [dbo].[ORDINE] ([ORDINE], [CLIENTE], [DATA_ORDINE]) VALUES (N'O4_', N'C30', N'2022-09-15')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [AZIENDA]) VALUES (N'P10', N'A10')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [AZIENDA]) VALUES (N'P10_', N'A10')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [AZIENDA]) VALUES (N'P20', N'A20')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [AZIENDA]) VALUES (N'P20_', N'A20')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [AZIENDA]) VALUES (N'P30', N'A20')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [AZIENDA]) VALUES (N'P30_', N'A20')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [AZIENDA]) VALUES (N'P40', N'A20')
GO
INSERT [dbo].[PRODOTTO] ([PRODOTTO], [AZIENDA]) VALUES (N'P40_', N'A20')
GO
ALTER TABLE [dbo].[AZIENDA]  WITH CHECK ADD  CONSTRAINT [FK_AZIENDA_CITTA] FOREIGN KEY([CITTA])
REFERENCES [dbo].[CITTA] ([CITTA])
GO
ALTER TABLE [dbo].[AZIENDA] CHECK CONSTRAINT [FK_AZIENDA_CITTA]
GO
ALTER TABLE [dbo].[CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_CITTA] FOREIGN KEY([CITTA])
REFERENCES [dbo].[CITTA] ([CITTA])
GO
ALTER TABLE [dbo].[CLIENTE] CHECK CONSTRAINT [FK_CLIENTE_CITTA]
GO
ALTER TABLE [dbo].[CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_PRODOTTO] FOREIGN KEY([PREFER])
REFERENCES [dbo].[PRODOTTO] ([PRODOTTO])
GO
ALTER TABLE [dbo].[CLIENTE] CHECK CONSTRAINT [FK_CLIENTE_PRODOTTO]
GO
ALTER TABLE [dbo].[DETTAGLIO]  WITH CHECK ADD  CONSTRAINT [FK_DETTAGLIO_ORDINE] FOREIGN KEY([ORDINE])
REFERENCES [dbo].[ORDINE] ([ORDINE])
GO
ALTER TABLE [dbo].[DETTAGLIO] CHECK CONSTRAINT [FK_DETTAGLIO_ORDINE]
GO
ALTER TABLE [dbo].[DETTAGLIO]  WITH CHECK ADD  CONSTRAINT [FK_DETTAGLIO_PRODOTTO] FOREIGN KEY([PRODOTTO])
REFERENCES [dbo].[PRODOTTO] ([PRODOTTO])
GO
ALTER TABLE [dbo].[DETTAGLIO] CHECK CONSTRAINT [FK_DETTAGLIO_PRODOTTO]
GO
ALTER TABLE [dbo].[ORDINE]  WITH CHECK ADD  CONSTRAINT [FK_ORDINE_CLIENTE] FOREIGN KEY([CLIENTE])
REFERENCES [dbo].[CLIENTE] ([CLIENTE])
GO
ALTER TABLE [dbo].[ORDINE] CHECK CONSTRAINT [FK_ORDINE_CLIENTE]
GO
ALTER TABLE [dbo].[PRODOTTO]  WITH CHECK ADD  CONSTRAINT [FK_PRODOTTO_AZIENDA] FOREIGN KEY([AZIENDA])
REFERENCES [dbo].[AZIENDA] ([AZIENDA])
GO
ALTER TABLE [dbo].[PRODOTTO] CHECK CONSTRAINT [FK_PRODOTTO_AZIENDA]
GO
