

-- STAR SCHEMA

-- DIMENSION TABLE AZIENDA
-- FORMATTA CON CHATGPT
CREATE VIEW DT_AZIENDA AS
SELECT dbo.AZIENDA.AZIENDA, dbo.CITTA.CITTA AS CITTA_AZIENDA, dbo.CITTA.REGIONE AS REGIONE_AZIENDA
FROM     dbo.AZIENDA INNER JOIN
                  dbo.CITTA ON dbo.AZIENDA.CITTA = dbo.CITTA.CITTA


-- DIMENSION TABLE CLIENTE
-- FORMATTA CON CHATGPT
CREATE VIEW DT_CLIENTE AS
SELECT dbo.CLIENTE.CLIENTE, dbo.CITTA.CITTA AS CITTA_CLIENTE, dbo.CITTA.REGIONE AS REGIONE_CLIENTE, dbo.PRODOTTO.PRODOTTO AS PREFERENZA, dbo.AZIENDA.AZIENDA AS CLIENTE_AZIENDA, CITTA_1.CITTA AS CLIENTE_CITTA_AZIENDA, 
                  CITTA_1.REGIONE AS CLIENTE_REGIONE_AZIENDA
FROM     dbo.PRODOTTO INNER JOIN
                  dbo.AZIENDA ON dbo.PRODOTTO.AZIENDA = dbo.AZIENDA.AZIENDA INNER JOIN
                  dbo.CLIENTE INNER JOIN
                  dbo.CITTA ON dbo.CLIENTE.CITTA = dbo.CITTA.CITTA ON dbo.PRODOTTO.PRODOTTO = dbo.CLIENTE.PREFER INNER JOIN
                  dbo.CITTA AS CITTA_1 ON dbo.AZIENDA.CITTA = CITTA_1.CITTA

SELECT COUNT(*) FROM CLIENTE
SELECT COUNT(*) FROM DT_CLIENTE


-- FACT TABLE

-- VISTA DI APPOGGIO

CREATE VIEW PER_FT AS
SELECT dbo.PRODOTTO.AZIENDA, dbo.ORDINE.CLIENTE, dbo.ORDINE.DATA_ORDINE, dbo.DETTAGLIO.DATA_SPED, dbo.DETTAGLIO.COSTO, dbo.PRODOTTO.PRODOTTO, dbo.ORDINE.ORDINE
FROM     dbo.DETTAGLIO INNER JOIN
                  dbo.ORDINE ON dbo.DETTAGLIO.ORDINE = dbo.ORDINE.ORDINE INNER JOIN
                  dbo.PRODOTTO ON dbo.DETTAGLIO.PRODOTTO = dbo.PRODOTTO.PRODOTTO

SELECT COUNT(*) FROM PER_FT
SELECT COUNT(*) FROM DETTAGLIO

-- FT

CREATE VIEW FACT_TABLE AS
SELECT	CLIENTE, AZIENDA, DATA_ORDINE, DATA_SPED, 
		NUMPROD=COUNT(DISTINCT PRODOTTO), NUMSPED=COUNT(*),
		COSTO=SUM(COSTO), NUMORD=COUNT(DISTINCT ORDINE)
FROM PER_FT
GROUP BY CLIENTE, AZIENDA, DATA_ORDINE, DATA_SPED



ALTER VIEW STAR_SCHEMA AS
SELECT  RITARDO = DATEDIFF(DAY, DATA_ORDINE, DATA_SPED), dbo.FACT_TABLE.DATA_ORDINE, dbo.FACT_TABLE.DATA_SPED, dbo.FACT_TABLE.NUMPROD, dbo.FACT_TABLE.NUMSPED, dbo.FACT_TABLE.COSTO, dbo.FACT_TABLE.NUMORD, dbo.DT_CLIENTE.*, dbo.DT_AZIENDA.*
FROM     dbo.FACT_TABLE INNER JOIN
                  dbo.DT_CLIENTE ON dbo.FACT_TABLE.CLIENTE = dbo.DT_CLIENTE.CLIENTE INNER JOIN
                  dbo.DT_AZIENDA ON dbo.FACT_TABLE.AZIENDA = dbo.DT_AZIENDA.AZIENDA


-- ARCO MULTIPLO
SELECT AZIENDA, 'X' AS SETTORE, 1.0 AS PESO INTO PESO FROM AZIENDA
UPDATE PESO SET PESO=0.5 WHERE AZIENDA = 'A20'
INSERT PESO SELECT 'A20','Y',0.5

CREATE VIEW FACT_TABLE_PD AS
SELECT	CLIENTE, FACT_TABLE.AZIENDA, DATA_ORDINE, DATA_SPED, PESO.SETTORE,
		NUMPROD, 
		NUMSPED_P=PESO * NUMSPED,
		NUMSPED,
		COSTO_P=PESO*COSTO, NUMORD
FROM FACT_TABLE LEFT JOIN PESO ON FACT_TABLE.AZIENDA = PESO.AZIENDA


ALTER VIEW STAR_SCHEMA AS
SELECT dbo.DT_CLIENTE.*, dbo.DT_AZIENDA.*, dbo.FACT_TABLE_PD.DATA_ORDINE, dbo.FACT_TABLE_PD.NUMORD, dbo.FACT_TABLE_PD.COSTO_P, dbo.FACT_TABLE_PD.NUMSPED, dbo.FACT_TABLE_PD.NUMSPED_P, 
                  dbo.FACT_TABLE_PD.NUMPROD, dbo.FACT_TABLE_PD.SETTORE, dbo.FACT_TABLE_PD.DATA_SPED
FROM     dbo.DT_CLIENTE INNER JOIN
                  dbo.FACT_TABLE_PD ON dbo.DT_CLIENTE.CLIENTE = dbo.FACT_TABLE_PD.CLIENTE INNER JOIN
                  dbo.DT_AZIENDA ON dbo.FACT_TABLE_PD.AZIENDA = dbo.DT_AZIENDA.AZIENDA

