

SELECT * FROM STAR_SCHEMA
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'STAR_SCHEMA';

-- NA 

-- PATTERN {DATA_ORDINE, DATA_SPED}
CREATE VIEW PATTERN_DATAORDINE_DATASPED AS
SELECT DATA_ORDINE,DATA_SPED, NUMPROD = SUM(NUMPROD), NUMSPED = SUM(NUMSPED), NUMORD = SUM(NUMORD), COSTO = SUM(COSTO)
FROM STAR_SCHEMA
GROUP BY DATA_ORDINE,DATA_SPED

-- NON POSSIAMO CALCOLARE NUMORD 
-- NEL PATTERN NO AZIENDA
-- CONTROLLO
SELECT DATA_ORDINE,DATA_SPED, NUMORD = COUNT(DISTINCT ORDINE)
FROM PER_FT
GROUP BY DATA_ORDINE,DATA_SPED
ORDER BY NUMORD DESC

SELECT * 
FROM PATTERN_DATAORDINE_DATASPED
ORDER BY NUMORD DESC

-- POSSIAMO CALCOLCARE NUMPROD
-- CONTROLLO
SELECT DATA_ORDINE,DATA_SPED, NUMPROD = COUNT(DISTINCT PRODOTTO)
FROM PER_FT
GROUP BY DATA_ORDINE,DATA_SPED
ORDER BY NUMPROD DESC

SELECT * 
FROM PATTERN_DATAORDINE_DATASPED
ORDER BY NUMPROD DESC


-- WINDOW FUNCTION
-- spedizioni con un COSTO_maggiore di quello medio per CLIENTE_CITTA

WITH SPED_MAGGIORI_MEDIO_CITTA AS
(
SELECT	CITTA_CLIENTE, COSTO,
		MEDIOCITTA = AVG(COSTO) OVER (PARTITION BY CITTA_CLIENTE) 
FROM STAR_SCHEMA
)
SELECT *
FROM SPED_MAGGIORI_MEDIO_CITTA
WHERE COSTO > MEDIOCITTA



-- per ogni AZIENDA_CITTA il CLIENTE con il maggior numero di spedizioni complessivo

WITH CLIENTE_SPEDIZIONI AS
(
SELECT	CITTA_AZIENDA,CLIENTE,
		TOTALESPED = SUM(NUMSPED)
FROM STAR_SCHEMA
GROUP BY CITTA_AZIENDA,CLIENTE
), CLIENTE_SPEDIZIONI_RANKED AS
(
SELECT *,  [RANK] =  RANK() OVER (PARTITION BY CITTA_AZIENDA ORDER BY TOTALESPED DESC)
FROM CLIENTE_SPEDIZIONI
)
SELECT * 
FROM CLIENTE_SPEDIZIONI_RANKED
WHERE [RANK] = 1


-- WITH CUBE

WITH CLIENTE_SPEDIZIONI AS
(
SELECT	CITTA_AZIENDA,CLIENTE,
		TOTALESPED = SUM(NUMSPED)
FROM STAR_SCHEMA
GROUP BY CITTA_AZIENDA,CLIENTE WITH CUBE
), CLIENTE_SPEDIZIONI_RANKED AS
(
SELECT *,  [RANK] =  RANK() OVER (PARTITION BY CITTA_AZIENDA ORDER BY TOTALESPED DESC)
FROM CLIENTE_SPEDIZIONI
)
SELECT * 
FROM CLIENTE_SPEDIZIONI_RANKED
WHERE [RANK] <= 2 AND CITTA_AZIENDA IS NOT NULL AND CLIENTE IS NOT NULL


-- RITARDO
SELECT AZIENDA, DATA_ORDINE, DATA_SPED,
		MAX_RITARDO = MAX(RITARDO) OVER (PARTITION BY AZIENDA) 
FROM STAR_SCHEMA

-- Ora consideriamo per ogni AZIENDA il mese della DATA_ORDINE e calcoliamo la somma dei ritardi

SELECT	AZIENDA, YEAR(DATA_SPED) AS ANNO, MONTH(DATA_SPED) AS MESE,
		SUM(DATEDIFF(DAY, DATA_ORDINE, DATA_SPED)) AS SOMMA_RITARDI
FROM STAR_SCHEMA
GROUP BY AZIENDA, YEAR(DATA_SPED), MONTH(DATA_SPED)


SELECT	AZIENDA, MONTH(DATA_SPED) AS MESE,
		SUM(DATEDIFF(DAY, DATA_ORDINE, DATA_SPED)) AS SOMMA_RITARDI
FROM STAR_SCHEMA
GROUP BY AZIENDA, MONTH(DATA_SPED)



SELECT	AZIENDA, DATA_ORDINE, DATA_SPED, 
		DATEDIFF(DAY, DATA_ORDINE, DATA_SPED) AS RITARDO, MONTH(DATA_SPED) AS MESE,
		SUM(DATEDIFF(DAY, DATA_ORDINE, DATA_SPED)) OVER (PARTITION BY AZIENDA, MONTH(DATA_SPED)) AS SOMMA_RITARDI_MENSILI
FROM STAR_SCHEMA
ORDER BY AZIENDA, MESE


-- PATTERN CLIENTE, DATA_SPED

CREATE VIEW PATTERN_CLIENTE_DATA_SPED AS
SELECT	CLIENTE, DATA_SPED,
		-- MISURE : per semplicità si considerano sol le misure additive
		NUMSPED=SUM(NUMSPED), COSTO=SUM(COSTO)
FROM STAR_SCHEMA
GROUP BY CLIENTE, DATA_SPED


-- si analizza usando la PARTITION CLIENTE, ANNO_SPED= YEAR(DATA_SPED)

SELECT	CLIENTE, DATA_SPED, YEAR(DATA_SPED) as ANNO_SPED, NUMSPED,
		ROW_NUMBER() OVER (PARTITION BY CLIENTE, YEAR(DATA_SPED) ORDER BY NUMSPED DESC) AS RowNo
FROM PATTERN_CLIENTE_DATA_SPED


-- TOP 2 per cliente anno

CREATE VIEW TOP_2_CLIENTE_ANNO AS
SELECT CLIENTE, YEAR(DATA_SPED) AS ANNO_SPED, DATA_SPED, NUMSPED,
	ROW_NUMBER() OVER (PARTITION BY CLIENTE, YEAR(DATA_SPED) ORDER BY NUMSPED DESC) AS RowNo
FROM PATTERN_CLIENTE_DATA_SPED

SELECT * FROM TOP_2_CLIENTE_ANNO
WHERE RowNo<=2


-- Come fare queste stesse analisi rispetto al totale SUM(NUMSPED) ?
-- Non possiamo mettere SUM(NUMSPED)

-- ERRORE
SELECT CLIENTE, YEAR(DATA_SPED) as ANNO_SPED, NUMSPED,
ROW_NUMBER() OVER (PARTITION BY CLIENTE, YEAR(DATA_SPED) ORDER BY SUM(NUMSPED) DESC) AS RowNo
FROM PATTERN_CLIENTE_DATA_SPED


CREATE VIEW PATTERN_CLIENTE_ANNO_SPED AS
SELECT CLIENTE, ANNO_SPED= YEAR(DATA_SPED), NUMSPED=SUM(NUMSPED), COSTO=SUM(COSTO)
FROM STAR_SCHEMA
GROUP BY CLIENTE, YEAR(DATA_SPED)


CREATE VIEW v6 AS
SELECT CLIENTE, ANNO_SPED, NUMSPED,
ROW_NUMBER() OVER (PARTITION BY CLIENTE, ANNO_SPED ORDER BY NUMSPED DESC) AS RowNo
FROM PATTERN_CLIENTE_ANNO_SPED

SELECT * FROM v6
WHERE RowNo<=2


--- Come ottenere il totale (16 ad esempio) nella PARTITION BY CLIENTE, YEAR(DATA_SPED) ?
--- Non possiamo fare
PARTITION BY CLIENTE, YEAR(DATA_SPED) ORDER BY SUM(NUMSPED)


SELECT CLIENTE, DATA_SPED, NUMSPED,
SUM(NUMSPED) OVER (PARTITION BY CLIENTE, YEAR(DATA_SPED), MONTH(DATA_SPED) ORDER BY DATA_SPED) AS CLIENTEMonthToDate,
SUM(NUMSPED) OVER (PARTITION BY CLIENTE , YEAR(DATA_SPED) ORDER BY DATA_SPED) AS CLIENTEYearToDate,
SUM(NUMSPED) OVER (PARTITION BY CLIENTE
ORDER BY DATA_SPED) AS CLIENTECumulative,
SUM(NUMSPED) OVER (ORDER BY CLIENTE, DATA_SPED) AS Cumulative
FROM PATTERN_CLIENTE_DATA_SPED;


-- ARCO MULTIPLO
ALTER VIEW PATTERN_CLIENTE_DATA_SPED AS
SELECT CLIENTE, DATA_SPED,
		-- MISURE : per semplicità si considerano sol le misure additive
		NUMSPED=SUM(NUMSPED),
		COSTO=SUM(COSTO)
FROM STAR_SCHEMA
GROUP BY CLIENTE, DATA_SPED



--- NEI PATTERN CON ARCO MULTIPLO DEVO CONSIDERARE

NUMSPED = CASE WHEN GROUPING(SETTORE) = 1 THEN
SUM(NUMSPED_PES) ELSE SUM(NUMSPED) END ,COSTO=SUM(COSTO_PES)


--- LO PROVO NEL CASO PIù SEMPLICE
SELECT	SETTORE ,
		NUMSPED = CASE WHEN GROUPING(SETTORE) = 1 THEN SUM(NUMSPED_PES) ELSE SUM(NUMSPED) END,
		COSTO=SUM(COSTO_PES)
FROM STAR_SCHEMA
GROUP BY SETTORE WITH CUBE

-- LO APPLICO IN CASI GENERICI
CREATE VIEW CUBE_SETTORE_DATA_ordine AS
SELECT	PATTERN=GROUPING_id( SETTORE, DATA_ORDINE ),
		SETTORE = CASE WHEN GROUPING(SETTORE) = 0 THEN SETTORE ELSE 'ALL_SETTORE' END,
		DATA_ORDINE = CASE WHEN GROUPING(DATA_ORDINE) = 0 THEN DATA_ORDINE ELSE '1999-09-19' END,
		-- MISURE
		NUMSPED = CASE WHEN GROUPING(SETTORE) = 1 THEN SUM(NUMSPED_PES) ELSE SUM(NUMSPED) END,
		COSTO=SUM(COSTO_PES)
FROM STAR_SCHEMA_PD
GROUP BY SETTORE, DATA_ORDINE WITH CUBE

