

-- DIMENSION TABLE UTENTE
CREATE VIEW S_DT_UTENTE AS
SELECT 
    UTENTE_CITTA.CITTA AS UTENTE_CITTA,
    UTENTE_CITTA.REGIONE AS UTENTE_CITTA_REGIONE,
    UTENTE.UTENTE AS UTENTE,
    UTENTE_BIBLIOTECA.BIBLIOTECA AS UTENTE_BIBLIOTECA,
    UTENTE_BIBLIOTECA_CITTA.CITTA AS UTENTE_BIBLIOTECA_CITTA,
    UTENTE_BIBLIOTECA_CITTA.REGIONE AS UTENTE_BIBLIOTECA_CITTA_REGIONE
FROM 
    dbo.BIBLIOTECA AS UTENTE_BIBLIOTECA
INNER JOIN dbo.UTENTE 
    ON UTENTE_BIBLIOTECA.BIBLIOTECA = UTENTE.BIBLIOTECA
INNER JOIN dbo.CITTA AS UTENTE_CITTA 
    ON UTENTE.CITTA = UTENTE_CITTA.CITTA
INNER JOIN dbo.CITTA AS UTENTE_BIBLIOTECA_CITTA 
    ON UTENTE_BIBLIOTECA.CITTA = UTENTE_BIBLIOTECA_CITTA.CITTA;

SELECT COUNT(*) FROM UTENTE
SELECT COUNT(*) FROM S_DT_UTENTE

-- DIMENSION TABLE BIBLIOTECA
CREATE VIEW S_DT_BIBLIOTECA AS
SELECT 
    BIBLIOTECA.BIBLIOTECA AS BIBLIOTECA,
    BIBLIOTECA_CITTA.CITTA AS BIBLIOTECA_CITTA,
    BIBLIOTECA_CITTA.REGIONE AS BIBLIOTECA_CITTA_REGIONE
FROM 
    dbo.BIBLIOTECA
INNER JOIN dbo.CITTA AS BIBLIOTECA_CITTA 
    ON BIBLIOTECA.CITTA = BIBLIOTECA_CITTA.CITTA;

SELECT COUNT(*) FROM S_DT_BIBLIOTECA
SELECT COUNT(*) FROM BIBLIOTECA


-- DIMENSION TABLE BOX-RESI
ALTER VIEW S_DT_BOXRESI AS
SELECT 
    BOX_RESI.BOX_RESI AS BOX_RESI,
    BOX_RESI_BIBLIOTECA.BIBLIOTECA AS BOX_RESI_BIBLIOTECA,
    BOX_RESI_BIBLIOTECA_CITTA.CITTA AS BOX_RESI_BIBLIOTECA_CITTA,
    BOX_RESI_BIBLIOTECA_CITTA.REGIONE AS BOX_RESI_BIBLIOTECA_CITTA_REGIONE,
    BOX_RESI_CITTA.CITTA AS BOX_RESI_CITTA,
    BOX_RESI_CITTA.REGIONE AS BOX_RESI_CITTA_REGIONE
FROM 
    dbo.BIBLIOTECA AS BOX_RESI_BIBLIOTECA
INNER JOIN dbo.BOX_RESI 
    ON BOX_RESI_BIBLIOTECA.BIBLIOTECA = BOX_RESI.BIBLIOTECA
INNER JOIN dbo.CITTA AS BOX_RESI_CITTA 
    ON BOX_RESI.CITTA = BOX_RESI_CITTA.CITTA
INNER JOIN dbo.CITTA AS BOX_RESI_BIBLIOTECA_CITTA 
    ON BOX_RESI_BIBLIOTECA.CITTA = BOX_RESI_BIBLIOTECA_CITTA.CITTA

SELECT COUNT(*) FROM S_DT_BOXRESI
SELECT COUNT(*) FROM BOX_RESI

-- VISTA D'APPOGGIO
ALTER VIEW PER_FT AS
SELECT dbo.RESTITUZIONE.BOX_RESI, dbo.PRESTITO.DATA, dbo.PRESTITO.LIBRO, dbo.TESSERA.UTENTE, dbo.PRESTITO.PREZZO, dbo.PRESTITO.BIBLIOTECA, dbo.TESSERA.TESSERA
FROM     dbo.PRESTITO INNER JOIN
                  dbo.TESSERA ON dbo.PRESTITO.TESSERA = dbo.TESSERA.TESSERA LEFT JOIN
                  dbo.RESTITUZIONE ON dbo.PRESTITO.COD = dbo.RESTITUZIONE.COD AND dbo.PRESTITO.BIBLIOTECA = dbo.RESTITUZIONE.BIBLIOTECA

SELECT COUNT(*) FROM PER_FT
SELECT COUNT(*) FROM PRESTITO

-- FACT TABLE
ALTER VIEW FACT_TABLE AS
SELECT	LIBRO,DATA, UTENTE, BIBLIOTECA, COALESCE([BOX_RESI],'NO') AS BOX_RESI,
		SUM(PREZZO) AS SUM_PREZZO, COUNT(PREZZO) AS COUNT_PREZZO,
		NUM_TESSERE = COUNT(DISTINCT TESSERA)
FROM PER_FT
GROUP BY LIBRO,DATA, UTENTE, BIBLIOTECA, BOX_RESI


-- STARSCHEMA MATERIALIZZATO
CREATE SCHEMA STARSCHEMA

SELECT * INTO STARSCHEMA.FACT_TABLE FROM FACT_TABLE
SELECT * INTO STARSCHEMA.DT_UTENTE FROM S_DT_UTENTE
SELECT * INTO STARSCHEMA.DT_BOXRESI FROM S_DT_BOXRESI
SELECT * INTO STARSCHEMA.DT_BIBLIOTECA FROM S_DT_BIBLIOTECA

-- STAR SCHEMA
CREATE VIEW STARSCHEMA AS
SELECT dbo.FACT_TABLE.NUM_TESSERE, dbo.FACT_TABLE.COUNT_PREZZO, dbo.FACT_TABLE.SUM_PREZZO, dbo.S_DT_BIBLIOTECA.*,dbo.S_DT_UTENTE.*,dbo.FACT_TABLE.DATA, dbo.FACT_TABLE.LIBRO, dbo.S_DT_BOXRESI.*
FROM     dbo.FACT_TABLE INNER JOIN
                  dbo.S_DT_BIBLIOTECA ON dbo.FACT_TABLE.BIBLIOTECA = dbo.S_DT_BIBLIOTECA.BIBLIOTECA INNER JOIN
				  dbo.S_DT_UTENTE ON dbo.FACT_TABLE.UTENTE = dbo.S_DT_UTENTE.UTENTE INNER JOIN
				  dbo.S_DT_BOXRESI ON dbo.FACT_TABLE.BOX_RESI = dbo.S_DT_BOXRESI.BOX_RESI