
SELECT * FROM STARSCHEMA

-- PATTERN DELLE REGIONI



-- PATTERN REGIONE,DATA

SELECT  PATTERN = GROUPING_ID(BIBLIOTECA_CITTA_REGIONE,DATA),
		BIBLIOTECA_CITTA_REGIONE =  CASE WHEN GROUPING(BIBLIOTECA_CITTA_REGIONE) = 1 THEN 'ALL_REGIONE' ELSE BIBLIOTECA_CITTA_REGIONE END,
		DATA = CASE WHEN GROUPING(DATA) = 1 THEN 'ALL_DATA' ELSE CONVERT(CHAR(12),DATA) END,
		CASE 
			WHEN GROUPING(DATA) = 0 THEN SUM(NUM_TESSERE)
			ELSE -SUM(NUM_TESSERE)
		END AS NUM_TESSERE,
		NUM_LIBRI = COUNT(DISTINCT LIBRO)
FROM STARSCHEMA
GROUP BY BIBLIOTECA_CITTA_REGIONE, DATA WITH CUBE


-- PREZZO MEDIO
SELECT  UTENTE_CITTA_REGIONE, DATA,
		NUM_LIBRI = COUNT(DISTINCT LIBRO),
		PREZZO_MEDIO = SUM(SUM_PREZZO) / SUM(COUNT_PREZZO)
FROM STARSCHEMA
GROUP BY UTENTE_CITTA_REGIONE,DATA WITH CUBE

-- WINDOW FUNCTION
CREATE VIEW BIBLIOTECAREGIONE_DATA AS
SELECT  PATTERN = GROUPING_ID(BIBLIOTECA_CITTA_REGIONE,DATA),
		BIBLIOTECA_CITTA_REGIONE =  CASE WHEN GROUPING(BIBLIOTECA_CITTA_REGIONE) = 1 THEN 'ALL_REGIONE' ELSE BIBLIOTECA_CITTA_REGIONE END,
		DATA = CASE WHEN GROUPING(DATA) = 1 THEN 'ALL_DATA' ELSE CONVERT(CHAR(12),DATA) END,
		CASE 
			WHEN GROUPING(DATA) = 0 THEN SUM(NUM_TESSERE)
			ELSE -SUM(NUM_TESSERE)
		END AS NUM_TESSERE,
		NUM_LIBRI = COUNT(DISTINCT LIBRO)
FROM STARSCHEMA
GROUP BY BIBLIOTECA_CITTA_REGIONE, DATA WITH CUBE

SELECT	BIBLIOTECA_CITTA_REGIONE, DATA,NUM_TESSERE,
		SUM(NUM_TESSERE) OVER (PARTITION BY BIBLIOTECA_CITTA_REGIONE ORDER BY DATA) AS TOTALE_TESSERE_REGIONE_TO_DATE
FROM BIBLIOTECAREGIONE_DATA
WHERE PATTERN <> 1 AND PATTERN <> 3