

-- PATTERN {CONTRAENTE,CONVENZIONE}

CREATE VIEW PATTERN_CONTRAENTE_CONVENZIONE AS
SELECT	CONTRAENTE,CONVENZIONE,
		DURATA = AVG(DURATA),
		IMPORTO = SUM(IMPORTO),
		NUMERO = COUNT(*),
		NUM_CONTRAENTI = COUNT(DISTINCT CONTRAENTE),
		NUM_COMMITTENTI = CASE WHEN GROUPING(CONTRAENTE) = 1 OR GROUPING(CONVENZIONE) = 1 THEN 9999 ELSE SUM(NUM_COMMITTENTI) END,
		NUM_ISTITUZIONI = CASE WHEN GROUPING(CONTRAENTE) = 1 OR GROUPING(CONVENZIONE) = 1 THEN 9999 ELSE SUM(NUM_ISTITUZIONI) END
FROM STARSCHEMA
GROUP BY CONTRAENTE,CONVENZIONE WITH CUBE


