

-- DIMENSION TABLE COMMITTENTE CITTA
CREATE VIEW DT_COMMITTENTE_CITTA AS
SELECT * 
FROM CITTA

SELECT COUNT(*) FROM CITTA
SELECT COUNT(*) FROM DT_COMMITTENTE_CITTA


-- DIMENSION TABLE CONTRAENTE
CREATE VIEW DT_CONTRAENTE AS
SELECT 
    CONTRAENTE.PERSONA AS CONTRAENTE,
    CONTRAENTE.TITOLO_DI_STUDIO AS CONTRAENTE_TITOLODISTUDIO,
    CONTRAENTE_CITTA.CITTÀ AS CONTRAENTE_CITTA,
    CONTRAENTE_CITTA.STATO AS CONTRAENTE_CITTA_STATO
FROM dbo.CITTA AS CONTRAENTE_CITTA 
INNER JOIN dbo.PERSONA AS CONTRAENTE 
    ON CONTRAENTE_CITTA.CITTÀ = CONTRAENTE.RESIDENZA

SELECT COUNT(*) FROM DT_CONTRAENTE
SELECT COUNT(*) FROM PERSONA

-- DIMENSION TABLE CONVENZIONE
CREATE VIEW DT_CONVENZIONE AS
SELECT 
    dbo.CONVENZIONE.CONVENZIONE AS CONVENZIONE,
    dbo.CONVENZIONE.GENERE AS CONVENZIONE_GENERE,
    CONVENZIONE_ISTITUZIONE_CITTA.CITTÀ AS CONVENZIONE_ISTITUZIONE_CITTA,
    CONVENZIONE_ISTITUZIONE_CITTA.STATO AS CONVENZIONE_ISTITUZIONE_STATO,
    CONVENZIONE_ISTITUZIONE.ISTITUZIONE AS CONVENZIONE_ISTITUZIONE,
    CONVENZIONE_ISTITUZIONE_DIRETTORE.PERSONA AS CONVENZIONE_ISTITUZIONE_DIRETTORE,
    CONVENZIONE_ISTITUZIONE_DIRETTORE.TITOLO_DI_STUDIO AS CONVENZIONE_ISTITUZIONE_DIRETTORE_TITOLODISTUDIO,
    CONVENZIONE_ISTITUZIONE_DIRETTORE_CITTA.CITTÀ AS CONVENZIONE_ISTITUZIONE_DIRETTORE_CITTA,
    CONVENZIONE_ISTITUZIONE_DIRETTORE_CITTA.STATO AS CONVENZIONE_ISTITUZIONE_DIRETTORE_CITTA_STATO
FROM dbo.PERSONA AS CONVENZIONE_ISTITUZIONE_DIRETTORE 
INNER JOIN dbo.CITTA AS CONVENZIONE_ISTITUZIONE_DIRETTORE_CITTA 
    ON CONVENZIONE_ISTITUZIONE_DIRETTORE.RESIDENZA = CONVENZIONE_ISTITUZIONE_DIRETTORE_CITTA.CITTÀ 
INNER JOIN dbo.CONVENZIONE 
INNER JOIN dbo.ISTITUZIONE AS CONVENZIONE_ISTITUZIONE 
    ON dbo.CONVENZIONE.ISTITUZIONE = CONVENZIONE_ISTITUZIONE.ISTITUZIONE 
    ON CONVENZIONE_ISTITUZIONE_DIRETTORE.PERSONA = CONVENZIONE_ISTITUZIONE.DIRETTORE 
INNER JOIN dbo.CITTA AS CONVENZIONE_ISTITUZIONE_CITTA 
    ON CONVENZIONE_ISTITUZIONE.SEDE_LEGALE = CONVENZIONE_ISTITUZIONE_CITTA.CITTÀ

SELECT COUNT(*) FROM CONVENZIONE
SELECT COUNT(*) FROM DT_CONVENZIONE


-- FACT TABLE CONTRATTO
CREATE VIEW FACT_TABLE AS
SELECT	dbo.CONTRATTO.CONVENZIONE, 
		dbo.CONTRATTO.CONTRAENTE, 
		dbo.PERSONA.RESIDENZA AS COMMITTENTE_CITTA, 
		dbo.CONTRATTO.ANNO, 
		dbo.CONTRATTO.TIPO, 
		dbo.CONTRATTO.DURATA, 
		dbo.CONTRATTO.IMPORTO
FROM     dbo.CONTRATTO INNER JOIN
                  dbo.PERSONA ON dbo.CONTRATTO.COMMITTENTE = dbo.PERSONA.PERSONA

SELECT COUNT(*) FROM CONTRATTO
SELECT COUNT(*) FROM FACT_TABLE


-- STAR SCHEMA VIRTUALE
ALTER VIEW STARSCHEMA AS
SELECT dbo.FACT_TABLE.TIPO, dbo.FACT_TABLE.DURATA, dbo.FACT_TABLE.IMPORTO, dbo.FACT_TABLE.ANNO, dbo.DT_CONVENZIONE.*, dbo.DT_CONTRAENTE.*, dbo.FACT_TABLE.COMMITTENTE_CITTA, 
                  dbo.DT_COMMITTENTE_CITTA.STATO AS COMMITTENTE_CITTA_STATO,
				  NUM_COMMITTENTI = 1, NUM_ISTITUZIONI = 1
FROM     dbo.DT_COMMITTENTE_CITTA INNER JOIN
                  dbo.FACT_TABLE INNER JOIN
                  dbo.DT_CONVENZIONE ON dbo.FACT_TABLE.CONVENZIONE = dbo.DT_CONVENZIONE.CONVENZIONE INNER JOIN
                  dbo.DT_CONTRAENTE ON dbo.FACT_TABLE.CONTRAENTE = dbo.DT_CONTRAENTE.CONTRAENTE ON dbo.DT_COMMITTENTE_CITTA.CITTÀ = dbo.FACT_TABLE.COMMITTENTE_CITTA

SELECT COUNT(*) FROM STARSCHEMA