


-- NA {AA, LABORATORIO_DIPARTIMENTO, DIPARTIMENTO_CITTA}

CREATE VIEW PATTERN_AA_LABDIP_DIPCITTA AS
SELECT	AA, LABORATORIO_DIPARTIMENTO, DIPARTIMENTO_CITTA,
		CFU_MEDIO = SUM(SOMMA_CFU) / SUM(COUNT_CFU),
		NUM_INSEGNAMENTI = CASE WHEN GROUPING(AA) = 1 THEN -1 ELSE SUM(NUM_INSEGNAMENTI) END,
		NUM_ESERCITATORI = CASE WHEN GROUPING(AA) = 1 THEN -1 ELSE SUM(NUM_ESERCITATORE) END
FROM STARSCHEMA
GROUP BY AA, LABORATORIO_DIPARTIMENTO, DIPARTIMENTO_CITTA WITH CUBE

-- NUM_ESERCITATORI NON CALCOLABILE, MANCA DELLE DIMENSIONI NEL PATTERN
-- CONTROLLO
SELECT AA, LABORATORIO_DIPARTIMENTO, DIPARTIMENTO_CITTA,NUM_ESERCITATORI
FROM PATTERN_AA_LABDIP_DIPCITTA
WHERE AA IS NOT NULL AND LABORATORIO_DIPARTIMENTO IS NOT NULL AND DIPARTIMENTO_CITTA IS NOT NULL

SELECT	AA,COD_CDL_INSEGNAMENTO,CF_TITOLARE, COD_LAB,
		NUM_ESERCITATORI = COUNT(DISTINCT CF_ESERCITATORE)
FROM PER_FT
GROUP BY AA,COD_CDL_INSEGNAMENTO,CF_TITOLARE, COD_LAB 


-- WINDOW FUNCTION
SELECT	AA,LABORATORIO_DIPARTIMENTO,DIPARTIMENTO_CITTA, CFU_MEDIO, NUM_INSEGNAMENTI,
		SUM(CFU_MEDIO) OVER (PARTITION BY LABORATORIO_DIPARTIMENTO) AS TOTALE_CFU_PER_DIP
FROM PATTERN_AA_LABDIP_DIPCITTA
WHERE AA IS NOT NULL AND LABORATORIO_DIPARTIMENTO IS NOT NULL AND DIPARTIMENTO_CITTA IS NOT NULL

SELECT	AA,LABORATORIO_DIPARTIMENTO,DIPARTIMENTO_CITTA, CFU_MEDIO, NUM_INSEGNAMENTI,
		RANK() OVER (PARTITION BY LABORATORIO_DIPARTIMENTO ORDER BY CFU_MEDIO) AS [RANK]
FROM PATTERN_AA_LABDIP_DIPCITTA
WHERE AA IS NOT NULL AND LABORATORIO_DIPARTIMENTO IS NOT NULL AND DIPARTIMENTO_CITTA IS NOT NULL