

-- DIMENSION TABLE DT_DOCENTE
ALTER VIEW DT_DOCENTE AS
SELECT 
    dbo.DOCENTE.CF AS DOCENTE,
    dbo.DOCENTE.RUOLO AS DOCENTE_RUOLO,
    DOCENTE_CDL.CDL AS DOCENTE_CDL,
    DOCENTE_CDL.TIPO AS DOCENTE_CDL_TIPO,
    DOCENTE_CITTA.CITTA AS DOCENTE_CITTA,
    DOCENTE_CITTA.REGIONE AS DOCENTE_CITTA_REGIONE,
    COALESCE(dbo.RICERCATORE.ETA,-1) AS DOCENTE_ETA
FROM dbo.DOCENTE
INNER JOIN dbo.CORSODILAUREA AS DOCENTE_CDL 
    ON dbo.DOCENTE.COD_CDL = DOCENTE_CDL.CDL
INNER JOIN dbo.CITTA AS DOCENTE_CITTA 
    ON dbo.DOCENTE.RESIDENZA = DOCENTE_CITTA.CITTA
LEFT OUTER JOIN dbo.RICERCATORE 
    ON dbo.DOCENTE.CF = dbo.RICERCATORE.CF;

SELECT COUNT(*) FROM DOCENTE
SELECT COUNT(*) FROM DT_DOCENTE


-- DIMENSION TABLE COD_LAB
ALTER VIEW DT_COD_LAB AS
SELECT 
    LABORATORIO.LAB AS LABORATORIO,
    LABORATORIO_DIPARTIMENTO.DIP AS LABORATORIO_DIPARTIMENTO,
    RESPONSABILE.CF AS RESPONSABILE,
    RESPONSABILE.NOME AS RESPONSABILE_NOME,
    RESPONSABILE.RUOLO AS RESPONSABILE_RUOLO,
    COALESCE(RESPONSABILE_RICERCATORE.ETA,-1) AS RESPONSABILE_ETA,
    LABORATORIO_DIPARTIMENTO_CITTA.CITTA AS DIPARTIMENTO_CITTA,
    LABORATORIO_DIPARTIMENTO_CITTA.REGIONE AS DIPARTIMENTO_CITTA_REGIONE,
    DIRETTORE.CF AS DIRETTORE,
    DIRETTORE.NOME AS DIRETTORE_NOME,
    DIRETTORE.RUOLO AS DIRETTORE_RUOLO,
    DIRETTORE_CDL.CDL AS DIRETTORE_CDL,
    DIRETTORE_CDL.TIPO AS DIRETTORE_CDL_TIPO,
    COALESCE(DIRETTORE_RICERCATORE.ETA,-1) AS DIRETTORE_ETA,
    DIRETTORE_CITTA.CITTA AS DIRETTORE_CITTA,
    DIRETTORE_CITTA.REGIONE AS DIRETTORE_CITTA_REGIONE,
    RESPONSABILE_CITTA.CITTA AS RESPONSABILE_CITTA,
    RESPONSABILE_CITTA.REGIONE AS RESPONSABILE_CITTA_REGIONE,
    RESPONSABILE_CDL.CDL AS RESPONSABILE_CDL,
    RESPONSABILE_CDL.TIPO AS RESPONSABILE_TIPO
FROM dbo.LABORATORIO
INNER JOIN dbo.DIPARTIMENTO AS LABORATORIO_DIPARTIMENTO 
    ON dbo.LABORATORIO.COD_DIP = LABORATORIO_DIPARTIMENTO.DIP
INNER JOIN dbo.DOCENTE AS RESPONSABILE 
    ON dbo.LABORATORIO.CF_RESPONSABILE = RESPONSABILE.CF
INNER JOIN dbo.CITTA AS LABORATORIO_DIPARTIMENTO_CITTA 
    ON LABORATORIO_DIPARTIMENTO.SEDE = LABORATORIO_DIPARTIMENTO_CITTA.CITTA
INNER JOIN dbo.CORSODILAUREA AS RESPONSABILE_CDL 
    ON RESPONSABILE.COD_CDL = RESPONSABILE_CDL.CDL
INNER JOIN dbo.CITTA AS RESPONSABILE_CITTA 
    ON RESPONSABILE.RESIDENZA = RESPONSABILE_CITTA.CITTA
INNER JOIN dbo.DOCENTE AS DIRETTORE 
    ON LABORATORIO_DIPARTIMENTO.CF_DIRETTORE = DIRETTORE.CF
INNER JOIN dbo.CITTA AS DIRETTORE_CITTA 
    ON DIRETTORE.RESIDENZA = DIRETTORE_CITTA.CITTA
INNER JOIN dbo.CORSODILAUREA AS DIRETTORE_CDL 
    ON DIRETTORE.COD_CDL = DIRETTORE_CDL.CDL
LEFT OUTER JOIN dbo.RICERCATORE AS DIRETTORE_RICERCATORE 
    ON DIRETTORE.CF = DIRETTORE_RICERCATORE.CF
LEFT OUTER JOIN dbo.RICERCATORE AS RESPONSABILE_RICERCATORE 
    ON RESPONSABILE.CF = RESPONSABILE_RICERCATORE.CF
UNION 
SELECT	'NO_LAB','NO_LAB','NO_LAB','NO_LAB','NO_LAB',9999,'NO_LAB','NO_LAB','NO_LAB','NO_LAB','NO_LAB','NO_LAB','NO_LAB',9999,
		'NO_LAB','NO_LAB','NO_LAB','NO_LAB','NO_LAB','NO_LAB'


SELECT COUNT(*) FROM LABORATORIO
SELECT COUNT(*) FROM DT_COD_LAB

-- DIMENSION TABLE CDL
CREATE VIEW DT_CDL AS
SELECT CDL, TIPO
FROM	dbo.CORSODILAUREA
UNION 
SELECT 'NO_CDL','NO_CDL'


-- VISTA APPOGGIO
ALTER VIEW PER_FT AS
SELECT dbo.DOCENZA.AA, dbo.DOCENZA.COD_INS, dbo.DOCENZA.CFU, COALESCE(dbo.ESERCITAZIONI.COD_LAB,'NO_LAB') AS COD_LAB, dbo.DOCENZA.CF_TITOLARE, dbo.ESERCITAZIONI.CF_ESERCITATORE, dbo.INSEGNAMENTO.COD_CDL AS COD_CDL_INSEGNAMENTO, 
                  COALESCE(dbo.DOCENTE.COD_CDL,'NO_CDL') AS COD_CDL_ESERCITATORE
FROM     dbo.ESERCITAZIONI INNER JOIN 
                  dbo.LABORATORIO ON dbo.ESERCITAZIONI.COD_LAB = dbo.LABORATORIO.LAB INNER JOIN
                  dbo.DOCENTE ON dbo.LABORATORIO.CF_RESPONSABILE = dbo.DOCENTE.CF RIGHT OUTER JOIN
                  dbo.DOCENZA INNER JOIN
                  dbo.INSEGNAMENTO ON dbo.DOCENZA.COD_INS = dbo.INSEGNAMENTO.COD_INS ON dbo.ESERCITAZIONI.AA = dbo.DOCENZA.AA AND dbo.ESERCITAZIONI.COD_INS = dbo.DOCENZA.COD_INS

SELECT COUNT(*) FROM PER_FT
SELECT COUNT(*) FROM DOCENZA

SELECT * FROM PER_FT

-- FACT TABLE
CREATE VIEW FACT_TABLE AS
SELECT	AA,COD_CDL_INSEGNAMENTO,CF_TITOLARE,COD_CDL_ESERCITATORE,COD_LAB,
		SOMMA_CFU = SUM(CFU), COUNT_CFU = COUNT(CFU),
		NUM_INSEGNAMENTI = COUNT(DISTINCT COD_INS),
		NUM_ESERCITATORE = COUNT(DISTINCT CF_ESERCITATORE)
FROM PER_FT
GROUP BY AA,COD_CDL_INSEGNAMENTO,CF_TITOLARE,COD_CDL_ESERCITATORE,COD_LAB


-- STAR SCHEMA VIRTUALE
CREATE VIEW STARSCHEMA AS
SELECT dbo.FACT_TABLE.AA, dbo.DT_DOCENTE.*, dbo.FACT_TABLE.SOMMA_CFU, dbo.FACT_TABLE.COUNT_CFU, dbo.FACT_TABLE.NUM_INSEGNAMENTI, dbo.FACT_TABLE.NUM_ESERCITATORE, 
                  dbo.FACT_TABLE.COD_CDL_ESERCITATORE, DT_CDL_1.TIPO AS COD_CDL_ESERCITATORE_TIPO, dbo.DT_CDL.TIPO AS COD_CDL_INSEGNAMENTO_TIPO, dbo.FACT_TABLE.COD_CDL_INSEGNAMENTO, dbo.DT_COD_LAB.*
FROM     dbo.DT_CDL AS DT_CDL_1 INNER JOIN
                  dbo.FACT_TABLE INNER JOIN
                  dbo.DT_DOCENTE ON dbo.FACT_TABLE.CF_TITOLARE = dbo.DT_DOCENTE.DOCENTE ON DT_CDL_1.CDL = dbo.FACT_TABLE.COD_CDL_ESERCITATORE INNER JOIN
                  dbo.DT_CDL ON dbo.FACT_TABLE.COD_CDL_INSEGNAMENTO = dbo.DT_CDL.CDL INNER JOIN
                  dbo.DT_COD_LAB ON dbo.FACT_TABLE.COD_LAB = dbo.DT_COD_LAB.LABORATORIO

SELECT * FROM STARSCHEMA
