

-- DIMENSION TABLE CONTO
CREATE VIEW DT_CONTO AS
SELECT *
FROM CONTO


-- DIMENSION TABLE CLIENTE
CREATE VIEW DT_CLIENTE AS
SELECT * 
FROM CLIENTE

-- DIMENSION TABLE CITTA
ALTER VIEW DT_CITTA AS 
SELECT * 
FROM CITTA


-- DIMENSION TABLE BANCA
CREATE VIEW DT_BANCA AS
SELECT *
FROM BANCA


-- VISTA APPOGGIO
ALTER VIEW PER_FT AS
SELECT dbo.TRASFERIMENTO.DA_CONTO, dbo.CONTO.BANCA AS A_BANCA, dbo.TRASFERIMENTO.A_CONTO, dbo.TRASFERIMENTO.IMPORTO, dbo.TRASFERIMENTO.DATA, COALESCE(dbo.TRASFERIMENTO_ESTERO.BANCA_ESTERA,'NO') AS BANCA_ESTERA
FROM     dbo.CONTO INNER JOIN
                  dbo.TRASFERIMENTO ON dbo.CONTO.CONTO = dbo.TRASFERIMENTO.A_CONTO LEFT OUTER JOIN
                  dbo.TRASFERIMENTO_ESTERO ON dbo.TRASFERIMENTO.NUM_TRASF = dbo.TRASFERIMENTO_ESTERO.NUM_TRASF

SELECT COUNT(*) FROM TRASFERIMENTO
SELECT COUNT(*) FROM PER_FT

-- FACT TABLE
CREATE VIEW FACT_TABLE AS
SELECT	DATA,BANCA_ESTERA, A_BANCA, DA_CONTO,
		SUM(IMPORTO) AS IMPORTO_SOMMA, COUNT(IMPORTO) AS COUNT_IMPORTO,
		NUM_A_CONTO = COUNT(DISTINCT A_CONTO)
FROM PER_FT
GROUP BY DATA,BANCA_ESTERA, A_BANCA, DA_CONTO

SELECT COUNT(*) FROM FACT_TABLE

-- SNOWFLAKE MATERIALIZZATO
DROP SCHEMA IF EXISTS SNOWFLAKE
CREATE SCHEMA SNOWFLAKE

SELECT * INTO SNOWFLAKE.FACT_TABLE_PD FROM FACT_TABLE_PD
SELECT * INTO SNOWFLAKE.DT_CONTO FROM DT_CONTO
SELECT * INTO SNOWFLAKE.DT_BANCA FROM DT_BANCA
SELECT * INTO SNOWFLAKE.DT_BANCA_ESTERA FROM DT_BANCA_ESTERA
SELECT * INTO SNOWFLAKE.DT_CLIENTE FROM DT_CLIENTE
SELECT * INTO SNOWFLAKE.DT_FONDO FROM DT_FONDO
SELECT * INTO SNOWFLAKE.DT_CITTA FROM DT_CITTA


-- SNOWFLAKE VIRTUALE
CREATE VIEW SNOWFLAKE AS
SELECT 
    FACT_TABLE_PD.DA_CONTO AS DA_CONTO,
    DA_CONTO_CLIENTE.CLIENTE AS DA_CONTO_CLIENTE_CLIENTE,
    DA_CONTO_CLIENTE.MASSIMO_SCOPERTO_GIORNALIERO AS DA_CONTO_CLIENTE_MASSIMO_SCOPERTO_GIORNALIERO,
    DA_CONTO_CLIENTE_CITTA.CITTA AS DA_CONTO_CLIENTE_CITTA_CITTA,
    DA_CONTO_CLIENTE_CITTA.REGIONE AS DA_CONTO_CLIENTE_CITTA_REGIONE,
    DA_CONTO_BANCA_CITTA.CITTA AS DA_CONTO_BANCA_CITTA_CITTA,
    DA_CONTO_BANCA_CITTA.REGIONE AS DA_CONTO_BANCA_CITTA_REGIONE,
    FACT_TABLE_PD.NUM_A_CONTO_P AS NUM_A_CONTO_P,
    FACT_TABLE_PD.IMPORTO_SOMMA_P AS IMPORTO_SOMMA_P,
    FACT_TABLE_PD.COUNT_IMPORTO_P AS COUNT_IMPORTO_P,
    FACT_TABLE_PD.NUM_A_CONTO AS NUM_A_CONTO,
    FACT_TABLE_PD.A_BANCA AS A_BANCA,
    DA_CONTO_BANCA.BANCA AS DA_CONTO_BANCA_BANCA,
    FACT_TABLE_PD.BANCA_ESTERA AS BANCA_ESTERA,
    FACT_TABLE_PD.DATA AS DATA,
    FONDO.FONDO AS FONDO_FONDO,
    FONDO.TIPO AS FONDO_TIPO
FROM dbo.BANCA AS BANCA_ESTERA
INNER JOIN dbo.CITTA AS BANCA_ESTERA_CITTA 
    ON BANCA_ESTERA.CITTA = BANCA_ESTERA_CITTA.CITTA
INNER JOIN dbo.DT_BANCA AS DA_CONTO_BANCA 
    ON DA_CONTO_BANCA.BANCA = BANCA_ESTERA.BANCA
INNER JOIN dbo.CITTA AS DA_CONTO_BANCA_CITTA 
    ON DA_CONTO_BANCA.CITTA = DA_CONTO_BANCA_CITTA.CITTA
INNER JOIN dbo.FACT_TABLE_PD 
    ON FACT_TABLE_PD.BANCA_ESTERA = BANCA_ESTERA.BANCA
INNER JOIN dbo.DT_FONDO AS FONDO 
    ON FACT_TABLE_PD.FONDO = FONDO.FONDO
INNER JOIN dbo.DT_CONTO AS DA_CONTO 
    ON FACT_TABLE_PD.DA_CONTO = DA_CONTO.CONTO
INNER JOIN dbo.DT_CLIENTE AS DA_CONTO_CLIENTE 
    ON DA_CONTO.CLIENTE = DA_CONTO_CLIENTE.CLIENTE
INNER JOIN dbo.CITTA AS DA_CONTO_CLIENTE_CITTA 
    ON DA_CONTO_CLIENTE.CITTA = DA_CONTO_CLIENTE_CITTA.CITTA
INNER JOIN dbo.BANCA AS A_BANCA 
    ON FACT_TABLE_PD.A_BANCA = A_BANCA.BANCA
INNER JOIN dbo.DT_CITTA AS A_BANCA_CITTA 
    ON A_BANCA.CITTA = A_BANCA_CITTA.CITTA;


-- ARCO MULTIPLO

-- DIMENSION TABLE FONDO
ALTER VIEW DT_FONDO AS
SELECT *
FROM FONDO


-- FACT TABLE PUSHDOWN
CREATE VIEW FACT_TABLE_PD AS
SELECT	dbo.INVESTE.FONDO, dbo.FACT_TABLE.DATA, dbo.FACT_TABLE.BANCA_ESTERA, dbo.FACT_TABLE.A_BANCA, dbo.FACT_TABLE.DA_CONTO,
		IMPORTO_SOMMA_P = PESO * IMPORTO_SOMMA,
		COUNT_IMPORTO_P = PESO * COUNT_IMPORTO,
		NUM_A_CONTO_P = PESO * NUM_A_CONTO,
		NUM_A_CONTO
FROM     dbo.FACT_TABLE INNER JOIN
                  dbo.INVESTE ON dbo.FACT_TABLE.DA_CONTO = dbo.INVESTE.CONTO


