SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [BANCA](
	[BANCA] [varchar](10) NOT NULL,
	[CITTA] [varchar](10) NULL,
 CONSTRAINT [PK_BANCA] PRIMARY KEY CLUSTERED 
(
	[BANCA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CITTA](
	[CITTA] [varchar](10) NOT NULL,
	[REGIONE] [varchar](10) NULL,
 CONSTRAINT [PK_CITTA] PRIMARY KEY CLUSTERED 
(
	[CITTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CLIENTE](
	[CLIENTE] [varchar](10) NOT NULL,
	[CITTA] [varchar](10) NULL,
	[MASSIMO_SCOPERTO_GIORNALIERO] [int] NULL,
 CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CONTO](
	[CONTO] [varchar](10) NOT NULL,
	[BANCA] [varchar](10) NULL,
	[CLIENTE] [varchar](10) NULL,
 CONSTRAINT [PK_CONTO] PRIMARY KEY CLUSTERED 
(
	[CONTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [FONDO](
	[FONDO] [varchar](10) NOT NULL,
	[TIPO] [varchar](10) NULL,
 CONSTRAINT [PK_FONDO] PRIMARY KEY CLUSTERED 
(
	[FONDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [INVESTE](
	[CONTO] [varchar](10) NOT NULL,
	[FONDO] [varchar](10) NOT NULL,
	[PESO] [decimal](4, 2) NULL,
 CONSTRAINT [PK_INVESTE] PRIMARY KEY CLUSTERED 
(
	[CONTO] ASC,
	[FONDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TRASFERIMENTO](
	[NUM_TRASF] [int] NOT NULL,
	[DA_CONTO] [varchar](10) NULL,
	[A_CONTO] [varchar](10) NULL,
	[IMPORTO] [decimal](18, 4) NULL,
	[DATA] [smalldatetime] NULL,
 CONSTRAINT [PK_TRASFERIMENTO] PRIMARY KEY CLUSTERED 
(
	[NUM_TRASF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [TRASFERIMENTO_ESTERO](
	[NUM_TRASF] [int] NOT NULL,
	[BANCA_ESTERA] [varchar](10) NULL,
 CONSTRAINT [PK_TRASFERIMENTO_ESTERO] PRIMARY KEY CLUSTERED 
(
	[NUM_TRASF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [BANCA] ([BANCA], [CITTA]) VALUES (N'K', N'CH')
GO
INSERT [BANCA] ([BANCA], [CITTA]) VALUES (N'no', N'no')
GO
INSERT [BANCA] ([BANCA], [CITTA]) VALUES (N'P', N'RE')
GO
INSERT [BANCA] ([BANCA], [CITTA]) VALUES (N'Q', N'RE')
GO
INSERT [BANCA] ([BANCA], [CITTA]) VALUES (N'R', N'RE')
GO
INSERT [CITTA] ([CITTA], [REGIONE]) VALUES (N'CH', N'CH')
GO
INSERT [CITTA] ([CITTA], [REGIONE]) VALUES (N'MO', N'ER')
GO
INSERT [CITTA] ([CITTA], [REGIONE]) VALUES (N'no', N'no')
GO
INSERT [CITTA] ([CITTA], [REGIONE]) VALUES (N'RE', N'ER')
GO
INSERT [CLIENTE] ([CLIENTE], [CITTA], [MASSIMO_SCOPERTO_GIORNALIERO]) VALUES (N'A', N'MO', 10)
GO
INSERT [CLIENTE] ([CLIENTE], [CITTA], [MASSIMO_SCOPERTO_GIORNALIERO]) VALUES (N'B', N'MO', 10)
GO
INSERT [CLIENTE] ([CLIENTE], [CITTA], [MASSIMO_SCOPERTO_GIORNALIERO]) VALUES (N'C', N'MO', 10)
GO
INSERT [CLIENTE] ([CLIENTE], [CITTA], [MASSIMO_SCOPERTO_GIORNALIERO]) VALUES (N'no', N'no', NULL)
GO
INSERT [CONTO] ([CONTO], [BANCA], [CLIENTE]) VALUES (N'A1P', N'P', N'A')
GO
INSERT [CONTO] ([CONTO], [BANCA], [CLIENTE]) VALUES (N'A2Q', N'Q', N'A')
GO
INSERT [CONTO] ([CONTO], [BANCA], [CLIENTE]) VALUES (N'B1P', N'P', N'B')
GO
INSERT [CONTO] ([CONTO], [BANCA], [CLIENTE]) VALUES (N'B2Q', N'Q', N'B')
GO
INSERT [CONTO] ([CONTO], [BANCA], [CLIENTE]) VALUES (N'C1R', N'R', N'C')
GO
INSERT [CONTO] ([CONTO], [BANCA], [CLIENTE]) VALUES (N'C2Q', N'Q', N'C')
GO
INSERT [CONTO] ([CONTO], [BANCA], [CLIENTE]) VALUES (N'no', N'no', N'no')
GO
INSERT [FONDO] ([FONDO], [TIPO]) VALUES (N'F2', N'A2')
GO
INSERT [FONDO] ([FONDO], [TIPO]) VALUES (N'F3', N'A4')
GO
INSERT [FONDO] ([FONDO], [TIPO]) VALUES (N'no', N'no')
GO
INSERT [INVESTE] ([CONTO], [FONDO], [PESO]) VALUES (N'A1P', N'F2', CAST(0.30 AS Decimal(4, 2)))
GO
INSERT [INVESTE] ([CONTO], [FONDO], [PESO]) VALUES (N'A1P', N'F3', CAST(0.70 AS Decimal(4, 2)))
GO
INSERT [INVESTE] ([CONTO], [FONDO], [PESO]) VALUES (N'A2Q', N'F2', CAST(1.00 AS Decimal(4, 2)))
GO
INSERT [INVESTE] ([CONTO], [FONDO], [PESO]) VALUES (N'B1P', N'F2', CAST(1.00 AS Decimal(4, 2)))
GO
INSERT [INVESTE] ([CONTO], [FONDO], [PESO]) VALUES (N'B2Q', N'F2', CAST(1.00 AS Decimal(4, 2)))
GO
INSERT [INVESTE] ([CONTO], [FONDO], [PESO]) VALUES (N'C1R', N'F2', CAST(1.00 AS Decimal(4, 2)))
GO
INSERT [INVESTE] ([CONTO], [FONDO], [PESO]) VALUES (N'C2Q', N'F2', CAST(1.00 AS Decimal(4, 2)))
GO
INSERT [INVESTE] ([CONTO], [FONDO], [PESO]) VALUES (N'no', N'no', CAST(1.00 AS Decimal(4, 2)))
GO
INSERT [TRASFERIMENTO] ([NUM_TRASF], [DA_CONTO], [A_CONTO], [IMPORTO], [DATA]) VALUES (1, N'B1P', N'A1P', CAST(20.0000 AS Decimal(18, 4)), CAST(N'2016-02-01T00:00:00' AS SmallDateTime))
GO
INSERT [TRASFERIMENTO] ([NUM_TRASF], [DA_CONTO], [A_CONTO], [IMPORTO], [DATA]) VALUES (2, N'A2Q', N'B1P', CAST(10.0000 AS Decimal(18, 4)), CAST(N'2016-02-01T00:00:00' AS SmallDateTime))
GO
INSERT [TRASFERIMENTO] ([NUM_TRASF], [DA_CONTO], [A_CONTO], [IMPORTO], [DATA]) VALUES (3, N'A1P', N'A2Q', CAST(10.0000 AS Decimal(18, 4)), CAST(N'2016-03-01T00:00:00' AS SmallDateTime))
GO
INSERT [TRASFERIMENTO] ([NUM_TRASF], [DA_CONTO], [A_CONTO], [IMPORTO], [DATA]) VALUES (4, N'A2Q', N'C1R', CAST(10.0000 AS Decimal(18, 4)), CAST(N'2016-03-01T00:00:00' AS SmallDateTime))
GO
INSERT [TRASFERIMENTO] ([NUM_TRASF], [DA_CONTO], [A_CONTO], [IMPORTO], [DATA]) VALUES (5, N'B2Q', N'C2Q', CAST(10.0000 AS Decimal(18, 4)), CAST(N'2016-03-01T00:00:00' AS SmallDateTime))
GO
INSERT [TRASFERIMENTO_ESTERO] ([NUM_TRASF], [BANCA_ESTERA]) VALUES (2, N'K')
GO
INSERT [TRASFERIMENTO_ESTERO] ([NUM_TRASF], [BANCA_ESTERA]) VALUES (4, N'K')
GO
ALTER TABLE [BANCA]  WITH CHECK ADD  CONSTRAINT [FK_BANCA_CITTA] FOREIGN KEY([CITTA])
REFERENCES [CITTA] ([CITTA])
GO
ALTER TABLE [BANCA] CHECK CONSTRAINT [FK_BANCA_CITTA]
GO
ALTER TABLE [CLIENTE]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_CITTA] FOREIGN KEY([CITTA])
REFERENCES [CITTA] ([CITTA])
GO
ALTER TABLE [CLIENTE] CHECK CONSTRAINT [FK_CLIENTE_CITTA]
GO
ALTER TABLE [CONTO]  WITH CHECK ADD  CONSTRAINT [FK_CONTO_BANCA] FOREIGN KEY([BANCA])
REFERENCES [BANCA] ([BANCA])
GO
ALTER TABLE [CONTO] CHECK CONSTRAINT [FK_CONTO_BANCA]
GO
ALTER TABLE [CONTO]  WITH CHECK ADD  CONSTRAINT [FK_CONTO_CLIENTE] FOREIGN KEY([CLIENTE])
REFERENCES [CLIENTE] ([CLIENTE])
GO
ALTER TABLE [CONTO] CHECK CONSTRAINT [FK_CONTO_CLIENTE]
GO
ALTER TABLE [INVESTE]  WITH CHECK ADD  CONSTRAINT [FK_INVESTE_CONTO] FOREIGN KEY([CONTO])
REFERENCES [CONTO] ([CONTO])
GO
ALTER TABLE [INVESTE] CHECK CONSTRAINT [FK_INVESTE_CONTO]
GO
ALTER TABLE [INVESTE]  WITH CHECK ADD  CONSTRAINT [FK_INVESTE_FONDO] FOREIGN KEY([FONDO])
REFERENCES [FONDO] ([FONDO])
GO
ALTER TABLE [INVESTE] CHECK CONSTRAINT [FK_INVESTE_FONDO]
GO
ALTER TABLE [TRASFERIMENTO]  WITH CHECK ADD  CONSTRAINT [FK_TRASFERIMENTO_CONTO] FOREIGN KEY([DA_CONTO])
REFERENCES [CONTO] ([CONTO])
GO
ALTER TABLE [TRASFERIMENTO] CHECK CONSTRAINT [FK_TRASFERIMENTO_CONTO]
GO
ALTER TABLE [TRASFERIMENTO]  WITH CHECK ADD  CONSTRAINT [FK_TRASFERIMENTO_CONTO1] FOREIGN KEY([A_CONTO])
REFERENCES [CONTO] ([CONTO])
GO
ALTER TABLE [TRASFERIMENTO] CHECK CONSTRAINT [FK_TRASFERIMENTO_CONTO1]
GO
ALTER TABLE [TRASFERIMENTO_ESTERO]  WITH CHECK ADD  CONSTRAINT [FK_TRASFERIMENTO_ESTERO_BANCA] FOREIGN KEY([BANCA_ESTERA])
REFERENCES [BANCA] ([BANCA])
GO
ALTER TABLE [TRASFERIMENTO_ESTERO] CHECK CONSTRAINT [FK_TRASFERIMENTO_ESTERO_BANCA]
GO
ALTER TABLE [TRASFERIMENTO_ESTERO]  WITH CHECK ADD  CONSTRAINT [FK_TRASFERIMENTO_ESTERO_TRASFERIMENTO1] FOREIGN KEY([NUM_TRASF])
REFERENCES [TRASFERIMENTO] ([NUM_TRASF])
GO
ALTER TABLE [TRASFERIMENTO_ESTERO] CHECK CONSTRAINT [FK_TRASFERIMENTO_ESTERO_TRASFERIMENTO1]
GO
