
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SNOWFLAKE';

-- PATTERN {DATA, TIPO_FONDO, BANCA_ESTERA}

SELECT	DATA, FONDO_TIPO, BANCA_ESTERA,
		IMPORTO_MEDIO_P = SUM(IMPORTO_SOMMA_P) / COUNT(COUNT_IMPORTO_P),
		NUM_A_CONTO = CASE 
						WHEN GROUPING(DATA) = 1 THEN -1
						ELSE CASE 
								WHEN GROUPING(FONDO_TIPO) = 1 THEN SUM(NUM_A_CONTO_P) --SE AGGREGHI PESATA
								ELSE SUM(NUM_A_CONTO) -- NON PESATA
							 END
					  END
FROM SNOWFLAKE
GROUP BY DATA, FONDO_TIPO, BANCA_ESTERA WITH CUBE

